### ISSUE TITLE
[Feature] Add an option to filter out shorts

### ISSUE THREAD

**Issue by GauthierPLM** [iv-org/invidious#3263] opened 2022-08-12 09:28 UTC
Short videos are becoming more and more popular and start to appear very often in my subscriptions. However, in many cases they are just clips from main videos or are not very interesting.

I would love to have an option that allow to filter out these videos from my subscription feed so I don't have these shorts mixed with normal videos.

**Comment by unixfox** [comment] 2022-08-12 09:31
Already requested in https://github.com/iv-org/invidious/issues/2585

Duplicate of https://github.com/iv-org/invidious/issues/2585

**Closed by unixfox** 2022-08-12 09:31 UTC
