### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by captainspeedy68** [iv-org/invidious#2593] opened 2021-11-12 13:48 UTC
**Describe the bug**
Whatever I search this message comes up saying that I've found a new bug

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by syeopite** [comment] 2021-11-12 13:50
I'm guessing the error you got was something along the lines of `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`? 

If so it's caused by #2577, which should be fixed now.  If you're using a public instance, expect it to get resolved in the coming hours as instances update!

**Closed by syeopite** 2021-11-12 13:50 UTC
Labels: bug
