### ISSUE TITLE
[Bug] Can't open user profile

### ISSUE THREAD

**Issue by dik23** [iv-org/invidious#1864] opened 2021-03-05 01:01 UTC
Looks like you've found a bug in Invidious. Please open a new issue on GitHub and include the following text in your message:

> Title: `unexpected token '' at 1:1 (JSON::ParseException)`
Date: `2021-03-05T00:57:40Z`
Route: `/channel/UCF9IOB2TExg3QIBupFtBDxg?dark_mode=true&thin_mode=false`
Version: `2021.01.23-51ebec7 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from ../../../usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from ../../../usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
  from src/invidious.cr:1715:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by ytprivatecom** [comment] 2021-03-05 06:45
Duplicate of #1838

**Closed** 2021-03-05 08:22 UTC
Labels: duplicate
