### ISSUE TITLE
Searching for certain words results in no results being shown

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#979] opened 2020-01-07 16:00 UTC
When I search for unfathomable force, no results are being shown.

**Comment by haizrul** [comment] 2020-01-07 17:55
Looks okay : https://invidio.us/search?q=unfathomable+force

![Opera Snapshot_2020-01-08_015423_invidio us](https://user-images.githubusercontent.com/8771582/71916860-d629dd00-31b9-11ea-8624-16c72eac64d0.png)

**Comment by Zero3K** [comment] 2020-10-16 18:56
It happens randomly when refreshing the search results page.

**Comment by syeopite** [comment] 2021-10-02 15:28
Can you still reproduce this?

**Comment by unixfox** [comment] 2022-01-02 16:54
Closing due to a lack of replies.

**Closed by unixfox** 2022-01-02 16:54 UTC

**Comment by Zero3K** [comment] 2022-01-02 22:05
It is no longer happening for me.
