### ISSUE TITLE
[Bug] all video api requests include error field (Video unavailable) in the response

### ISSUE THREAD

**Issue by lekma** [iv-org/invidious#2133] opened 2021-06-06 17:39 UTC
all video api requests include error field (Video unavailable)in the response, that makes it very difficult to seperarate legit errors from valid answers.

working request from notyoutube.org:
https://notyoutube.org/api/v1/videos/El5XoB6EIZg?region=US (2021.05.04-4fc8905)

not working:
https://invidious.snopyta.org/api/v1/videos/El5XoB6EIZg?region=US (2021.05.26-4a45d10)
https://invidious.exonip.de/api/v1/videos/El5XoB6EIZg?region=US (2021.06.04-49ed485)

**Comment by lekma** [comment] 2021-06-06 17:45
73da8463caa39757678de04fb23c8015ffd6218c might be the culprit (pure guess, don't hit me :))

**Comment by unixfox** [comment] 2021-06-10 14:16
I don't understand the issue here, video unavailable means the video is probably not available in the country where the instance is hosted.
How is that a bug? It's working as intended.

**Comment by lekma** [comment] 2021-06-10 14:48
because, in fact, the video is available and if you ignore the error it plays fine.

**Comment by unixfox** [comment] 2021-06-10 15:47
I've looked a bit closely at the issue, and it's not the video that is unavailable due to a region restriction, but the invidious instance failed to fetch all the content from the video page because it is partially blocked by Google. The error message is very different from just "Video unavailable", it's this one instead: `Could not extract video info. Instance is likely blocked.`.

The instances are unable to fetch all the content due to a CAPTCHA returned by Google, but usually the public instance have an anti-captcha solution so maybe it fails to work correctly. You should contact the instance maintainer in order to ask them to fix this issue.

Unfortunately this is working as intended, the error is returned because Invidious is unable to fetch all the content needed for the video. As you can see, the video description is missing and no comment are loading: https://invidious.snopyta.org/watch?v=El5XoB6EIZg

I'm closing this issue because this is an expected behavior, if you want to get more reliable Invidious API results you should host your own instance.

**Closed by unixfox** 2021-06-10 15:47 UTC
Labels: bug
