### ISSUE TITLE
Found a bug in Invidious. Please open a new issue on GitHub

### ISSUE THREAD

**Issue by emwihs3** [iv-org/invidious#1752] opened 2021-02-08 22:30 UTC
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2021-02-08T22:23:19Z`
Route: `/watch?v=RgV9CTTymTA`
Version: `2021.01.17-e6a40b3 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_one?:as'
  from src/invidious/videos.cr:933:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-02-08 22:34
This appears to be a duplicate of #1582. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-02-08 22:34 UTC
Labels: duplicate
