### ISSUE TITLE
[Bug] Read timeout

### ISSUE THREAD

**Issue by ydubernet** [iv-org/invidious#2087] opened 2021-05-15 21:37 UTC
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-05-15T21:33:24Z`
Route: `/watch?v=6U6ZcdVl7JA`
Version: `2021.05.04-4fc8905 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from /usr/share/crystal/src/io/evented.cr:120:39 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from lib/pool/src/pool.cr:55:7 in 'checkout'
  from src/invidious/helpers/utils.cr:35:14 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2021-05-16 00:40
Duplicate of #1132

**Closed by syeopite** 2021-05-16 00:40 UTC
