### ISSUE TITLE
[Bug] Cannot subscribe to a particular channel

### ISSUE THREAD

**Issue by rramiachraf** [iv-org/invidious#2774] opened 2022-01-06 16:06 UTC
**Describe the bug**
Not aware of other channels that has the same issue, but when you try to subscribe to this particular one it throws a 500 error. 

**Steps to Reproduce**
1. Go to an Invidious instance that provides account functionality
2. Go to this channel `/channel/UCvuoyvO5ae3EpxQoLErgR2Q`
3. Click on the `Subscribe` button.
(Open the Network Manager in your browser to see the full error rather than a UI function.)

**Logs**
Title: `duplicate key value violates unique constraint "channels_id_key" (PQ::PQError)`
Date: `2022-01-06T15:45:33Z`
Route: `/subscription_ajax?action_create_subscription_to_channel=1&redirect=false&c=UCvuoyvO5ae3EpxQoLErgR2Q`
Version: `2022.01.05-7d8b3a8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
duplicate key value violates unique constraint "channels_id_key" (PQ::PQError)
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'handle_error'
  from lib/pg/src/pq/connection.cr:225:65 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:415:59 in 'move_next'
  from lib/db/src/db/result_set.cr:39:13 in 'exec:args'
  from src/invidious.cr:596:7 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by unixfox** [comment] 2022-01-06 16:56
Which instance are you using?

**Comment by SamantazFox** [comment] 2022-01-06 18:53
I can't reproduce that on our test instance:

```
2022-01-06T18:37:17.599541Z  DEBUG - db: Executing query -- query: "  UPDATE users\n  SET feed_needs_update = true,\n      subscriptions = array_append(subscriptions,$1)\n  WHERE email = $2", args: ["UCvuoyvO5ae3EpxQoLErgR2Q", "samantazfox"]

2022-01-06 18:37:17 UTC [info] 200 POST /subscription_ajax?action_create_subscription_to_channel=1&redirect=false&c=UCvuoyvO5ae3EpxQoLErgR2Q 193.5ms
```

**Comment by unixfox** [comment] 2022-01-06 21:13
Issue fixed on yewtu.be

**Closed by unixfox** 2022-01-06 21:13 UTC
Labels: bug
