### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MakaryGo** [iv-org/invidious#2051] opened 2021-04-30 11:16 UTC
**Describe the bug**

Error when trying to display a channel
**Steps to Reproduce**

**Logs**
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-04-30T11:14:56Z`
Route: `/channel/UCYqUgCOQqsdaUkIw6RtKGhw`
Version: `2021.04.21-bfd02ac @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from /usr/share/crystal/src/io/evented.cr:120:39 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from lib/pool/src/pool.cr:55:7 in 'checkout'
  from src/invidious/helpers/utils.cr:35:14 in 'get_about_info'
  from src/invidious.cr:1672:15 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-04-30 15:52
This appears to be a duplicate of #1508. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-04-30 15:52 UTC
Labels: duplicate
