### ISSUE TITLE
[Enhancement] Make it easier to hover over the slider in the YouTube-styled player

### ISSUE THREAD

**Issue by Mennaruuk** [iv-org/invidious#2104] opened 2021-05-20 22:57 UTC
**Is your enhancement request related to a problem? Please describe.**

I don't know how to best put this into words, so I made a video. Basically, it's more cumbersome to hover over the new YouTube-styled player's slider compared to YouTube's.

https://user-images.githubusercontent.com/52135169/119058608-b6edb300-b99c-11eb-982a-46352fc1d639.mp4

**Describe the solution you'd like**

It'd be awesome if the YouTube effect of making it easier to hover over the slider can be replicated.

**Describe alternatives you've considered**

The Invidious-styled player does it better than the YouTube-styled player.

**Additional context**

Thanks for your great work!

**Comment by ottersarecool** [comment] 2021-05-20 23:31
Actually working on something like thar right now with another person in the invidious matrix room



https://user-images.githubusercontent.com/51519051/119061252-39459980-b9d4-11eb-826e-be732edd4abd.mp4

**Comment by syeopite** [comment] 2021-05-21 03:13
Duplicate of #2080

**Closed by syeopite** 2021-05-21 03:13 UTC
Labels: enhancement
