### ISSUE TITLE
Videos stopping/freezing with no buffering indicator

### ISSUE THREAD

**Issue by Hepativore** [iv-org/invidious#3841] opened 2023-06-02 19:19 UTC
I tried searching to see if this has already been mentioned, and I did not find anything, as I do not know if I am phrasing this correctly. Feel free to move this or merge this where it belongs.

Does anybody know why videos will often freeze and stop loading, with no indication of buffering, or anything like that? If you leave the video alone, it will "finish" playing, as the seeker bar will go all the way towards the end of the video after the video has frozen itself for awhile without actually playing the part of the video from when it froze itself.

Switching instances does not seem to help, as it appears to be an Invidious-wide problem, so is it something I am doing on my end?

**Comment by unixfox** [comment] 2023-06-02 19:36
Duplicate of https://github.com/iv-org/invidious/issues/882

**Closed by unixfox** 2023-06-02 19:36 UTC
