### ISSUE TITLE
Cannot view certain videos

### ISSUE THREAD

**Issue by ddilans** [iv-org/invidious#1312] opened 2020-07-29 20:39 UTC
I have tried under both palemoon and firefox, https://invidious.snopyta.org/watch?v=_CL6n0FJZpk as an example video that doesn't work. This has both the same result on this and the official invidio.us instance.

I get the "The media could not be loaded, either because the server or network failed or because the format is not supported." error, and in the javascript console under firefox I see:
```
Error: failed to request sidx video.min.js:21:90574
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.min.js:12:695
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). player.js:64:19
An error occured in the player, reloading...
```
whilst under palemoon it reports:
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The media could not be loaded, eith…" }  
video.min.js:12:661
HTTP load failed with status 403. Load of media resource https://invidious.snopyta.org/latest_version?id=_CL6n0FJZpk&itag=18&local=true failed.
```

The only extension installed is umatrix which is set to allow all for these test so it does not affect it, none of this is in /etc/hosts. Most videos work fine, but some such as this simply do not.

Oddly enough, if I try watching them under Freetube, which uses the invidious api, they work fine, and they can also be loaded with NewPipe and youtube-dl aswell.

This fails whether or not proxy videos is enabled; obviously with the media resource failing being from googlevideo and not invidious itself if it's off.

**Comment by Perflyst** [comment] 2020-07-31 19:13
Duplicate of #92 - but thanks for your detailed report. If you have any questions after looking into #92 let us know

**Closed by Perflyst** 2020-07-31 19:13 UTC
