### ISSUE TITLE
Support for opening in local players

### ISSUE THREAD

**Issue by notpushkin** [iv-org/invidious#806] opened 2019-10-07 20:17 UTC
This should somewhat ease the load on Invidious instances (DASH videos can be played without proxying the streams) and keep power users / mpv fanatics (like me) happy. I'm not sure if it's _that_ useful, just wanted to throw in an idea. What do you think?

My setup right now:

1. <details><summary>A <code>.desktop</code> file registering a custom protocol, <code>ytdl</code>, and</summary>

   ```ini
   [Desktop Entry]
   Version=1.0
   Type=Application
   Name=ytdl scheme handler
   NoDisplay=true
   Exec=bash -c 'mpv "${1#ytdl:}"' -- %u
   MimeType=x-scheme-handler/ytdl
   ```

   <sup>For macOS, it would probably be a small helper application [bundle](http://hublog.hubmed.org/archives/001154.html), and on Windows we'll obviously go for [registry](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN).</sup>
   </details>

2. A userscript that replaces the player with a link to this custom protocol (e. g. `https://invidio.us/watch?v=xxxxxx` → `ytdl:https://youtube.com/watch?v=xxxxxx`).

**Comment by randrej** [comment] 2019-11-22 20:35
Great idea + a sane solution. How come nobody else is interested?

**Comment by elypter** [comment] 2019-11-23 15:01
sounds great. especially for older pcs that cannot run videos in the browser without framedrops.

**Comment by notpushkin** [comment] 2020-12-27 21:32
> If you think this issue is still relevant and applicable, please let us know.

It is!

**Comment by elypter** [comment] 2020-12-27 22:15
it's still a good and achievable idea

**Comment by Mennaruuk** [comment] 2021-01-30 08:44
Absolutely, would love to play in MPV!

**Comment by Mennaruuk** [comment] 2022-02-03 02:57
BUMP

**Comment by unixfox** [comment] 2022-02-03 07:49
> BUMP

This seems like a simple feature to implement. Would you be interested to contribute to invidious for adding this feature?

**Comment by notpushkin** [comment] 2022-02-03 11:26
I've updated my proposal with a bit more vendor-neutral `ytdl:` protocol – this removes the connotations that it will only be used with Invidious or YouTube, and instead means something along the lines of "open this in any player that works with youtube-dl".

**Comment by unixfox** [comment] 2022-04-17 21:12
Duplicate of https://github.com/iv-org/invidious/issues/2533

**Closed by unixfox** 2022-04-17 21:12 UTC
Labels: enhancement

**Comment by notpushkin** [comment] 2022-04-17 22:20
Uhhhhh okay I guess
