### ISSUE TITLE
[Bug] Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)

### ISSUE THREAD

**Issue by SArpnt** [iv-org/invidious#3210] opened 2022-07-19 01:57 UTC
**Describe the bug**
as far as i can tell this happens when trying to view a video that hasn't yet premiered

**Steps to Reproduce**
(might not work soon due to the premiere)
go to the videos `/watch?v=3FwMkFsAeO0` or `/watch?v=mCQKvZXRwM8`

**Logs**
Title: `Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)`
Date: `2022-07-19T01:47:20Z`
Route: `/watch?v=mCQKvZXRwM8`
Version: `2022.07.15-956d3e8 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)
  from /usr/lib/crystal/core/json/any.cr:102:10 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:1099:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Additional context**.
 - Browser: Librewolf 102.0.1
 - OS: Artix Linux

**Comment by unixfox** [comment] 2022-07-19 06:52
Duplicate of https://github.com/iv-org/invidious/issues/3200

**Closed by unixfox** 2022-07-19 06:52 UTC
Labels: bug
