### ISSUE TITLE
[Bug] Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)

### ISSUE THREAD

**Issue by nonchalantPuffin** [iv-org/invidious#4260] opened 2023-11-13 13:14 UTC
Title: `Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)`
Date: `2023-11-13T13:13:36Z`
Route: `/channel/UC4R8DWoMoI7CAwX8_LjQHig`
Version: `2023.11.08-c5b87e3 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from src/invidious/channels/about.cr:47:14 in 'get_about_info'
  from src/invidious/routes/channels.cr:372:17 in 'fetch_basic_information'
  from src/invidious/routes/channels.cr:15:12 in 'videos'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2023-11-13 23:52
Duplicate of #2137

**Closed by syeopite** 2023-11-13 23:52 UTC
Labels: bug
