### ISSUE TITLE
[Bug] yewtu.be:  'Can't load the video on this Invidious instance. YouTube is currently trying to block Invidious instances. Click here for more info about the issue.'

### ISSUE THREAD

**Issue by sunlightspectre** [iv-org/invidious#4478] opened 2024-03-09 17:35 UTC
**Describe the bug**

I get an old prompt when using many instances - most prominently yewtu.be, which I prefer - to access videos.  
Video access is random; it seems like I can view a handful of videos, and then nothing for a period of time.   
Switching through instances 'helps,' but does not seem to guarantee access.  
Due to the impression this was an older issue, I can only conclude this is a bug.  

**Steps to Reproduce**

1. Goto yewtu.be
2. Search videos
3. Click videos
4. After so many videos, goto 'Can't load the video on this Invidious instance. YouTube is currently trying to block Invidious instances. Click here for more info about the issue.'

**Additional context**

 - Waterfox G6.0.9
 - Win10 Pro 64-bit

**Comment by unixfox** [comment] 2024-03-09 18:11
https://github.com/yewtudotbe/invidious-custom/issues

Duplicate of https://github.com/iv-org/invidious/issues/4045

**Closed by unixfox** 2024-03-09 18:11 UTC
Labels: bug
