### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Trencaste** [iv-org/invidious#2797] opened 2022-01-10 00:58 UTC
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2022-01-10T00:54:34Z`
Route: `/watch?v=7-jGM-6DBsU`
Version: `2022.01.08-67cb8b71 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'select'
  from src/invidious/videos.cr:997:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>
Several of the videos under this search do not work.
https://vid.puffyan.us/search?q=mental+outlaw+verizon+germany

https://vid.puffyan.us/watch?v=7-jGM-6DBsU

The original bug that I found did not allow this video to be opened:
https://www.youtube.com/watch?v=7-jGM-6DBsU

**Comment by SamantazFox** [comment] 2022-01-10 01:02
Try to use another instance!
https://redirect.invidious.io/watch?v=7-jGM-6DBsU

**Comment by Trencaste** [comment] 2022-01-10 01:05
> Try to use another instance! https://redirect.invidious.io/watch?v=7-jGM-6DBsU

Indeed.
Even so, I like using the one I have because I normally use it.
I am just bringing this up to those who may know how to fix it.

Apparently a lot of his YouTube videos are being flagged somehow.
https://vid.puffyan.us/channel/UC7YOGHUfC1Tb6E4pudI9STA

Here are the ones I have found to be flagged:
https://vid.puffyan.us/watch?v=g3BQ41KGB5U

https://vid.puffyan.us/watch?v=XaHWcttD0tM

https://vid.puffyan.us/watch?v=GlO9CIrIsKE

https://vid.puffyan.us/watch?v=g9xK44imGVc

https://vid.puffyan.us/watch?v=Y0DRqDAF7D4

https://vid.puffyan.us/watch?v=Lk_v6Q0YsNo

**Comment by Trencaste** [comment] 2022-01-10 01:21
Using a different instance for all of these btw, but for whoever knows how to fix this, please let me know.

https://vid.puffyan.us/watch?v=E7wPG54cfgI

**Comment by unixfox** [comment] 2022-01-10 09:43
Duplicate of #1582

**Closed by unixfox** 2022-01-10 09:43 UTC
Labels: bug
