### ISSUE TITLE
[Bug] Very slow loading times of thumbnails

### ISSUE THREAD

**Issue by nickelswitte** [iv-org/invidious#3506] opened 2022-12-19 11:11 UTC
**Describe the bug**
While loading feeds (subscriptions, watch history as well as single videos) the fetching of thumbnails seem to take a very long time, slowing down the whole website strongly. See below some screenshots.

**Steps to Reproduce**

Not so sure how to reproduce, as I host Invidious normally via Docker Compose with no extraordinary settings.
Maybe its worth to mention that I proxy the videos through my server using `local: true` as settings.

**Logs**

```
invidious     | 2022-12-19 10:56:48 UTC [info] 200 GET /feed/subscriptions 13.14ms
invidious     | 2022-12-19 10:57:18 UTC [info] 200 GET /vi/w0mOxU9EsEs/mqdefault.jpg 28899.4ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/OoCnJGENAn0/mqdefault.jpg 27090.39ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/cBFOwr5Bxd0/mqdefault.jpg 27077.03ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/xssgULcXN2I/mqdefault.jpg 24542.39ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/ilLnpe9OIL0/mqdefault.jpg 24520.82ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/rpUEkHJIu4Q/mqdefault.jpg 21989.82ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/nK9wYzIEk_g/mqdefault.jpg 21972.33ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/Tv708p4gq5g/mqdefault.jpg 21827.32ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/QCrt8-cIfSg/mqdefault.jpg 21812.97ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/ZtTbbeCzVlw/mqdefault.jpg 21799.38ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/QILido6eoX4/mqdefault.jpg 21747.06ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/GgrtPH9UFGU/mqdefault.jpg 21732.78ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/kH5lND3p_sg/mqdefault.jpg 21717.19ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/l7fs4FFb99w/mqdefault.jpg 19363.22ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/HIxFcuVjxJE/mqdefault.jpg 16845.51ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/JZ7BCO9A2yg/mqdefault.jpg 14329.91ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/O7dCNG4CxB0/mqdefault.jpg 11303.0ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /vi/ezV_so1C_RE/mqdefault.jpg 11210.29ms
invidious     | 2022-12-19 10:57:19 UTC [info] 200 GET /feed/history 5.27ms
```

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36443026/208411314-07747f96-f21a-441e-aa40-4656c082ec63.png)

This is how it looks for around 10 seconds each time.
![grafik](https://user-images.githubusercontent.com/36443026/208412307-f49eb360-6586-4d43-99ea-9d62b09f4b39.png)

**Comment by nickelswitte** [comment] 2022-12-19 11:41
Yes, I wanted to mention that:
* The server is not overloaded. CPU is usually below 10% and when using a VPN on the same server, I get around 100MBits of up and downstream. So that should be fine
* About the DNS, I am not sure. I recently played with the DNS around a bit (in an attempt to install AdGuard), but returned everything to its original state (as far as I know). Is there a way to test if the DNS is working okay? 

How I use invidious currently:
Client -> Wireguard VPN tunnel to server -> Invidious on the same server -> Exposed to public internet with no further VPN

**Comment by unixfox** [comment] 2022-12-19 13:06
Check in your /etc/resolv.conf if you don't have dead DNS servers.

You can also use `nslookup` or `dig` in order to check for the response time of a DNS request.

**Comment by unixfox** [comment] 2022-12-21 06:02
Closing due to lack of replies and bug unreproducible locally.

**Closed by unixfox** 2022-12-21 06:03 UTC
Labels: bug
