### ISSUE TITLE
[Bug] The media could not be loaded

### ISSUE THREAD

**Issue by Yumega** [iv-org/invidious#4027] opened 2023-08-04 10:49 UTC
**Describe the bug**

most videos can play, but only a few videos can't play

**Steps to Reproduce**

xxx.com/watch?v=Srjk6_j8J04
**Logs**

The media could not be loaded, either because the server or network failed or because the format is not supported.
**Screenshots**

![image](https://github.com/iv-org/invidious/assets/61570667/1392e5c6-56c7-425f-bfe2-ebf231dce1c4)

**Additional context**

**Comment by unixfox** [comment] 2023-08-04 10:54
Is this a public instance or a private one?

**Comment by unixfox** [comment] 2023-08-04 14:19
Can you look at the Network tab from the devtools and check the requests, see if there are any errors. If so please report them

I did test with the video ID given and that was working fine for me: https://invidious.projectsegfau.lt/watch?v=Srjk6_j8J04

**Comment by rockerBOO** [comment] 2023-08-04 15:37
Specifically for me it returns 
```
2023-08-04 14:34:00 UTC [info] 403 GET /videoplayback?expire=1691181044&...
```
And does so in rapid fashion (3 per second at least) on the frontend. Maybe it's making too many requests?

**Comment by unixfox** [comment] 2023-08-04 15:43
> Specifically for me it returns
> 
> ```
> 2023-08-04 14:34:00 UTC [info] 403 GET /videoplayback?expire=1691181044&...
> ```
> 
> And does so in rapid fashion (3 per second at least) on the frontend. Maybe it's making too many requests?
> 
> `Current version: 2023.08.03-bfca043c`

Which instance (public or private)? Which video ID?

**Comment by rockerBOO** [comment] 2023-08-04 15:57
> > Specifically for me it returns
> > ```
> > 2023-08-04 14:34:00 UTC [info] 403 GET /videoplayback?expire=1691181044&...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And does so in rapid fashion (3 per second at least) on the frontend. Maybe it's making too many requests?
> > `Current version: 2023.08.03-bfca043c`
> 
> Which instance (public or private)? Which video ID?

Private, videoId: nxKNibbjrbQ 

Tried HD720 and DASH quality. 

HD720 generally works OK. 

But DASH does the rapid fire and 403. Now getting 206s in rapid fire. 

```
2023-08-04 15:54:13 UTC [info] 206 GET /videoplayback?expire=1691185995&...
```

Noting that this happens on newer videos only as many older videos work fine. But occasionally older videos might stop working for me but work fine after waiting some time. I think it might be related to trying to watch newer videos and then some rate limiting is happening (due to the rapid fire of the requests) or something.

**Comment by xortuna** [comment] 2023-08-04 18:03
Having similar issues on multiple instances E.g
https://invidious.projectsegfau.lt/watch?v=uMxrDOvzD1o

Seem to be getting 403 errors on videoload.js:

![Screenshot 2023-08-04 190137](https://github.com/iv-org/invidious/assets/3997742/5fcf2ba9-e5ba-4bdb-a613-1b2ed537e8a9)

**Comment by a7maadf** [comment] 2023-08-04 23:54
I'm encountering the same problem on my private instance. I have attempted nearly every solution, including rebuilding the instance from scratch. For now, my temporary workaround is viewing the video on a different public instance.

**Comment by thebozzcl** [comment] 2023-08-05 01:39
I'm having this issue with a not-so-new (1 day old) video: `PFD6i2ix9kw`. I'm running version `2023.08.04-701f03d` from `quay.io/invidious/invidious:latest-arm64`.

Here's an example query where I'm seeing a 403: https://mydomain/videoplayback?expire=1691220424&ei=aKXNZKOcEf6KsfIPzu6myA0&ip=MY_IP&id=o-AHoR6Q8k9pSGHtBLIz_ZWvvLQs9H-Uz7EW2Re_D9pJWA&itag=298&source=youtube&requiressl=yes&mh=Ip&mm=31%2C29&mn=sn-jxou0gtapo3-nx5e%2Csn-nx57ynss&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=20&initcwndbps=846250&spc=UWF9f9r0ojO7vItVfMpH_bAFrKa8yIcuO6cmE0iEGw&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=157059399&dur=1246.244&lmt=1691047622177353&mt=1691198510&fvip=2&keepalive=yes&fexp=24007246%2C24363392&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALlICz2UM8s_vOHASUt8iebEzujsbOXps9Ifg1dwOjgwAiEAluZh047lxThV5G28IWz7-DCVaQVEF-Dufd4BGI-8ZMw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgJ2XUDODo_bbxvfljJcR8hTUbBNbFySjQWYGK3DfYqtMCIQD15wr9kIUGOCm4bbgxX__8bPoyjm190hOzfZw6KcjRvw%3D%3D&host=rr2---sn-jxou0gtapo3-nx5e.googlevideo.com

**Comment by anoo2niem** [comment] 2023-08-05 11:08
Running private instance here, lately running into this issue more frequently aswell

**Comment by mycosavant** [comment] 2023-08-05 14:09
I'm having this same issue on multiple public instances, including the links provided in this thread.

**Comment by absidue** [comment] 2023-08-05 20:39
Question for everyone in the thread, have you enabled video proxying?

I'm wondering if YouTube might not like the IP of the server requesting the watch page being different to the computer that is actually requesting the video and audio data.

**Comment by anoo2niem** [comment] 2023-08-05 20:46
> Question for everyone in the thread, have you enabled video proxying?
> 
> I'm wondering if YouTube might not like the IP of the server requesting the watch page being different to the computer that is actually requesting the video and audio data.

For me i can confirm, proxying enabled

**Comment by xortuna** [comment] 2023-08-05 20:58
Tried enabled and disabled didn’t seem to make a difference at the time, yet to have the issue today

**Comment by a7maadf** [comment] 2023-08-05 21:01
> Question for everyone in the thread, have you enabled video proxying?
> 
> I'm wondering if YouTube might not like the IP of the server requesting the watch page being different to the computer that is actually requesting the video and audio data.

When I use proxying, I notice the issue on all videos. But when I turn it off, only a handful show that error. Not sure what's the common factor with those videos, but that's what I'm seeing. Anyone else?

**Comment by a7maadf** [comment] 2023-08-05 21:16
Allso, D

> Question for everyone in the thread, have you enabled video proxying?
> 
> I'm wondering if YouTube might not like the IP of the server requesting the watch page being different to the computer that is actually requesting the video and audio data.

When I use proxying, I notice the issue on all videos. But when I turn it off, only a few videos have that problem. I've been scratching my head trying to figure out what links those specific videos. The issue seems to pop up with the 'googlevideo.com' link. I even tried turning off my VPN, disabling my custom DNS, and switching both devices and networks. But no luck – none of these tweaks made any difference.

![image](https://github.com/iv-org/invidious/assets/89315818/a7b09a69-26b7-43d7-af3e-e5848ab83767)

**Comment by FavoritoHJS** [comment] 2023-08-05 21:34
you beat me to making this issue...guess i'll copy-paste what I would have submitted in case it is helpful.

-----




**Describe the bug**

Every now and then, a video fails to load with a "The media could not be loaded[...]" error. After some time the error disappears.

**Steps to Reproduce**

1. Watch a lot of videos. This issue is extremely rare, don't be surprised if it takes a long time to trigger.
2. One of the videos will say "The media could not be loaded[...]".
   Notice the video continually refreshes, like it's trying to load... and failing every time.
3. After a few minutes, the video magically loads like normal.





**Additional context**

Something interesting is that, when this bug happens, it attempts to play from the instance, like using a proxy... but the option to use a proxy is disabled.
I wonder if this could be poor handling of rate limiting or general network instability, as forcing a proxy is normal behavior for if a video fails to load.

Comparing the request of a video with this problem, and videos without this problem, I found the following:
- The "spc" argument is considerably longer with a faulty video than the same video (or most other videos!) when actually working(42 instead of 31, a change of 11 characters)
- Additionally, it had a longer than usual "sig"... though I'm doubtful about the importance of this, since a known-good video also had these properties.

**Comment by Joshndroid** [comment] 2023-08-06 05:22
Private, self hosted instance. 
I have been seeing this quite recently as well.
I can see that on a newer video I seem to get it more often.
I also seem to get it more on DASH quality than on HD720 (so i have mine just set to HD720)
Proxy on or off didn't make a difference

**Comment by andre4ik3** [comment] 2023-08-06 18:34
Related: NewPipe [had the same issue](https://github.com/TeamNewPipe/NewPipe/issues/10174), but [they fixed it](https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084) by implementing a workaround in v0.25.2.

(*As far as I understand, correct me if I'm wrong*) This is a new integrity check YouTube is currently rolling out through A/B testing. The 403 error means Invidious is failing the integrity check and thus YouTube is denying it access to the video.

The reason that it only happens on some videos, and that the rate seems to be increasing, is that YouTube is rolling it out as an A/B test, meaning they start with a small % of videos, then increase as time goes on until in the end all videos have this protection and Invidious won't be able to play anything at all.

**Comment by unixfox** [comment] 2023-08-06 18:57
Thanks @andre4ik3. We were made aware of this special parameter: https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084/files#diff-e07bd9a3dfb657e0ac68c2847533825c0c25d9cc8486c9a5a0dab1d413d54d42R986

We will have to implement it.

**Comment by a7maadf** [comment] 2023-08-06 19:02
> Thanks @andre4ik3. We were made aware of this special parameter a month ago but did not yet implement: https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084/files#diff-e07bd9a3dfb657e0ac68c2847533825c0c25d9cc8486c9a5a0dab1d413d54d42R986
> 
> 
> 
> We will implement it.

Thank you for your efforts

**Comment by anoo2niem** [comment] 2023-08-06 19:33
> > Thanks @andre4ik3. We were made aware of this special parameter a month ago but did not yet implement: https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084/files#diff-e07bd9a3dfb657e0ac68c2847533825c0c25d9cc8486c9a5a0dab1d413d54d42R986
> > We will implement it.
> 
> Thank you for your efforts

Agreed, many thanks for this project

**Comment by syeopite** [comment] 2023-08-06 19:39
Here's a quick patch that implements NewPipe's workaround. Can anyone see if this fixes the problem? Please clear or wait until the video cache expires when doing so. 

<details>
<summary> Patch </summary>

```patch
From 2f6b2688bb8042c29942e46767dc78836f21fb57 Mon Sep 17 00:00:00 2001
From: syeopite <syeopite@syeopite.dev>
Date: Sun, 6 Aug 2023 12:20:05 -0700
Subject: [PATCH] Use workaround for fetching streaming URLs

YouTube appears to be A/B testing some new integrity checks. Adding the
parameter "CgIQBg" to InnerTube player requests appears to workaround
the problem

See https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084
---
 src/invidious/videos/parser.cr | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)

diff --git a/src/invidious/videos/parser.cr b/src/invidious/videos/parser.cr
index 9cc0ffdc..2a09d187 100644
--- a/src/invidious/videos/parser.cr
+++ b/src/invidious/videos/parser.cr
@@ -55,8 +55,9 @@ def extract_video_info(video_id : String, proxy_region : String? = nil)
   client_config = YoutubeAPI::ClientConfig.new(proxy_region: proxy_region)
 
   # Fetch data from the player endpoint
-  # 8AEB param is used to fetch YouTube stories
-  player_response = YoutubeAPI.player(video_id: video_id, params: "8AEB", client_config: client_config)
+  # CgIQBg is a workaround for streaming URLs that returns a 403.
+  # See https://github.com/iv-org/invidious/issues/4027#issuecomment-1666944520
+  player_response = YoutubeAPI.player(video_id: video_id, params: "CgIQBg", client_config: client_config)
 
   playability_status = player_response.dig?("playabilityStatus", "status").try &.as_s
 
@@ -135,8 +136,9 @@ end
 
 def try_fetch_streaming_data(id : String, client_config : YoutubeAPI::ClientConfig) : Hash(String, JSON::Any)?
   LOGGER.debug("try_fetch_streaming_data: [#{id}] Using #{client_config.client_type} client.")
-  # 8AEB param is used to fetch YouTube stories
-  response = YoutubeAPI.player(video_id: id, params: "8AEB", client_config: client_config)
+  # CgIQBg is a workaround for streaming URLs that returns a 403.
+  # See https://github.com/iv-org/invidious/issues/4027#issuecomment-1666944520
+  response = YoutubeAPI.player(video_id: id, params: "CgIQBg", client_config: client_config)
 
   playability_status = response["playabilityStatus"]["status"]
   LOGGER.debug("try_fetch_streaming_data: [#{id}] Got playabilityStatus == #{playability_status}.")
-- 
2.41.0

```
</details>

**Comment by andre4ik3** [comment] 2023-08-06 20:37
Looks like the patch is working. After setting up a Linux VM and figuring out how to install all the dependencies, I did a before and after of the patch. Before the patch, clicking on random videos in trending, I'd say there is like a 30% chance of getting the error. After applying the patch and clicking more videos (lower down in the trending page, not the same ones because clicking the same ones will still result in error until video cache clears), I haven't had a single media error. Nice job!

**Comment by Despernal** [comment] 2023-08-06 21:15
I have patched the source and built the docker container locally and switched my docker stack over and have not had the problem anymore. I was having it happen non stop all day, have clicked and played about 60 videos now with no problem.
Thank you for the patch and your hard work on this project, very thankful.

**Comment by m4teh** [comment] 2023-08-06 22:44
Fantastic work all. Definitely been hit hard in the past week with most videos 403'ing. I was worried the "crackdown" was going to be the start of the end of the Invidious glory days, but replies above rest for now.

**Comment by a7maadf** [comment] 2023-08-06 23:18
> Here's a quick patch that implements NewPipe's workaround. Can anyone see if this fixes the problem? Please clear or wait until the video cache expires when doing so.
> Patch

Deployed it to my instance; no issues whatsoever. 
Would you consider opening a pull request?

**Comment by anoo2niem** [comment] 2023-08-06 23:46
Hi

 I changed parser.cr according to the provided patch, then i ran make from the invidious directory.
 i've restarted the invidious service, but on the video /watch?v=IHs-QqUik4E i still get the issue?
 
 Did i do something wrong?

**Comment by a7maadf** [comment] 2023-08-06 23:51
You will have to rebuild it (I'm using https://github.com/tmiland/Invidious-Updater)

------- Original Message -------

**Comment by anoo2niem** [comment] 2023-08-06 23:53
Sorry if i sound stupid but didn't i just rebuild it with make?

**Comment by a7maadf** [comment] 2023-08-07 00:04
to be honest I'm really not sure since I always use the [invidious updater](https://github.com/tmiland/Invidious-Updater), but yeah it seems like the make​ command is what rebuilds it

> Update a manual install
>
> https://docs.invidious.io/installation/#__codelineno-16-1
> su
>
> -
>
> invidious
> https://docs.invidious.io/installation/#__codelineno-16-2
> cd
>
> invidious
>
> git pull
>
> ​
> https://docs.invidious.io/installation/#__codelineno-16-4
> make
> https://docs.invidious.io/installation/#__codelineno-16-5
> exit
>
> https://docs.invidious.io/installation/#__codelineno-16-6
> systemctl
>
> restart
>
> invidious.service

I would try clearing the browser cache
------- Original Message -------

**Comment by a7maadf** [comment] 2023-08-07 00:07
> Sorry if i sound stupid but didn't i just rebuild it with make?

Rewriting cause apparently GitHub missed up the formatting 

to be honest I'm really not sure since I always use the [invidious updater](https://github.com/tmiland/Invidious-Updater), but yeah it seems like the make​ command is what rebuilds it

> **Update a manual install**
> 
> su - invidious
> cd invidious
> ~~git pull~~​
> make
> exit
> systemctl restart invidious.service


I would try clearing the browser cache

**Comment by bbsixzz** [comment] 2023-08-07 06:44
> Fantastic work all. Definitely been hit hard in the past week with most videos 403'ing. I was worried the "crackdown" was going to be the start of the end of the Invidious glory days, but replies above rest for now.

I'm glad there is a fix coming, it's seriously debilitating right now.

**Comment by syeopite** [comment] 2023-08-07 19:19
> Here's a quick patch that implements NewPipe's workaround. Can anyone see if this fixes the problem? Please clear or wait until the video cache expires when doing so.

Thanks for testing everyone! I've went ahead and opened up #4037 which will fix the issue once merged

**Closed** 2023-08-07 19:29 UTC
Labels: bug

**Comment by alex27riva** [comment] 2023-08-08 10:20
> EDIT: NVM, I just tried disabling Pi-hole and the problem went away. Time to look at my DNS logs.

Check `Pi-hole diagnosis` page in PiHole, you'll see a message like this: `Client 192.168.1.xx has been rate-limited (current config allows up to 1000 queries in 60 seconds)`
