### ISSUE TITLE
[Bug] Missing hash key: "navigationEndpoint" (KeyError)

### ISSUE THREAD

**Issue by AahanKotian** [iv-org/invidious#3812] opened 2023-05-18 16:00 UTC
I found a bug after trying to search "Replay Value" in the search bar on the yewtu.be instance. I tried all the possible alternatives to fix the problem. This is what it looked like:

Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2023-05-18T17:23:15Z`
Route: `/search?q=Replay+Value`
Version: `2023.05.18-8cfc99f @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/lib/crystal/core/json/any.cr:100 in '[]'
  from /usr/lib/crystal/core/json/any.cr:139:5 in 'dig'
  from /usr/lib/crystal/core/json/any.cr:215:3 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:279:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:783:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:830:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'process'
  from src/invidious/routes/search.cr:56:7 in 'search'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by SamantazFox** [comment] 2023-05-21 17:48
Ah, I'm able to get that error from time to time on the test instance!
Might be a duplicate of #2530 ?

**Comment by Fijxu** [comment] 2023-08-08 23:52
I just got this error on my public instance and other 3 instances where I tested to ensure that is not a problem from my instance

```
Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2023-08-08T23:42:57Z`
Route: `/search?q=The+Strxwberry+Vault+`
Version: `2023.08.07-34508966 @ master`

Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/lib/crystal/hash.cr:1077:11 in '[]'
  from /usr/lib/crystal/json/any.cr:115:7 in '[]'
  from /usr/lib/crystal/json/any.cr:151:5 in 'dig'
  from src/invidious/yt_backend/extractors.cr:774:12 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:279:41 in 'parse'
  from src/invidious/yt_backend/extractors.cr:266:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:792:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:839:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'regular'
  from src/invidious/search/query.cr:116:9 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/routing.cr:170:20 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:5 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/lib/crystal/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/http/server.cr:521:5 in 'handle_client'
  from /usr/lib/crystal/http/server.cr:451:5 in '->'
  from /usr/lib/crystal/fiber.cr:146:11 in 'run'
  from /usr/lib/crystal/fiber.cr:98:34 in '->'
  from ???
```

## Instances where I was able to reproduce this:

- inv.zzls.xyz (mine)
- invidious.flokinet.to
- vid.priv.au

Either `Route: /search?q=The+Strxwberry+Vault` and `Route: /search?q=The+Strxwberry+Vault+` give this error.

**Comment by poretsky** [comment] 2023-10-27 19:43
I've come across this as well on my local instance. Then tried
yewtu.be and got just the same result. Here is the trace log:

Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2023-10-27T18:49:12Z`
Route: `/channel/UCnVc-IW8Q98qFmQcXla5FdQ/podcasts`
Version: `2023.10.20-0e4d3d8 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:332:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:477:17 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/routes/channels.cr:130:32 in 'podcasts'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by Phos09** [comment] 2023-10-28 22:04
Oh this is a general issue?  I ran into it by searching for "darmok", and I was suspecting it was an easter egg gone wrong because that's the name of a famous star trek tng episode, tried on multiple instances

Reproducible by searching for "darmok" in any instance that I've tried.

Title: `Missing hash key: "browseEndpoint" (KeyError)`
Date: `2023-10-28T22:01:04Z`
Route: `/search?q=darmok`
Version: `2023.10.26-8087e64 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "browseEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:144:5 in 'get_browse_id'
  from /usr/share/crystal/src/indexable.cr:949:8 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by poretsky** [comment] 2023-10-29 06:42
Curiously, but I tried to search for "darmok" on yewtu.be and on my
local instance and ended up just with normal result, no error. And, if
read this error message carefully, it would better relate to #4133.

**Comment by xprnio** [comment] 2024-01-15 23:49
I just got this error when trying to search for `¥ØU$UK€ ¥UK1MAT$U`

```
Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2024-01-15T23:48:19Z`
Route: `/search?q=%C2%A5%C3%98U%24UK%E2%82%AC+%C2%A5UK1MAT%24U`
Version: `2023.12.18-97c4165f @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1077:11 in '[]'
  from /usr/share/crystal/src/json/any.cr:103:7 in '[]'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'dig'
  from src/invidious/yt_backend/extractors.cr:827:12 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:332:41 in 'parse'
  from src/invidious/yt_backend/extractors.cr:319:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'regular'
  from src/invidious/search/query.cr:116:9 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/routing.cr:184:20 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:517:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:470:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>
```

**Comment by LuukMo** [comment] 2024-01-20 19:57
Getting the same error searching for `Filatelie Felbm`. 
Tested on Firefox and Edge on multiple instances. 

Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2024-01-20T19:48:14Z`
Route: `/search?q=Filatelie+Felbm`
Version: `2024.01.10-1c0b420 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:332:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by maxysoft** [comment] 2024-02-08 23:23
Same error searching "Veerus - Infinity". Tried on mine and some public instances. Latest firefox and brave.

https://invidious.fdn.fr/search?q=Veerus+-+Infinity
https://invidious.nerdvpn.de/search?q=Veerus+-+Infinity
https://iv.datura.network/search?q=Veerus+-+Infinity

Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2024-02-08T23:21:56Z`
Route: `/search?q=Veerus+-+Infinity`
Version: `2024.01.29-c005ada @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:332:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Closed** 2024-02-12 21:40 UTC
Labels: bug, research-needed, module:search
