### ISSUE TITLE
[Feature] Theater Mode

### ISSUE THREAD

**Issue by seniorm0ment** [iv-org/invidious#2760] opened 2022-01-04 12:00 UTC
Requesting the ability for theater mode similar to YouTibe's that simply scales the video window to fill the page, but not fullscreen.
This makes it easier to see without the need to be in fullscreen.

**Comment by unixfox** [comment] 2022-01-04 12:24
Duplicate of https://github.com/iv-org/invidious/issues/2395

**Closed by unixfox** 2022-01-04 12:24 UTC
Labels: feature-request
