### ISSUE TITLE
Processing videos in Subscriptions page

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#719] opened 2019-08-21 23:10 UTC
I have noticed that Processing videos (ones with a ... image) are showing in the Subscriptions page (an example is a Playing with Pasta video made by ThreadBanger).

**Comment by Zero3K** [comment] 2021-02-02 00:58
*bump*

**Comment by SamantazFox** [comment] 2022-02-03 16:48
@Zero3K  could you provide a screenshot of the issue if that still happens?

**Comment by unixfox** [comment] 2022-04-17 20:56
Closing due to a lack of replies and procedure to reproduce the issue.

**Closed by unixfox** 2022-04-17 20:56 UTC
