### ISSUE TITLE
[Feature request] Add 1.1x play speed

### ISSUE THREAD

**Issue by bipox** [iv-org/invidious#1574] opened 2020-12-13 17:15 UTC
Hi,

I have been using Enhancer for YouTube browser addon for a long time, which allows to set speed at 1.1x. 

It's perfect, you don't feel the speed increase, it doesn't look weird or makes it too fast to understand, yet it feels slow if I watch at 1x.

1.25x is too fast to still feel "normal". I understand it's subjective and I can't speak for others, but I suspect it's the same for most people. 

Thank you for your work, Invidious is really great!

**Comment by Perflyst** [comment] 2020-12-13 18:48
Sounds like a duplicate of #533, what do you think?

**Comment by bipox** [comment] 2020-12-13 21:13
I think I missed it.

My bad, closing this

**Closed** 2020-12-13 21:14 UTC
