### ISSUE TITLE
[Bug] invidious plays the first audio track even if it is not the main audio track

### ISSUE THREAD

**Issue by rezad1393** [iv-org/invidious#3295] opened 2022-09-01 07:43 UTC
https://www.youtube.com/watch?v=2ZWui_J1HkA
it is a video that has 3 audio tracks on youtube. and on youtube the main one (English) is played by default ( I dont login in youtube or google and this this is still the default behavior) 
now go to 
set video format to dash.
https://yewtu.be/watch?v=2ZWui_J1HkA
the same video on invidious.
it played spanish audio tracks  which in the first audio track in the audio list on youtube (English is the third one)

**Comment by unixfox** [comment] 2022-09-01 08:29
Duplicate of https://github.com/iv-org/invidious/issues/2007

**Closed by unixfox** 2022-09-01 08:29 UTC
Labels: bug

**Comment by rezad1393** [comment] 2022-09-01 08:31
I saw that issue too but that video plays in english in invidious. this one just go spanish.
maybe this one doesnt have a default one.

**Comment by unixfox** [comment] 2022-09-01 08:47
Yes but at the time of the creation of the issue the audio was in Spanish too and it's the same bug.
