### ISSUE TITLE
[Bug] materialized view "subscriptions_cdb6d65985d22f1693e657164eb28246678015297754e543c" has not been populated (PQ::PQError)

### ISSUE THREAD

**Issue by lingruby-pl** [iv-org/invidious#3126] opened 2022-05-27 23:03 UTC
Title: `materialized view "subscriptions_cdb6d65985d22f1693e657164eb28246678015297754e543c" has not been populated (PQ::PQError)`
Date: `2022-05-27T23:01:52Z`
Route: `/feed/subscriptions`
Version: `2022.05.24-c2d91c95 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
materialized view "subscriptions_cdb6d65985d22f1693e657164eb28246678015297754e543c" has not been populated (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'query_all:as'
  from /usr/share/crystal/src/reference.cr:28:3 in 'get_subscription_feed'
  from src/invidious/routes/feeds.cr:97:29 in 'subscriptions'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-05-28 07:32
Duplicate of https://github.com/iv-org/invidious/issues/3123

**Closed by unixfox** 2022-05-28 07:33 UTC
Labels: bug
