### ISSUE TITLE
[Bug] Content not available in this app. upgrade to latest version of youtube.

### ISSUE THREAD

**Issue by accessiblepixel** [iv-org/invidious#3230] opened 2022-07-30 13:41 UTC
Continuation of #3217 as it was closed so that I couldn't reopen.

Getting same message again, and this time have tried in multiple browsers with no extensions, after cleaning cache, disabling extensions, enabling extensions on my own invidious install in docker on linux from latest tag.

Obviously something isn't working right, even in a fresh browser with no extensions.

I'm trying to report again. Tell me what you need to debug it, as didn't feel it was looked at properly last time.

**Comment by unixfox** [comment] 2022-07-30 13:46
Please post the video(s) ID that you tested.

Also for these video ID please check if you can reproduce the same issue on others public instances: https://instances.invidious.io/

**Comment by accessiblepixel** [comment] 2022-07-30 13:47
Also something from this list makes it work for a video again.: refreshing, viewing different videos, turning proxy on/off, restarting docker...

It's an intermittent thing, and doesn't seem to be dependent on a specific video, but once it rears it's head, it won't show on the instance in any browser.

The two videos in the last thread did, and the videos will work fine on a public instance, because it's something intermittent going wrong with the core.

**Comment by unixfox** [comment] 2022-07-30 13:50
In which country is your invidious instance located?

So do you confirm that you have no issues whatsoever on most the public instances and that you are currently only able to reproduce this issue on your local invidious installation?

**Comment by accessiblepixel** [comment] 2022-07-30 13:55
I've tested the couple of videos I've found that don't work on a public installation and the videos that haven't worked for me have worked on public instances. After fiddling for a while with it, something in the above list, it will start working again, but so far I haven't figured out what fixed it. Updating fixed it last time because it wipes anything that might be cached and restarts it so...

I don't use public instances enough to see if the problem rears it's head or not, I've only used public instances to check to the videos that haven't worked.... although this time when one video stopped, they all stopped and started showing that 5 minute video again.

It's hosted in the UK on my internet connection. In docker on a VM running Debian Linux 11 (bullseye), on top of the Proxmox hypervisor.

**Comment by unixfox** [comment] 2022-07-31 07:16
@SamantazFox any ideas about this issue?

On matrix people were talking about the fact that we are using an old version of the ANDROID client: https://github.com/iv-org/invidious/blob/master/src/invidious/yt_backend/youtube_api.cr#L58

**Comment by SamantazFox** [comment] 2022-07-31 14:00
yeah, that could be related to the client version. I need to bump them ^^

**Comment by coletdjnz** [comment] 2022-08-03 22:14
https://github.com/TeamNewPipe/NewPipe/issues/8713#issuecomment-1204537903

**Comment by accessiblepixel** [comment] 2022-08-04 14:00
Okay, I've done a little digging, but it's so intermittent it's hard to get good debug data.

I'm not exactly sure what I'm looking for, but in web developer network console, when the video shows the error message, when it's trying to start playback it gets a HTTP 200 straight away then that video loads.

On videos where it works normally I get a 302 Moved, then it goes to a HTTP 200.

What do I need to be on the lookout for in the network tab, since there's a lot of stuff happening here and I'm not familiar with much of it (I just use invidious and know my away around some web development).

**Comment by unixfox** [comment] 2022-08-04 14:06
> What do I need to be on the lookout for in the network tab, since there's a lot of stuff happening here and I'm not familiar with much of it (I just use invidious and know my away around some web development).

It's not directly related to invidious, it's an issue between invidious and youtube servers. You won't see anything in the network tab as all the requests are done inside invidious.

On your side you can't do anything if you don't have some background in reverse engineering, you will have to wait that the community find a solution for this issue.

**Comment by unixfox** [comment] 2022-08-06 20:02
@accessiblepixel Can you me help with these questions:
- Do you sometimes use the official YouTube app on your internet? On your phone with YouTube for Android, or on www.youtube.com with your computer?
- Do you have IPv6? You can find out if you have it here: https://ipv6test.google.com or https://test-ipv6.com
- Can you give the IP address that you get for the domain `www.youtube.com`. On Windows and Linux, you can find it through the command line/terminal by entering `nslookup www.youtube.com`
- Do you have this error after viewing a few videos, or it appears straight away on the first video that you watch for the day?

These questions will help us replicate this issue on our side because it's very tricky to replace the error, I haven't been able to do it even after 300 tries of loading the same video.

**Comment by accessiblepixel** [comment] 2022-08-06 20:31
@unixfox 

Yes, my partner uses the official YouTube website on our internet (with Firefox on his computer) and I think he sometimes browses on his phone, but the error video comes up regardless of whether he's using it (I know he's not using it when he is asleep and I am not 😃)

We don't have IPv6 enabled.

The error comes a couple of times a day, usually after watching a few videos. I've taken to just not watching the video that doesn't work and move on to another one or if I really want to watch it, open it on the YouTube website.

If I can help further, please don't hesitate to ask. Next time it happens I will post the lookup for the youtube domain. :)

Kind regards,
Jessica

**Comment by unixfox** [comment] 2022-08-07 19:46
@accessiblepixel Thanks to the collaboration in the YouTube reverse engineering community, we finally found the missing parameter (https://github.com/TeamNewPipe/NewPipe/issues/8713#issuecomment-1207443550) that resulted in the error that you got.

Please update Invidious and the error will be fixed.

**Comment by unixfox** [comment] 2022-08-08 09:04
We should probably add an exception if we find that the videoID returned is not the correct one, like yt-dlp did: https://github.com/yt-dlp/yt-dlp/pull/4593/files

This may allow debugging future issues quicker.

**Comment by accessiblepixel** [comment] 2022-08-10 19:54
I've updated and I haven't yet seen the same error again.

It seems like @unixfox 's suggestion of throwing an exception if the returned video isn't the expected one would be very useful and I see they've opened #3257 for that. That would be very useful, it would have helped me not feel like I was loosing my mind :p 

Thanks all.

**Comment by accessiblepixel** [comment] 2022-08-23 12:11
I've not seen this error from https://github.com/iv-org/invidious/issues/3230 since, except today where I tried to watch a video and it came up, so it looks like in certain circumstances it's still possible? Was the debug thing not added, where if the video that comes back isn't the video id requested to throw some kind of exception?

**Comment by unixfox** [comment] 2022-08-23 12:32
A debug code is going to be added in https://github.com/iv-org/invidious/pull/3278. I'm waiting for the confirmation from @SamantazFox.

**Comment by unixfox** [comment] 2022-08-23 20:07
@accessiblepixel Please update invidious and report any bug related to the error from this github issue.

**Comment by accessiblepixel** [comment] 2022-08-23 23:37
Alright, I've updated to `2022.08.23-16b23ef` @ master`, and will report back if/when I see the error again.

It is a lot less common with the change from #3255 though, for sure, but I've seen it a couple of times now. :)

**Comment by accessiblepixel** [comment] 2022-08-24 06:18
Okay, yes, I got a video that doesn't appear and shows the same message and video like before today.

Let me know what info and debugging info I need to provide.

**Comment by unixfox** [comment] 2022-08-24 06:59
You didn't get the error message like this?:
![image](https://user-images.githubusercontent.com/4016501/186351673-37676710-2182-4a15-b434-6d4a00294e26.png)

Please send us:
- The video ID of the YouTube video that have the issue
- A screenshot of the video that have the issue

**Comment by accessiblepixel** [comment] 2022-08-24 10:25
No, I didn't get a debug error like that, unfortunately.

I missed screenshotting when it happened last time, but I will grab it when it happens again. Is the debug information available in ` 2022.08.23-16b23ef @ master`? That's the version that I got when I updated the docker, was it added at that time?

Thanks,
Jessica

**Comment by unixfox** [comment] 2022-08-24 11:14
Yes `2022.08.23-16b23ef @ master` is the latest version available on Invidious, and it has the debug information added to it.

Even though the issue may not be related to a particular video, it's still useful information that we can use in order to diagnose the issue. The thing is that we don't know if the potential issue affect some videos or all the videos on YouTube.

By having the video ID/URL, we can be sure that either it affects all the videos or some videos.

If you happen to reproduce the issue again, sending us a screenshot would really help us.

On my side, when I have time I'll try to reproduce the issue.

**Comment by accessiblepixel** [comment] 2022-08-24 11:46
No problem. I'll get you a screenshot when it happens again and the video URL :)

**Comment by accessiblepixel** [comment] 2022-08-24 17:17
Here's the screenshot as promised [here.](https://i.lowrex.com/i/BJZcG.png) and the video where it happened is `watch?v=bWRFDVjb-xo`

**Comment by accessiblepixel** [comment] 2022-08-24 18:38
Another broken video [here.](https://i.lowrex.com/i/BJzrY.png) video URL is `watch?v=mepmJJ62ZFU`

**Comment by unixfox** [comment] 2022-08-24 18:42
Thank you for the screenshot and the video IDs. I'll investigate.
(by the way, if the last message is from you then please edit it instead of posting a new one, it helps in keeping this issue "clean".)

**Comment by unixfox** [comment] 2022-08-25 07:34
Could you set the `log_level` to `All` in the `config.yml` file and then restart Invidious?

When you encounter the issue again, get the logs from 5 minutes before the issue happened to the very last logs. Then upload them on https://paste.ee. It's ok if there are too many lines in the logs.

If you installed Invidious using docker-compose, you can get the logs using `docker-compose logs --tail=10000`. `10000` means it will show you the last `10000` lines, increase or decrease the number in order to find the corresponding lines, check the date it's normally written at each line. 

And also tell us the videoID where the issue happened.

If you don't want to publicly share the logs (which I completely understand), then send us the link by email to `contact [at] invidious [dot] io`. (Obviously, replace the [at] and the [dot])

**Comment by accessiblepixel** [comment] 2022-08-25 14:30
Excellent! I'm glad you were able to find where the problem is! That's good searching. I'll wait to update until the new useragent is merged and grab the new docker files when they're next built. You're a star. 🌟 

I'm really glad you were able to find it, I sort-of started to think I was going a little crazy 😛. 

I'm really glad I was a bit more persistent with reporting this, because I bet it probably got on a lot of people's nerves. I really appreciate that you folks have been able to find the problem, and all those involved in tracking it down from my reports.

I know initially there might have been a bit of a language barrier, I asked my friend about things and he said that sometimes people can say things that sound a bit "abrupt" but it's just a kind of "local custom", which I wasn't aware of, but was good to know - at first I thought I got told off for trying to help, so my apologies if that was the case & again thank you (and everyone else who's been involved, from invidious and the other people working on reverse engineering the YouTube client) for figuring out this issue - I hope I at least helped in a small way.

I'll update when there's a new build available and report back (edit if there's no further replies - I'm quite new at using github so I didn't realise that was the custom!) 😃 

Kind regards,
Jessica

**Comment by unixfox** [comment] 2022-08-25 18:54
Sorry for being sometimes a bit *"aggressive"*. It's just that as a maintainer of not only Invidious but [SearX](https://github.com/searx/searx) and [SearXNG](https://github.com/searxng/searxng) I see many and many issues every week, and I sometimes I get sick of people that don't try to replicate the issue on a bare minimum setup like a browser with no extension, or just forget to update Invidious or forget to fill in the issue template that we created.

The thing is that to me, I don't treat GitHub issues as a place to chat, so I don't like when people are not concise about the problem or send many consecutive messages in a short period instead of editing the previous message. But I always forget that people don't know about that, only the people accustomed to GitHub know that.

I'm not against chatting, but I prefer that people do it on our [Matrix channel](https://matrix.to/#/#invidious:matrix.org) or [IRC channel](https://web.libera.chat/?channel=#invidious).

Now for the on-topic:

You are not crazy, I feel like YouTube is cracking down on our projects (Newpipe, invidious, youtube-dl and more). They are trying to find what kind of information we are not correctly sending compared to a real YouTube app so that they can block us.

I'll try to find some free time this weekend for replicating more precisely the information that we send to YouTube servers compared to the official YouTube apps.

Meanwhile, with the latest version of Invidious, which you should update to, if you get the error message just refreshing the page should give you the correct video content instead of serving you that "Content not available in this app. upgrade to latest version of youtube." message for more than 10 minutes.

**Comment by accessiblepixel** [comment] 2022-08-25 20:24
Thank you. I totally get it, I'm just a fairly new user of github (you could probably say a n00b, even though I've been using the internet for like 20+ years) and I like to try and make detailed reports, but sometimes with some things I don't know exactly what information is required or how to get it.

I think it's only fair (in my opinion) that for free software I contribute since I can't afford any other contribution to make the experience better for everyone else.

On topic, I'll update invidious and let you know anything I see in the future. Thank you ❤️

**Comment by 89z** [comment] 2022-09-15 11:10
https://github.com/zerodytrash/YouTube-Internal-Clients/issues/3

**Closed** 2022-09-15 21:27 UTC
Labels: bug

**Comment by unixfox** [comment] 2022-09-16 05:12
Hello @accessiblepixel can you try if the issue is now fully fixed.

We pushed some changes. You will need to update invidious.
