### ISSUE TITLE
[Bug] long videos stop playing after exactly 6 hours.

### ISSUE THREAD

**Issue by arrowgent** [iv-org/invidious#2731] opened 2021-12-21 14:11 UTC
yes "6hours"

**Describe the bug**

watching 6+ hour long videos from start (FROM THE START) after approximately 6 hours (5:59:55-6:05:00) will stop playing and display a buffering loading loop

this is hard to reproduce because you literally have to not interact with the video for 6+ hours to test it
any interaction on the video player will effect the outcome

i have seen this atleast 4-5 times
at first i thought possibly, oh small internet buffer, or youtube, or invidious hiccup, or cache issue
but no, it happens consistently so this is a repeatable bug

instance:
vi.puffyan.us

player:
DASH formats

default quality:
720p
override - do not play 60fps

**Steps to Reproduce**

1. Go to '...' 6+ hour video
2. Click on '....' start video and do not interact for atleast 6 hours (go to sleep)
3. Scroll down to '....' at ~~~6hours~~~ the videos will stop playing
4. See error video should be playing....

**Logs**

**Screenshots**

[https://i.imgur.com/vXD2lbZ.png](https://i.imgur.com/vXD2lbZ.png)

**Additional context**

i am using FreeTube, a player which goes through invidious.
i feel that this is an invidious issue more than a FreeTube issue,
if you feel otherwise i can re-report to them ... but i think they will kick it back again to invidious

**Comment by unixfox** [comment] 2021-12-21 14:14
You aren't using the Invidious frontend right? You are just using the API of invidious on Freetube?

Can you reproduce this issue without using invidious on Freetube?

**Comment by arrowgent** [comment] 2021-12-21 15:43
correct
i will test that later to confirm

**Comment by unixfox** [comment] 2021-12-21 17:15
It's probably not an issue related to invidious.

**Comment by unixfox** [comment] 2021-12-28 09:14
Closing as it's not an invidious bug.

**Closed** 2021-12-28 09:15 UTC
Labels: bug

**Comment by arrowgent** [comment] 2022-01-27 13:02
finally tested on two invidious instances

no issues with 8hours +

**Comment by SamantazFox** [comment] 2022-01-29 14:50
Okay, that's probably because we bumped the videoJS version!

**Comment by unixfox** [comment] 2022-01-29 15:35
> Okay, that's probably because we bumped the videoJS version!

Hum no, we merged that yesterday not 2 days ago.
