### ISSUE TITLE
[Bug] Playlist Parameter Modification

### ISSUE THREAD

**Issue by Daxy7** [iv-org/invidious#4384] opened 2024-01-09 09:29 UTC
**Describe the bug**
Going to native YT appends `&plid` instead of `&list`, thus deprecating the playlist.

**Steps to Reproduce**

https://github.com/iv-org/invidious/assets/91396482/5774835c-1756-472a-b1c1-f19e5d551b4e

**Logs**
https://yewtu.be/watch?v=ZxxyIqR5Aig&list=PLNlQ1VSZ3EaylQeeQczaSOhgiPNY1NJln&index=1

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/91396482/a7d43a03-d355-4cea-8722-f90ec3892f00)

**Additional context**
 - Browser: Firefox 115.6.0esr
 - OS: Windows 7

**Comment by unixfox** [comment] 2024-01-09 12:27
Sounds like a very easy change. Changing `&plid` to `&list` in the code.

Would you be able to create a PR for that?

**Comment by syeopite** [comment] 2024-01-09 12:38
Should be fixed by #4342

**Comment by unixfox** [comment] 2024-01-09 13:45
Duplicate of https://github.com/iv-org/invidious/issues/3929

**Closed by unixfox** 2024-01-09 13:45 UTC
Labels: bug
