### ISSUE TITLE
[Enhancement] Split authentication account for personal settings

### ISSUE THREAD

**Issue by maboroshin** [iv-org/invidious#4882] opened 2024-08-26 03:02 UTC
**Is your enhancement request related to a problem? Please describe.**

Each instance is prone to errors when connecting to YouTube. This is a recent trend. The instance must be switched. Do I have to recreate my account each time?

**Describe the solution you'd like**
Allows you to log in to the instance for personal settings. There is no need to create an account for a new instance. Settings from previous instances are available.

* Instance for data sharing. For information not related to connection errors, such as subscriptions and playlists.
* Instance for accessing YouTube.

**Describe alternatives you've considered**
None

**Additional context**
Related: https://github.com/iv-org/invidious/issues/4426

**Comment by unixfox** [comment] 2024-08-26 04:30
Duplicate of https://github.com/iv-org/invidious/issues/879

**Closed by unixfox** 2024-08-26 04:30 UTC
Labels: enhancement
