### ISSUE TITLE
Inacurrante title in tab and in window title

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1213] opened 2020-05-31 16:59 UTC
Hello,

Sometimes, the title showed in the tab and the top bar of the window is not the actual title of the video, like in the example here below.

![Screenshot_20200531_185333](https://user-images.githubusercontent.com/22192600/83358031-fbcda380-a35f-11ea-9750-f44c60f602ed.png)

**Comment by TheFrenchGhosty** [comment] 2020-08-20 21:13
Dupe of https://github.com/iv-org/invidious/issues/1285

**Closed** 2020-08-20 21:13 UTC
Labels: bug
