### ISSUE TITLE
media playback failed with error relating to my browser

### ISSUE THREAD

**Issue by gloschtla** [iv-org/invidious#931] opened 2019-11-24 10:19 UTC
> The media playback was aborted due to a corruption problem or because the media used features your browser did not support. 

This error must be from my mozilla-based browser Waterfox, because media playback on invidioUS works on my other chrome-based browser. How to make it work on my mozilla-based browser? I [searched online for anwers](https://metager.de/meta/meta.ger3?eingabe=The+media+playback+was+aborted+due+to+a+corruption+problem+or+because+the+media+used+features+your+browser+did+not+support.&submit-query=&focus=web) and found [no clear answers](https://support.mozilla.org/en-US/questions/1191741#answer-1042205). I tested it once again on Firefox 68.0.1 and found out that the same video worked, but other videos did still not work on newest Firefox with another error: 

> The media could not be loaded, either because the server or network failed or because the format is not supported.

This second error was already considered: [here on Github](https://github.com/omarroth/invidious/issues/602)

**Comment by gloschtla** [comment] 2019-11-24 13:06
The first error doesn't occur anymore in Waterfox, 
but the second still occurs in latest version of Firefox.

**Comment by stemy2** [comment] 2019-11-30 14:59
Same problem, it happens randomly during a video playing.

**Comment by tleydxdy** [comment] 2019-11-30 16:12
link to the video in question?

**Comment by stemy2** [comment] 2019-11-30 16:15
It happens with any video.

**Comment by tleydxdy** [comment] 2019-11-30 23:12
I suspect it's related to your internet connection. I have it when my internet is bad. create a brand new profile and see if it happens too

**Comment by lewisbelcher** [comment] 2020-02-16 21:06
Also getting this error. Happens on any video after some time. I don't think I've made it all the way through any video without getting this error at some point. I usually refresh and continue from where the error occurred (and repeat this however many times are necessary).

Full error from console: `VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support.`

**Comment by xplosionmind** [comment] 2020-04-09 14:04
I have this problem, too! Is there a way to fix it quickly?
Currently running Firefox 75.0 on MacOS.
Here's what I get:
![Screenshot 2020-04-09 at 4 02 12 PM](https://user-images.githubusercontent.com/42862428/78903681-cb623b00-7a7b-11ea-999e-cd035cbef509.jpg)

**Comment by WandeingLagomorph793** [comment] 2020-05-15 03:31
Had this happen to me too on an Arch Linux system, with the latest version of Firefox. Tried both public instances (snopyta and .us) and neither helped.

https://invidious.snopyta.org/watch/?v=DjRZLyY2cZo&list=PLC85CE5248C193CB2

**Comment by gloschtla** [comment] 2020-07-08 10:30
This old problem still occurs. 
#1268

**Comment by thatHguy** [comment] 2020-12-13 20:18
Can confirm this is happening on my local installation on a Debian machine, just installed freshly yesterday. Almost always on a video and at no specific point.

![image](https://user-images.githubusercontent.com/20350884/102022664-2f15d400-3d80-11eb-84c0-c96356c7709b.png)

**Comment by stemy2** [comment] 2020-12-13 20:23
I can also say it happens often on music videos, especially the official ones and the ones included on a "[artist] - Topic" channel.

According the developper tools, this is a HTTP 404 error.

**Comment by stemy2** [comment] 2021-12-18 10:18
The problem is still here.

And if i reload the page, it stops at the exact same timestamp for the exact same reason.

**Comment by SamantazFox** [comment] 2021-12-20 14:55
> The problem is still here.
> 
> And if i reload the page, it stops at the exact same timestamp for the exact same reason.

From my own experience, it looks like Firefox is keeping corrupted video data.
Have you tried using DASH quality?

**Comment by stemy2** [comment] 2022-01-04 19:24
It happens in chrome too.

**Comment by Zero3K** [comment] 2022-01-17 16:09
I am also experiencing it on https://invidious.namazso.eu/watch?v=z0DRRMI7-Sw (under Chrome) with the default video quality being selected.

**Comment by unixfox** [comment] 2022-04-17 21:01
Closing in favor of https://github.com/iv-org/invidious/issues/602 and https://github.com/iv-org/invidious/issues/2850

This issue is likely going to be somewhat fixed in https://github.com/iv-org/invidious/pull/3011

**Closed by unixfox** 2022-04-17 21:01 UTC
