### ISSUE TITLE
[Feature request] Add support for whitelist/blacklist channels/videos

### ISSUE THREAD

**Issue by thebiblelover7** [iv-org/invidious#3334] opened 2022-09-30 20:36 UTC
**Is your feature request related to a problem? Please describe.**
It would be great to only allow certain channels for a distraction-free experience and also could be useful for schools that want to block YouTube, but would still like some videos/channels available.

**Describe the solution you'd like**
Videos not in the whitelist would be blocked and videos in it, would be allowed. Videos from blocked channels would not be shown in search results.

**Describe alternatives you've considered**
Fortinet offers YouTube channel whitelisting, but it will show blocked videos in search results. Plus, it does not offer the control given by Invidious.

**Comment by unixfox** [comment] 2022-09-30 21:12
Duplicate of https://github.com/iv-org/invidious/issues/344

**Closed by unixfox** 2022-09-30 21:12 UTC
Labels: feature-request

**Comment by thebiblelover7** [comment] 2022-09-30 21:29
@unixfox Great, somehow I couldn't find that issue... Could you unlock the conversation? It is currently locked to collaborators only.
