### ISSUE TITLE
[Bug] Playlist pagination has overlaps

### ISSUE THREAD

**Issue by foghawk** [iv-org/invidious#2782] opened 2022-01-07 17:27 UTC
**Describe the bug**

Playlist pages show 200 videos per page, but changing the "page" parameter adjusts the offset into the playlist by only 100 videos per page. Most videos in long playlists therefore appear twice, making the pagination difficult to use.

In addition, it appears that

- each page is made of two separate blocks of 100 available videos,
- each block of _available_ videos may reflect more than 100 videos _in the playlist_—apparently since if some videos in the block are unavailable, more will be borrowed from just after the end of the block until a full hundred working videos can be displayed—and
- block offsets do not take this borrowing into account.

This can result in videos being repeated within individual pages (and seems like it would remain an issue, albeit between rather than within pages, even if the page length discrepancy were fixed).

**Steps to Reproduce**

1. Visit a playlist with >100 videos, such as [this one](https://yewtu.be/playlist?list=PL0zzw4k7yuKJT-NYMWNYUSQj8tsbSqlKX). Observe which videos are listed just before, on, and after position 100.
2. Click "Next Page". Observe which videos are listed on and after position 1.

Expected behavior: pages are disjoint segments of the playlist, and each video is displayed once.

Actual behavior: the first block of videos on the second page is the same as the second block of videos on the first page (and this holds for each successive pair of pages), and some videos may be displayed twice on the same page.

[Here](https://yewtu.be/playlist?list=PLJ_TJFLc25JR3VZ7Xe-cmt4k3bMKBZ5Tm) is another example of an affected playlist. One video, number 18, has been copyright-struck and taken down; one video ("Ninja Movies") is displayed twice on the first page.

**Additional context**

Affects  2021.12.17-2ac19eb, 2021.12.28-a779cdd4, 2021.12.29-4e866dce, 2021.12.31-4a7efcbe, 2022.01.03-ddc26ed, 2022.01.04-8231216, 2022.01.06-5a72824, 2022.01.07-9b134698 (all the builds I have been able to test on).

Note that versions before 444b1c99d0a0c69b6dc60559ef6b1647984623ab (2022.01.04-8231216 and earlier) do not display unavailable videos in playlists, while versions after (2022.01.06-5a72824 and later) do. However, the latter versions borrow anyway, so they still have the repetition issue; when affected by it they will display more than 100 videos per block/200 per page.

**Comment by SamantazFox** [comment] 2022-01-07 17:41
Thanks for so many details :)
Probably a regression of https://github.com/iv-org/invidious/pull/2257

**Comment by matthewmcgarvey** [comment] 2022-02-10 05:46
I believe this is a duplicate of https://github.com/iv-org/invidious/issues/2694

**Closed** 2022-02-10 14:09 UTC
Labels: bug
