### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gabrielash** [iv-org/invidious#2341] opened 2021-08-22 09:42 UTC
trying to import subscriptions from youtube. 
got csv file from takeouts
converted to json. 
Coversion looks fine:  I put a modified snippet for reference

[
{"Channel Id": "XXXX","Channel Url": "http://www.youtube.com/channel/XXXX","Channel Title": "YYYYY"},
...
]

imported to invidious and got the following error : 

Title: `Missing hash key: "snippet" (KeyError)`
Date: `2021-08-22T09:32:07Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.08.16-8bd2669 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "snippet" (KeyError)
  from /usr/share/crystal/src/hash.cr:1032:11 in '[]'
  from /usr/share/crystal/src/json/any.cr:103:7 in '[]'
  from src/invidious.cr:793:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:68:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2021-08-22 10:06
Duplicate of https://github.com/iv-org/invidious/issues/2319

**Closed by unixfox** 2021-08-22 10:06 UTC
Labels: bug
