### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hrg71** [iv-org/invidious#1986] opened 2021-04-07 03:44 UTC
Title: `Nil assertion failed (NilAssertionError)`
Date: `2021-04-07T03:42:47Z`
Route: `/watch?v=Pnvf9wSMepg`
Version: `2021.04.02-c4c2e01 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2021-04-08 04:58
Maybe a duplicate of #1762?

**Comment by markozajc** [comment] 2021-04-10 16:26
Works on b7eba3b, I assume this is also the same as #1996.

**Closed** 2021-04-19 20:13 UTC
