### ISSUE TITLE
[Bug] Tried to import from Youtube

### ISSUE THREAD

**Issue by Raul3324** [iv-org/invidious#2448] opened 2021-10-03 10:09 UTC
Title: `Unexpected char 'I' at line 1, column 1 (JSON::ParseException)`
Date: `2021-10-03T10:08:33Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.10.02-f8d64dd @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'I' at line 1, column 1 (JSON::ParseException)
  from /usr/lib/crystal/core/json/lexer.cr:376:7 in 'raise'
  from /usr/lib/crystal/core/json/lexer.cr:372:5 in 'unexpected_char'
  from /usr/lib/crystal/core/json/lexer.cr:371:11 in 'unexpected_char'
  from /usr/lib/crystal/core/slice.cr:225:5 in 'next_token'
  from /usr/lib/crystal/core/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>

**Comment by unixfox** [comment] 2021-10-03 10:10
Duplicate of https://github.com/iv-org/invidious/issues/2319

**Closed by unixfox** 2021-10-03 10:10 UTC
Labels: bug
