### ISSUE TITLE
Graphical issue with buffering progress

### ISSUE THREAD

**Issue by Zero3K** [iv-org/invidious#147] opened 2018-08-31 20:16 UTC
The grey used to show how much of the video has been buffered isn't filling up the entire bar (there's some black left over at the very end). Is it intentional or a bug?

**Comment by Zero3K** [comment] 2018-08-31 20:44
Here's a video where the issue is occurring:

https://www.invidio.us/watch?v=awnGMghybS8

**Comment by Discookie** [comment] 2018-08-31 21:32
![image](https://user-images.githubusercontent.com/16914176/44936676-f8b21780-ad75-11e8-8d2b-8634ac73203d.png)
Works on Chromium latest with JS enabled on Win8.1 64bit. What's your browser/OS?

**Comment by Zero3K** [comment] 2018-08-31 22:38
Are the last 4-6 seconds filled in with a gray color? And to answer your question, I am using Pale Moon 28 on Windows 10.

**Comment by Discookie** [comment] 2018-08-31 22:58
The full bar is filled with the grey color (no black anywhere that's marking unloaded sections), and it played properly through that section as well.
I've only seen a similar thing happen on YouTube a few times - not on invid yet.

**Comment by Zero3K** [comment] 2019-02-03 20:38
Its still happening to me in the latest unstable build of Pale Moon.

**Comment by Zero3K** [comment] 2019-09-20 17:23
Its still happening for me in the latest version of Pale Moon.

**Comment by Zero3K** [comment] 2021-01-02 05:23
*bump*

**Comment by Zero3K** [comment] 2022-01-02 14:50
Bump

**Comment by unixfox** [comment] 2022-01-02 16:51
> Bump

Can you still reproduce the issue?

**Comment by unixfox** [comment] 2022-01-16 18:07
Closing due to a lack of replies.

**Closed by unixfox** 2022-01-16 18:07 UTC
Labels: bug
