### ISSUE TITLE
[Bug] Expected Hash for #[]?(key : String), not String (Exception)

### ISSUE THREAD

**Issue by BienkowskiTomasz** [iv-org/invidious#2613] opened 2021-11-14 13:27 UTC
Title: `Expected Hash for #[]?(key : String), not String (Exception)`
Date: `2021-11-14T13:24:39Z`
Route: `/watch?v=_1eHVLPP99Y`
Version: `2021.11.12-be1a390b @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Expected Hash for #[]?(key : String), not String (Exception)
  from /usr/share/crystal/src/json/any.cr:117:7 in '[]?'
  from src/invidious/videos.cr:575:47 in 'fmt_stream'
  from src/invidious/routes/watch.cr:127:18 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Additional context**

**Comment by unixfox** [comment] 2021-11-14 13:30
Which instance did you use?

**Comment by syeopite** [comment] 2021-11-14 14:07
Possible duplicate of #2549

**Comment by SamantazFox** [comment] 2021-11-15 13:33
> Possible duplicate of #2549

Confirmed. I'm closing this issue.

**Closed by SamantazFox** 2021-11-15 13:33 UTC
Labels: bug
