### ISSUE TITLE
[Bug] Missing JSON element "videoDetails" (BrokenTubeException)

### ISSUE THREAD

**Issue by ringo7777777** [iv-org/invidious#3456] opened 2022-12-01 05:49 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Title: `Missing JSON element "videoDetails" (BrokenTubeException)`
Date: `2022-12-01T05:48:27Z`
Route: `/embed/rPIUI0RCsN0`
Version: `2022.12.01-6b05780 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "videoDetails" (BrokenTubeException)
  from src/invidious/videos/parser.cr:177:9 in 'parse_video_info'
  from src/invidious/videos/parser.cr:90:12 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:354:13 in 'get_video:region'
  from src/invidious/routes/embed.cr:133:15 in 'show'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by ringo7777777** [comment] 2022-12-01 05:49
Title: `Missing JSON element "videoDetails" (BrokenTubeException)`
Date: `2022-12-01T05:48:27Z`
Route: `/embed/rPIUI0RCsN0`
Version: `2022.12.01-6b05780 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "videoDetails" (BrokenTubeException)
  from src/invidious/videos/parser.cr:177:9 in 'parse_video_info'
  from src/invidious/videos/parser.cr:90:12 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:354:13 in 'get_video:region'
  from src/invidious/routes/embed.cr:133:15 in 'show'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-12-02 19:19
Closing, as it is a duplicate of https://github.com/iv-org/invidious/issues/3402

**Closed by SamantazFox** 2022-12-02 19:19 UTC
Labels: bug, duplicate
