### ISSUE TITLE
[Bug] Index out of bounds (IndexError)

### ISSUE THREAD

**Issue by rodlord5000** [iv-org/invidious#3996] opened 2023-07-19 09:43 UTC
**Describe the bug**
Receiving an Index out of bounds (IndexError) when trying to import a YouTube subscription list CSV as per the instructions at https://docs.invidious.io/export-youtube-subscriptions/ 

**Steps to Reproduce**

Go to Subscriptions -> Manage Subscriptions -> Import/Export -> Import YouTube subscriptions, select the file you just downloaded and click on Import

**Logs**
Title: `Index out of bounds (IndexError)`
Date: `2023-07-19T09:37:21Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2023.07.16-69e2eac @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/json/parser.cr:117:5 in 'update_data_control'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2023-07-19 10:18
Probably a duplicate of https://github.com/iv-org/invidious/issues/3593

**Closed** 2023-07-27 16:46 UTC
Labels: bug
