### ISSUE TITLE
[Bug] videos are slow to load

### ISSUE THREAD

**Issue by Morasithil** [iv-org/invidious#3941] opened 2023-06-27 19:50 UTC
Summary: Videos are slow to load.

-----

**Describe the bug**
When attempting to watch any video on yewtu.be there's an X symbol at the center of the video, seemingly the stream failed to load.
However this is not the actual issue i want to inform you about, when setting the video quality fo FullHD 1080p Dash at https://yewtu.be/preferences then the videos will load as they should, however since a week or so the DASH quality is not working, the videos load at super low resolution looking extemely "pixelated" and this happens with any video even after saving the preferences to use DASH quality. The only current fix i found is to manually klick the settings icon of each indivdual video and once again set the quality to 1080p, then the video wil load for a few seconds and finaly play normaly in 1080p quality.
I'm guessing this is around 1-2 weeks max since this issue first appeared, and for the first issue i mentioned where videos don't even load if DASH quality isn't selected, this happens since a month +/-

**Steps to Reproduce**
Visit https://yewtu.be and try watch any video - it will fail to load
Fix: Visit https://yewtu.be/preferences and set the preffered video quality to DASH
Attempt to watch any video, it will load in extremely bad quality.
Fix: Manualy change the video quality via the settings icon.

**Logs**

**Screenshots**

**Additional context**

**Comment by unixfox** [comment] 2023-06-27 20:01
All the projects based on youtube are facing this issue.

DASH works but it's very slow. This is due to a new breakage from youtube.

We are trying to fix this issue.

**Comment by CptanPanic** [comment] 2023-09-30 11:57
> All the projects based on youtube are facing this issue.
> 
> DASH works but it's very slow. This is due to a new breakage from youtube.
> 
> It's not just yewtu.be
> 
> We are trying to fix this issue.

I wonder if there has been any updates on this? My instance is very slow, and is almost unusable.

**Comment by unixfox** [comment] 2023-10-09 16:01
@SamantazFox @syeopite did we update the specific params used when fetching the youtube player endpoint? something that was related to youtube shorts but it's a new parameter now.

**Comment by unixfox** [comment] 2024-02-19 23:21
Closing as I can't reproduce the issue anymore.

**Closed by unixfox** 2024-02-19 23:21 UTC
Labels: bug

**Comment by kevinarch** [comment] 2024-06-10 17:17
I'm still facing with DASH for above 1080p. long buffering, constant pause make it unusable for me right now.
I tried to enabled Proxy video on my private instance but not seem to work tho
