### ISSUE TITLE
[Bug] The video returned by YouTube isn't the requested one. (Android client)

### ISSUE THREAD

**Issue by marcus-marchinco** [iv-org/invidious#4556] opened 2024-04-02 19:55 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by syeopite** [comment] 2024-04-02 20:29
Duplicate of #4498

---

Please update your Invidious

**Closed** 2024-04-02 20:29 UTC
Labels: bug
