### ISSUE TITLE
[Bug] Could not get channel info when clicking on a YouTube Channel

### ISSUE THREAD

**Issue by VannaFluffie** [iv-org/invidious#4244] opened 2023-11-08 18:33 UTC
**Describe the bug**

When you search for a Channel (seems to be any Channel as far as I have tested), you'll get an Error with the info "Could not get channel info". I tried to load on various instances, which doesn't seem to work either. Going to YouTube or FreeTube works as intended.

**Steps to Reproduce**
1. Go to '[...](https://yewtu.be/channel/UCqwGaUvq_l0RKszeHhZ5leA)' or '[...](https://yewtu.be/channel/UClyGlKOhDUooPJFy4v_mqPg)' or search any Channel
2. If you searched for a Channel, Click on the Channel
3. See error

**Logs**

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/99033727/6116aad8-886b-4851-8dcb-41a5bf15d14b)
![image](https://github.com/iv-org/invidious/assets/99033727/def502f7-8dbb-4b80-afd6-55962205325f)

**Additional context**
 - Browser (if applicable): 
Main Browser: Firefox 119.0.1; Firefox Release; November 7, 2023
Backup: Microsoft Edge Version 119.0.2151.44 (Official build) (64-bit)

 - OS (if applicable):
Windows 11, Version 22H2 (OS Build 22621.2428)

**Comment by deckeys** [comment] 2023-11-08 20:00
Yes, seems like it is broken, no matter what instance. For now I am using piped.video.

**Comment by syeopite** [comment] 2023-11-08 20:00
Duplicate of #4238

**Closed** 2023-11-08 20:00 UTC
Labels: bug
