### ISSUE TITLE
How to unfreeze subscriptions?

### ISSUE THREAD

**Issue by cyberchief1984** [iv-org/invidious#674] opened 2019-08-06 13:22 UTC
How do I unfreeze my subscription feed? I;m not using the official instance. Somebody froze it.

**Comment by fliegentoeter** [comment] 2019-08-06 20:33
Happens to me on the official instance on a daily basis. Seems like subspriptions are only updated twice a day or even less...

**Comment by omarroth** [comment] 2019-08-09 03:45
> I;m not using the official instance

Mind providing which instance you are using?

Otherwise I expect it's an issue with higher load. There's a couple things I have in mind to try that should fix the issue, although it may be a couple days before I can take a look at it.

**Comment by cyberchief1984** [comment] 2019-08-09 08:29
I am using https://invidious.13ad.de.

**Comment by PureTryOut** [comment] 2019-08-10 16:39
I'm using a private self-hosted one, I'm the only user, and I haven't seen an update to my subscriptions since last week. If I go to an individual channel the newest videos do show up however.

**Comment by omarroth** [comment] 2019-08-11 17:45
What does your `config.yml` look like?

**Comment by PureTryOut** [comment] 2019-08-11 18:03
```
channel_threads: 1
feed_threads: 1
db:
  user: ****
  password: ****
  host: ****
  port: ****
  dbname: ****
full_refresh: false
https_only: false
domain:
```

**Comment by omarroth** [comment] 2019-08-12 13:14
You may check that you're up-to-date, otherwise make sure that postgres isn't logging any errors. If you're seeing something like #619, then you should be able to fix it with `check_tables: true` in your config.

**Comment by omarroth** [comment] 2019-08-12 13:15
> I am using https://invidious.13ad.de.

Since I am not the administrator of that instance there's not much I can there unfortunately. For the official instance it's still something I'm looking into.

**Comment by PureTryOut** [comment] 2019-08-17 23:08
I'm definitely up to date, version 0.19.1.

Invidious didn't log any error besides the following:
```
INSERT has more expressions than target columns
```

I added `check_tables: true` to the config which seems to have at least fixed that warning/error, but it didn't update my subscriptions sadly.

PostgreSQL doesn't have any obvious errors either.

**Comment by Gleddified** [comment] 2019-10-29 19:20
Still an issue for me on the official instance. If it's any help, this video, uploaded over a day ago, is still not in my subsciptions feed:

https://www.invidio.us/watch?v=WVDQEoe6ZWY

**Comment by schwukas** [comment] 2020-11-13 06:44
Despite the merged fix I am unfortunately still having that same problem where videos are shown in my Youtube but not the Invidious feed. 

I do however get quite a lot of errors in my invidious container logs:
```
UC3_VCOJMaivgcGqPCTePLBA : Invalid parameter: hub.callback; must be valid URI with no fragment and optional port in ranges 80-90, 440-450, 1024-65535
```
These usually come in bursts of 5-15 messages every 30 seconds or so.
I could not find where this is originating from. A web search did not yield any results and there is no such string in the repo. I'm running the latest code (557b0d76abe978cd8044a48f89313ef805954713). From what I can understand this reports some issue with reading that specific channel. This _might_ be a different issue, though. So let me know if I should open a new one.

**Comment by direkt** [comment] 2021-01-03 22:13
> Despite the merged fix I am unfortunately still having that same problem where videos are shown in my Youtube but not the Invidious feed.
> 
> I do however get quite a lot of errors in my invidious container logs:
> 
> ```
> UC3_VCOJMaivgcGqPCTePLBA : Invalid parameter: hub.callback; must be valid URI with no fragment and optional port in ranges 80-90, 440-450, 1024-65535
> ```
> 
> These usually come in bursts of 5-15 messages every 30 seconds or so.
> I could not find where this is originating from. A web search did not yield any results and there is no such string in the repo. I'm running the latest code ([557b0d7](https://github.com/iv-org/invidious/commit/557b0d76abe978cd8044a48f89313ef805954713)). From what I can understand this reports some issue with reading that specific channel. This _might_ be a different issue, though. So let me know if I should open a new one.
> 
> I do not see any error logs from postgresql.
> 
> _Edit:_ These originate from the `pubsubhubbub` module that's being used in `subscribe_pubsub()` in the file `helpers/utils.cr`. Shouldn't pubsub be disabled by default? Anyway, I don't think that's why I'm not getting up to date videos. I'll keep on digging.

Were you able to figure this out?  I am seeing it over and over in my logs and feeds are not updating.  I am running the docker image if that makes a difference.

**Comment by saltycrys** [comment] 2021-01-04 16:49
To fix the `pubsubhubbub` errors it's enough to fill in the domain in the config. `domain: localhost` works for a local instance.

Subscriptions freeze because sometimes requests to YouTube stall forever. Updating subscriptions happens in `channel_threads` count loops that collectively fetch all channels every minute. Once all those loops stalled subscriptions freeze. A workaround for this is to increase `channel_threads` (defaults to 1).

**Comment by Numline1** [comment] 2021-01-31 11:31
I can confirm, I'm having this very same issue. Recreating the docker container fixes that temporarily (usually just for one refresh run), then it breaks again.

**Comment by m4teh** [comment] 2021-03-08 21:43
After a few days of running ec30f7, it appears subscriptions are auto updating again. For the first time in years, for me. I suspect pull #1849 was what did it?

**Comment by randrej** [comment] 2021-09-13 15:21
This was never fixed for me; instead, I have a systemd timer that restarts the container every 6 hours and that's the sole reason my invidious instance is usable. Otherwise, it just stops updating the subscriptions after 6-12h, and has done so for at least the last year. I'm always on the latest version, too.

**Comment by sylv-io** [comment] 2021-09-14 12:42
> This was never fixed for me; instead, I have a systemd timer that restarts the container every 6 hours and that's the sole reason my invidious instance is usable. Otherwise, it just stops updating the subscriptions after 6-12h, and has done so for at least the last year. I'm always on the latest version, too.

same issue in my case, too :+1:

**Comment by erinarbleizez** [comment] 2021-10-07 09:29
Same here, I usually restart the docker when I go to my sub feed and don't see any new video...
On another server invidious is not installed through docker but the problem is also here

I checked the log and nothing in them. I just updated channel_threads hope this will work

**Comment by unixfox** [comment] 2022-04-17 21:14
We recommend to either periodically restart invidious or enable pubsub in the settings.

**Closed by unixfox** 2022-04-17 21:14 UTC
Labels: bug
