### ISSUE TITLE
Trending API Missing hash key error [Bug] 

### ISSUE THREAD

**Issue by keshavbhatt** [iv-org/invidious#1958] opened 2021-03-31 15:37 UTC
**Describe the bug**
When accessing Trending API (https://invidious.snopyta.org/api/v1/trending?region=us&type=music) for example, Getting 
`error":"Missing hash key: \"subMenu\"","errorBacktrace":"Missing hash key:`

**Steps to Reproduce**
1. Go to https://invidious.snopyta.org/api/v1/trending?region=us&type=music 
2. Notice the error response.

Other:
Hitting this API endpoint used to return JSON response of trending videos from passed region and category described by 'type' parameter, which no longer seems to work.

**Comment by hackerncoder** [comment] 2021-03-31 15:41
This appears to be a duplicate of #1755. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-03-31 15:41 UTC
Labels: duplicate
