### ISSUE TITLE
[Bug] Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError) for invalid (and deleted) channel

### ISSUE THREAD

**Issue by Trung0246** [iv-org/invidious#2214] opened 2021-06-26 22:24 UTC
**Describe the bug**
Hi, after attempting to put an invalid channel like https://invidious.silkky.cloud/channel/UCaaaaaaaaaaaaaaaaaaaaaa, the result is this:
![image](https://user-images.githubusercontent.com/11626920/123527120-bd550600-d691-11eb-96ae-a3c552a03d07.png)

Interestingly https://invidious.silkky.cloud/channel/Uaaaaaaaaaaaaaaaaaaaaaaa (same amount of character, just replacing `C` with `a`) and https://invidious.silkky.cloud/channel/UCaaaaaaaaaaaaaaaaaaaaa (delete a single `a`), invidious reported those as `This channel does not exist.` which is a correct behaviour I assume.

**Steps to Reproduce**

**Logs**

```
Title: `Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)`
Date: `2021-06-26T22:21:06Z`
Route: `/channel/UCaaaaaaaaaaaaaaaaaaaaaa`
Version: `2021.06.25-135ae11 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "interactiveTabbedHeaderRenderer" (KeyError)
  from /usr/share/crystal/src/hash.cr:1027:11 in '[]'
  from /usr/share/crystal/src/json/any.cr:102:7 in '[]'
  from src/invidious/channels.cr:814:14 in 'get_about_info'
  from src/invidious.cr:1702:15 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>
```

**Additional context**
This bug also triggerable for channel that have been deleted like https://playboard.co/en/channel/UC_FqH-6GpFosu_P0ApjqW5A/about (currently linking Playboard which they have an "archive" for the channel). Obviously https://www.youtube.com/channel/UC_FqH-6GpFosu_P0ApjqW5A returns `This channel does not exist.`.

**Comment by syeopite** [comment] 2021-06-26 22:27
Duplicate of #2137 but thanks for reporting! The fact that this also applies to invalid or deleted channels was unknown.

**Closed by syeopite** 2021-06-26 22:27 UTC
Labels: bug
