### ISSUE TITLE
Trending page is broken. 

### ISSUE THREAD

**Issue by Chuckalate** [iv-org/invidious#2713] opened 2021-12-10 18:54 UTC
Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-12-10T18:53:13Z`
Route: `/feed/trending`
Version: `2021.12.06-f236a687 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/pointer.cr:130:6 in 'decode_length_seconds'
  from src/invidious/yt_backend/extractors.cr:82:28 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:327:20 in 'parse'
  from src/invidious/yt_backend/extractors.cr:288:16 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:582:28 in 'extract_videos'
  from src/invidious/trending.cr:19:14 in 'trending'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2021-12-10 19:19
Duplicate of https://github.com/iv-org/invidious/issues/2708

**Closed by unixfox** 2021-12-10 19:19 UTC
Labels: bug
