### ISSUE TITLE
[Feature request] Add Bypass YouTube Age Restriction script

### ISSUE THREAD

**Issue by JnTon** [iv-org/invidious#2403] opened 2021-09-14 11:14 UTC
[This is a script](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass) that allows the user to bypass YouTube's age restriction, could be implemented into Invidious? This would be very useful, age restriction imposes people to make and use a Google account and to submit a personal document if they live in the EU.

**Comment by unixfox** [comment] 2021-09-14 11:19
duplicate of https://github.com/iv-org/invidious/issues/2189 and we don't plan to use an external service just for that: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/main/Simple-YouTube-Age-Restriction-Bypass.user.js#L42

**Closed by unixfox** 2021-09-14 11:19 UTC
Labels: feature-request
