### ISSUE TITLE
[Bug] Yewtu.be returns error when you click on a playlist from the search results

### ISSUE THREAD

**Issue by hohenheim1618** [iv-org/invidious#2688] opened 2021-12-01 13:03 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

Title: `Missing hash key: "runs" (KeyError)`
Date: `2021-12-01T12:55:22Z`
Route: `/playlist?list=PLVnkoLiLMTm5ujnVrL0stYImWGU9svQlK`
Version: `2021.12.01-d673014 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "runs" (KeyError)
  from /usr/lib/crystal/core/json/any.cr:100:0 in '[]'
  from src/invidious/playlists.cr:355:41 in 'get_playlist'
  from src/invidious/playlists.cr:330:1 in 'show'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Additional context**

**Comment by unixfox** [comment] 2021-12-01 14:11
Probably a duplicate of https://github.com/iv-org/invidious/issues/2278

**Comment by SamantazFox** [comment] 2021-12-13 16:32
@unixfox could you please provide the JSON reply for said playlist?

You can use https://github.com/iv-org/youtube-utils/blob/master/scripts/yt-api-helper.sh
```
./yt-api-helper.sh -e browse --output file.json --data '{"browseId":"VLPLVnkoLiLMTm5ujnVrL0stYImWGU9svQlK","context":{"client":{"hl":"en","gl":"US","clientName":"WEB","clientVersion":"2.20210721.00.00","clientScreen":"WATCH_FULL_SCREEN"}}}'
```

**Comment by unixfox** [comment] 2021-12-14 08:20
[file.json.zip](https://github.com/iv-org/invidious/files/7709835/file.json.zip)

**Comment by unixfox** [comment] 2022-01-16 18:12
Seems to be fixed.

**Closed by unixfox** 2022-01-16 18:12 UTC
Labels: bug
