### ISSUE TITLE
[Bug] tube.connect.cafe cannot load a video

### ISSUE THREAD

**Issue by Cwpute** [iv-org/invidious#2560] opened 2021-11-03 22:30 UTC
**Describe the bug**
Cannot load this video on tube.connect.cafe, while the video still loads on invidious.snopyta.org

**Steps to Reproduce**
1. Go to https://tube.connect.cafe/watch?v=GF8lUEEmlrU
2. See logs

**Logs**
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from lib/db/src/db/pool.cr:240:9 in 'wait_for_available'
  from lib/db/src/db/pool.cr:85:35 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:7 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'player:video_id:params:client_config'
  from src/invidious/videos.cr:835:3 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:971:3 in 'fetch_video'
  from src/invidious/videos.cr:961:13 in 'get_video'
  from src/invidious/videos.cr:944:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from src/invidious.cr:317:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

**Additional context**
 - Browser: Mozilla Firefox 94.0 (32 bits)
 - OS: Windows 8

**Comment by SamantazFox** [comment] 2021-11-04 20:42
Duplicate of #1582. Also, it seems that it was a temporary instance issue.

**Closed by SamantazFox** 2021-11-04 20:42 UTC
Labels: duplicate, instance-issue
