### ISSUE TITLE
Bug: "Pool Retry Attempts Exceeded"

### ISSUE THREAD

**Issue by PikaDominator** [iv-org/invidious#2701] opened 2021-12-08 00:13 UTC
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2021-12-08T00:11:39Z`
Route: `/watch?v=R3OvKZeviv0`
Version: `2021.12.07-1b3e5c6 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/pool.cr:190:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:146:9 in 'query_one?:as'
  from src/invidious/videos.cr:997:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**What does this mean, and how to fix? Almost no background in coding here, for future reference. :)**

**Comment by Vegann** [comment] 2021-12-08 00:27
Same issue here but for `feed/subscriptions`

**Comment by SamantazFox** [comment] 2021-12-08 00:27
It means that invidious can't send request to your database

**Comment by SamantazFox** [comment] 2021-12-08 00:28
Closing, as it's a duplicate of #1582

**Closed by SamantazFox** 2021-12-08 00:28 UTC

**Comment by PikaDominator** [comment] 2021-12-08 01:29
Sorry. I tried searching before hand but must not have used the correct keywords. My apologies.
