### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by noah-frank** [iv-org/invidious#3754] opened 2023-04-18 01:31 UTC
Would it be possible to include the sponsor block (https://addons.mozilla.org/de/firefox/addon/sponsorblock/) addon into this project?

**Comment by ggtylerr** [comment] 2023-04-18 03:20
The extension already supports it. Options -> Misc. -> Add 3rd Party sites.
In case you mean integrating it into the site, this is a duplicate of...
* #1502
* #3130 
* #3519 
* #3604

**Comment by noah-frank** [comment] 2023-04-18 03:30
Thank you for your quick reply. I tried the search but it seems that I failed. Anyway thank you I found the option in the addon settings and added my invidious instance. Works perfect :) Is the same possible with the return youtube dislike button addon?

**Comment by ggtylerr** [comment] 2023-04-18 03:32
Refer to #2707

**Comment by noah-frank** [comment] 2023-04-18 03:33
Thanks again 👍🏼

**Closed** 2023-04-18 05:54 UTC
Labels: feature-request
