### ISSUE TITLE
[Bug] Leading spaces indescription are not visible

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2575] opened 2021-11-09 23:46 UTC
**Describe the bug**

Spaces at the beginning of a line (e.g for indenting text) in the video description are not visible.

Possible fix:
```css
#descriptionWrapper {
    white-space: pre-wrap;
}
```

**Steps to Reproduce**

Go to `/watch?v=5MAlgKdsdvg`

**Screenshots**

Expected (Youtube)
![image](https://user-images.githubusercontent.com/52980486/141022870-d7ac5c55-8801-4252-905a-a6fb84915b33.png)

Bug (Invidious):
![image](https://user-images.githubusercontent.com/52980486/141022909-49e913b8-60db-41eb-838c-646a0d28c2f9.png)

**Comment by syeopite** [comment] 2021-11-10 13:52
Duplicate of #1954

**Closed by syeopite** 2021-11-10 13:52 UTC
Labels: bug, type:client-side

**Comment by SamantazFox** [comment] 2021-11-13 19:34
Ah, crap, sorry :X
