### ISSUE TITLE
[Bug] "The following content is not available on this app."

### ISSUE THREAD

**Issue by accessiblepixel** [iv-org/invidious#3217] opened 2022-07-24 12:04 UTC
**Describe the bug**

On viewing a certain video on YouTube through my local install of Invidious, I get a video that isn't the requested content that has in it `The Following Content is not available on this app. Watch this content on the latest version of YouTube'. It appears to be a video of 5 minutes long.

**Steps to Reproduce**

I have proxy videos enabled and I went to watch?v=mYCesQJLNgw (the video I'm trying to watch) and the error is displayed. I also tried disabling proxy videos and got the same message.

I have my video quality set to DASH, and 720p preferred quality.
**Logs**

**Screenshots**

[Screenshot](https://i.lowrex.com/i/BJv2d.png)
**Additional context**

Browser is Firefox in Windows. Running the Docker version of Invidious. Haven't tried pulling the latest image yet, but will try that and report back any change.

Please let me know if there's any further information that I can provide to help trace the issue.

Kind regards,
Jessica

**Comment by accessiblepixel** [comment] 2022-07-24 12:15
Okay, seems like updating invidious to latest tag fixed the issue, please disregard.

If anyone else has same issue, just pull latest image and redeploy. x

Kind regards,
Jessica.

**Comment by unixfox** [comment] 2022-07-24 14:13
What even is this message? Invidious doesn't produce this message, only the real youtube does.

This bug is odd.

**Comment by accessiblepixel** [comment] 2022-07-25 00:24
Yes, it's a bit strange... but it has been fixed by the looks of it in the updated invidious.

My guess is one of the requests that Invidious sends to youtube, caused YouTube to send back that 5 minute video saying that it was an unsupported app, since to them it seemed like an older app was trying get a video?

That's my theory, but I'm not sure. I could see if I could pull out what version of invidious I was using at the time, but one of the problems is on each page it doesn't show what version it's currently running, just what the latest version on github is.

If you'd like me to fish out the old version and find out what it was, I can certainly try, but other than my theory I have nothing else to go on really.

Kind regards,
Jessica.

**Comment by accessiblepixel** [comment] 2022-07-27 01:41
Okay, so I'm gonna reopen this since I've found another video that's doing the same thing.

watch?v=TBcXXfzrqco plays that same 5 minute video saying to watch it on the latest YouTube.

**Comment by accessiblepixel** [comment] 2022-07-27 01:44
For that video (watch?v=TBcXXfzrqco) I went though all my preferences for video quality (from small, medium HD720 and the DASH quality options) and I still only got that 5 minute video replacing the content. It's so weird.

Does anyone have any ideas? I'm pretty stumped on this!

Kind regards,
Jessica

**Comment by accessiblepixel** [comment] 2022-07-27 01:51
Okay, after I updated the other day the version I was running was 2022.07.19-5e09077 @ master

I'm trying a new pull on docker to see if I can grab the version from 2022.07.25 since other instances that are running this, it appears to work, so maybe something got fixed again.

Okay, in version  2022.07.25-210c2a8 @ master it seems to be fixed again.

**Comment by unixfox** [comment] 2022-07-27 07:51
I'm pretty sure you have a browser extension or something that is messing up with the video content.

Next time please test with a browser without any extension on it.

By the way I can't reproduce the issue on an instance with the same exact version: https://inv.riverside.rocks/watch?v=TBcXXfzrqco

Closing this issue as you said it's fixed.

**Closed by unixfox** 2022-07-27 07:51 UTC
Labels: bug

**Comment by accessiblepixel** [comment] 2022-07-27 11:28
Normally I use Firefox and I do use an extension, sponsorblock.

But the first thing I tried was using it in a different browser (Chrome) without any extensions and had the same issue... so your assumption wasn't correct.

I was just trying to help, in the spirit of open source, providing all the detail that I could and the offer to provide more if I was told what... and now I regret it.

Kind regards,
Jessica
