### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lil1sean** [iv-org/invidious#2475] opened 2021-10-07 17:23 UTC
Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-10-07T17:20:54Z`
Route: `/search?q=nba+youngboy`
Version: `2021.10.04-d8063106 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/pointer.cr:130:6 in 'decode_length_seconds'
  from src/invidious/helpers/extractors.cr:77:113 in 'process'
  from src/invidious/helpers/extractors.cr:532:17 in 'extract_item'
  from src/invidious/helpers/extractors.cr:556:28 in 'extract_items'
  from src/invidious/search.cr:36:11 in 'search'
  from src/invidious/search.cr:232:20 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2021-10-07 17:25
Duplicate of https://github.com/iv-org/invidious/issues/2449

**Closed by unixfox** 2021-10-07 17:25 UTC
Labels: bug
