### ISSUE TITLE
[Bug] keep getting network error on videos

### ISSUE THREAD

**Issue by godspeed-x** [iv-org/invidious#2164] opened 2021-06-17 06:41 UTC
**Describe the bug**

Whatever video I play, after I while I get this error and the video stops. I have tried a few different instances but it's the same.

**Screenshots**

![image](https://user-images.githubusercontent.com/74945202/122344394-613d0400-cf64-11eb-8e0b-9d19ce27474a.png)

**Additional context**

Browser: Firefox

**Comment by unixfox** [comment] 2021-06-17 07:05
Duplicate of https://github.com/iv-org/invidious/issues/882

**Closed by unixfox** 2021-06-17 07:05 UTC
Labels: bug
