### ISSUE TITLE
"Could not check out a connection in 5.0 seconds" - YouTube servers stopped serving HTTP3/QUIC

### ISSUE THREAD

**Issue by ThatIsAPseudo** [iv-org/invidious#2577] opened 2021-11-12 10:37 UTC
By @unixfox:

⚠️ We pushed a fix to Invidious, **update your instance against the latest code in order to have a working experience again.**
Make sure to also turn to false `use_quic` in the config file if updating doesn't fix the bug. Removing the parameter `use_quic` from the config file works too.

If you use a public instance, and it doesn't work anymore, then please try to use another one from this list: https://instances.invidious.io

Basically, Google servers stopped serving HTTP3/QUIC and Invidious used to exclusively use HTTP3/QUIC for connecting to YouTube servers. That's why Invidious didn't really work anymore.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4016501/141461136-878bed2d-0d43-471d-9115-8654550d0f60.png">

-----

Original issue:

**Describe the bug**
Can't load anything on *any* invidious instance (_edit_: except the home page)

**Steps to Reproduce**
1. Go to any invidious instance
2. Click on a video/search for a term
3. See error

**Logs**

Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T10:31:35Z`
Route: `/search?q=test+search`
Version: `2021.11.08-21879da8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:540:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:14 in '_post_json'
  from src/invidious/search.cr:36:11 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by rzr** [comment] 2021-11-12 10:41
Same here with https://yewtu.be/watch?v=yI_Jiy_RKeU 

cc: @lpapp

Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T10:38:46Z`
Route: `/watch?v=yI_Jiy_RKeU`
Version: `2021.11.12-4f09430 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/lib/crystal/core/mutex.cr:47:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:7 in '_post_json'
  from /usr/lib/crystal/core/hash.cr:1139:13 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1139:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by ThatIsAPseudo** [comment] 2021-11-12 10:42
Probably linked to an undergoing Google outage in Europe : https://news.ycombinator.com/item?id=29197832

**Comment by n0thanky0u4444** [comment] 2021-11-12 10:43
Also having the same issue on multiple browsers and multiple machines

**Comment by rramiachraf** [comment] 2021-11-12 10:44
I encountered the same issue, I thought something was wrong with the instance I was using but I've tried several others and not a single one worked.

**Comment by Wojnstup** [comment] 2021-11-12 10:54
Yeah, it was working around half an hour ago, now every instance is down.

**Comment by yujiri8** [comment] 2021-11-12 11:07
I am encountering this for the first time on https://vid.puffyan.us/watch?v=zrGWalenkYE

**Comment by yujiri8** [comment] 2021-11-12 11:07
It says this:
```
Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T11:07:18Z`
Route: `/watch?v=zrGWalenkYE`
Version: `2021.11.07-6cabc96f @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/time/span.cr:75:15 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:14 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:970:10 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>
```

**Comment by artenaki** [comment] 2021-11-12 11:14
Google also closed Invidious project?

**Comment by unixfox** [comment] 2021-11-12 11:37
Basically, Google servers stopped serving HTTP3/QUIC and Invidious exclusively use HTTP3/QUIC for connecting to YouTube servers. That's why Invidious doesn't really work anymore until Google fixes their servers.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4016501/141461136-878bed2d-0d43-471d-9115-8654550d0f60.png">

**Comment by Rjevski** [comment] 2021-11-12 11:59
Can this be worked around? Nginx has beta support for QUIC & HTTP3: https://quic.nginx.org - can it be configured to reverse-proxy to YouTube and the hosts file made to redirect YT's DNS to the local host so Invidious can use it?

**Comment by miclill** [comment] 2021-11-12 12:11
@yujiri8 the backtrace i'm getting seems sligthly different than yours:

Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T12:08:10Z`
Route: `/watch?v=X8k_4tZ16qU`
Version: `2021.11.12-4f09430 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/lib/crystal/core/mutex.cr:47:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:7 in '_post_json'
  from /usr/lib/crystal/core/hash.cr:1139:13 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1139:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by Rjevski** [comment] 2021-11-12 12:18
@syeopite I've just tested disabling QUIC using the existing `USE_QUIC` setting on a fairly old (~2 months?) Invidious clone and am getting the following error:

```
Title: `Unexpected char '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-11-12T12:17:23Z`
Route: `/watch?v=6tDzprIM5gg`
Version: `n/a-n/a @ n/a`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:376:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:372:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:371:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:225:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '_post_json'
  from src/invidious/helpers/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:971:10 in 'fetch_video'
  from src/invidious/videos.cr:953:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>
```

I am now building your branch and will report back if it's better.

**Comment by syeopite** [comment] 2021-11-12 12:18
@Rjevski 
> Can this be worked around? Nginx has beta support for QUIC & HTTP3: https://quic.nginx.org - can it be configured to reverse-proxy to YouTube (essentially upgrading it to HTTP/3) and the hosts file made to redirect YT's DNS to the local host so Invidious can use it?

The problem isn't due to not using HTTP/3, rather it's because we are currently using it and YouTube has, for whatever reason, decided to randomly stop serving HTTP/3 requests.

#2364 would resolve this problem nicely. It's just a matter of when we can get it merged and unfortunately we tend to be quite slow on that front :(

**Comment by syeopite** [comment] 2021-11-12 12:19
> I am now building your branch and will report back if it's better.

Yes, `use_quic` has been broken on master for quite awhile unfortunately.

**Comment by Rjevski** [comment] 2021-11-12 12:20
@syeopite yes my idea with Nginx was to use it as a reverse-proxy to "upgrade" Youtube's legacy HTTP endpoint into HTTP/3 so that existing Invidious could work with it.

**Comment by syeopite** [comment] 2021-11-12 12:26
Ah, sorry! I've completely misinterpreted that 😅.

> use it as a reverse-proxy to "upgrade" Youtube's legacy HTTP endpoint into HTTP/3...

In that case, I think that'll probably work; good workaround for any instance that stuck on a branch without #2364 currently.

**Comment by Rjevski** [comment] 2021-11-12 12:27
@syeopite your branch has been deployed to https://invidious.rjevski.io and appears to work. Feel free to use it in the meantime until other instances are updated. Just FYI, this instance does log minimal personal data such as IP addresses and user-agents in HTTP logs, though I have no incentive to use any of it and it's just there for debug purposes.

**Comment by balasratran** [comment] 2021-11-12 12:44
> @syeopite your branch has been deployed to https://invidious.rjevski.io and appears to work. Feel free to use it in the meantime until other instances are updated. Just FYI, this instance does log minimal personal data such as IP addresses and user-agents in HTTP logs, though I have no incentive to use any of it and it's just there for debug purposes.

Please guide me how to temporarily fix this problem. Thank you

**Comment by Rjevski** [comment] 2021-11-12 12:46
@balasratran deploy Syeopite's branch from this PR: https://github.com/iv-org/invidious/pull/2364 - it works out of the box.

My alternative to use Nginx as a reverse-proxy for YT might also work but is more difficult to set up.

**Comment by cysea** [comment] 2021-11-12 12:48
@balasratran 
```
cd invidious

git fetch origin pull/2364/head:quic-fix

git merge quic-fix

docker-compose down

add "use quic: false" to your docker-compose.yml under invidious config or manually edit invidious config.yml

docker-compose up -d --build
```

**Comment by TheFrenchGhosty** [comment] 2021-11-12 12:59
I just merged https://github.com/iv-org/invidious/pull/2364 

It's not entirely tested, but it should fix (workaround) this issue.

If you notice any bug with it please report it.

**Comment by syeopite** [comment] 2021-11-12 13:03
If you're using the compile time flag instead of modifying `use_quic`, please also report if you see any stability improvements.

lsquic is speculated to contribute a massive portion to Invidious' crashes and memory leaks, and the compile time flag `disable_quic` strips that out entirely.

**Comment by artenaki** [comment] 2021-11-12 13:30
@Rjevski Thanks for your instance. Perhaps someone will find useful this greseamonkey redirection script https://pastebin.com/44tL7iz8

**Comment by unixfox** [comment] 2021-11-12 13:31
For yewtu.be I'm waiting for the build to have a working experience again: https://github.com/unixfox/invidious-custom/actions/runs/1451957414

In around 1 hour yewtu.be should be fixed.

**Comment by rzr** [comment] 2021-11-12 14:33
I confirm https://yewtu.be/watch?v=vjaQifTSLc8 is now working again thx for your reactivity 
May this be closed now ?

**Comment by unixfox** [comment] 2021-11-12 14:37
> I confirm [yewtu.be/watch?v=vjaQifTSLc8](https://yewtu.be/watch?v=vjaQifTSLc8) is now working again thx for your reactivity May this be closed now ?

No because the issue is still happening on youtube servers side and there are still some instances maintainers not aware of the issue.

**Comment by SamantazFox** [comment] 2021-11-12 16:27
poke @tio-trom, @artemislena, @hys0star, @TechnicalSuwako, @FireMasterK, @RiversideRocks, @ItsSt0ne, @mintphin and @11Tuvork28, @ytprivatecom, @Midou36O y'all should update your instances :)

**Comment by FireMasterK** [comment] 2021-11-12 16:34
Updated.

**Comment by SamantazFox** [comment] 2021-11-12 16:39
Also poke @vituperative and @cysea

**Comment by 11Tuvork28** [comment] 2021-11-12 16:51
> poke @tio-trom, @artemislena, @hys0star, @TechnicalSuwako, @FireMasterK, @RiversideRocks, @ItsSt0ne, @mintphin and @11Tuvork28, @ytprivatecom, @Midou36O y'all should update your instances :)

Already done :)

**Comment by cysea** [comment] 2021-11-12 17:02
@SamantazFox I was the first one to test syeopite's MR, thanks though! :100:

**Comment by RiversideRocks** [comment] 2021-11-12 17:18
All done, thanks, any idea why Google shut down quic support?

**Comment by TheFrenchGhosty** [comment] 2021-11-12 17:19
@RiversideRocks We have no idea, it doesn't even make sense considering they use it themselves. It's just *weird*.

**Comment by MarkG-108** [comment] 2021-11-12 18:40
Same issue.  It happened on instance _https://vid.mint.lgbt/watch?v=kqnvrjgyEMc_

`Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T18:31:46Z`
Route: `/watch?v=kqnvrjgyEMc`
Version: `2021.11.08-21879da8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:538:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:14 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:970:10 in 'fetch_video'
  from src/invidious/videos.cr:952:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>`

**Comment by unixfox** [comment] 2021-11-12 19:17
> Same issue. It happened on instance _[vid.mint.lgbt/watch?v=kqnvrjgyEMc](https://vid.mint.lgbt/watch?v=kqnvrjgyEMc)_
> 
> `Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`Date:`2021-11-12T18:31:46Z`Route:`/watch?v=kqnvrjgyEMc`Version:`2021.11.08-21879da8 @ master`
> Backtrace
> `

Use another instance from this list :): https://api.invidious.io/

**Comment by yungsmoke9** [comment] 2021-11-12 20:22
The issue on  vid.mint.lgbt/watch?v=kqnvrjgyEMc is still happening may i get a progress update.

**Comment by unixfox** [comment] 2021-11-12 20:29
> The issue on vid.mint.lgbt/watch?v=kqnvrjgyEMc is still happening may i get a progress update.

Use another instance from this list while the maintainer of vid.mint.lgbt fix the issue :): https://instances.invidious.io

**Comment by Rjevski** [comment] 2021-11-12 22:32
@RiversideRocks @TheFrenchGhosty there's been outages on Google services today so I wonder if disabling QUIC is a mitigation strategy for them (maybe QUIC infrastructure is dead but legacy HTTP isn't)?

**Comment by unixfox** [comment] 2021-11-12 22:36
> @RiversideRocks @TheFrenchGhosty there's been outages on Google services today so I wonder if disabling QUIC is a mitigation strategy for them (maybe QUIC infrastructure is dead but legacy HTTP isn't)?

Probably QUIC/HTTP3 doesn't even work:
```
[emilien@pcryzen]: ~>$ curl3 --http3 -I -v https://www.youtube.com
*   Trying 2a00:1450:4009:822::200e:443...
* Connect socket 5 over QUIC to 2a00:1450:4009:822::200e:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
*   Trying 216.58.212.238:443...
* Connect socket 6 over QUIC to 216.58.212.238:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* After 149973ms connect time, move on!
* connect to 2a00:1450:4009:822::200e port 443 failed: Connection timed out
*   Trying 2a00:1450:4009:823::200e:443...
* Connect socket 7 over QUIC to 2a00:1450:4009:823::200e:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* After 74887ms connect time, move on!
* connect to 2a00:1450:4009:823::200e port 443 failed: Connection timed out
*   Trying 2a00:1450:4009:817::200e:443...
* Connect socket 5 over QUIC to 2a00:1450:4009:817::200e:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* After 37444ms connect time, move on!
* connect to 2a00:1450:4009:817::200e port 443 failed: Connection timed out
*   Trying 2a00:1450:4009:80a::200e:443...
* Connect socket 7 over QUIC to 2a00:1450:4009:80a::200e:443
* Sent QUIC client Initial, ALPN: h3-29,h3-28,h3-27
* After 18722ms connect time, move on!
* connect to 2a00:1450:4009:80a::200e port 443 failed: Connection timed out
* Connection timed out after 300000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 300000 milliseconds
```

And youtube servers are trying to tell every browser to stop using QUIC/HTTP3 with this HTTP header:
```
[emilien@pcryzen]: ~>$ curl -I https://www.youtube.com
HTTP/2 200
alt-svc: clear
```

**Comment by RiversideRocks** [comment] 2021-11-12 22:38
Maybe they are trying to limit UDP packets to determine the problem? No idea

**Comment by RiversideRocks** [comment] 2021-11-12 22:46
Also, would it be possible to make the code fall back to HTTP/2 or HTTP/1.1 if it detects QUIC is down?

**Comment by unixfox** [comment] 2021-11-12 22:48
> Also, would it be possible to make the code fall back to HTTP/2 or HTTP/1.1 if it detects QUIC is down?

Not easily, but I guess we will probably stop using QUIC because the native HTTP client in crystal is much more stable than lsquic.

@syeopite thoughts?

**Comment by Joshndroid** [comment] 2021-11-13 00:47
I did a fresh docker update about 20 minutes ago and am also seeing this error 

`Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-13T00:41:42Z``

**Comment by unixfox** [comment] 2021-11-13 00:49
> I did a fresh docker update about 20 minutes ago and am also seeing this error
> 
> `Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`Date:`2021-11-13T00:41:42Z``

Check if use_quic is not set to true in the config file. If that's the case then turn it to false.

**Comment by Joshndroid** [comment] 2021-11-13 00:58
> > I did a fresh docker update about 20 minutes ago and am also seeing this error
> > `Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`Date:`2021-11-13T00:41:42Z``
> 
> Check if use_quic is set to true in the config file. If that's the case then turn it to false.

Absolutely perfect. This was exactly the next step I needed to get it going again. Thanks for the super quick reply

**Comment by DmitrySandalov** [comment] 2021-11-13 10:32
Built from d214a0b3330e6cbb3f42fc321510076238467731, works fine for me (`use_quic` is absent in my config).

**Comment by ianswett** [comment] 2021-11-16 17:23
Given UDP can also be blocked, I'd highly suggest falling back to a prior version of TCP when HTTP/3 fails.

From the HTTP/3 spec, [section 3](https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-3):
 "Connectivity problems (e.g., blocking UDP) can result in QUIC
   connection establishment failure; clients SHOULD attempt to use TCP-
   based versions of HTTP in this case."

**Comment by unixfox** [comment] 2021-11-16 18:29
> Given UDP can also be blocked, I'd highly suggest falling back to a prior version of TCP when HTTP/3 fails.
> 
> From the HTTP/3 spec, [section 3](https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-3): "Connectivity problems (e.g., blocking UDP) can result in QUIC connection establishment failure; clients SHOULD attempt to use TCP- based versions of HTTP in this case."

While I completely agree with you, the current state of the invidious code is not made to support an automatic fallback to HTTP1/HTTP2 in TCP. That's why we allow the user, for example if UDP is blocked, to switch from QUIC to HTTP1 with the setting `use_quic`.

**Comment by unixfox** [comment] 2021-11-17 09:41
Closing as YouTube just recently restored QUIC connections.

```
[emilien@pcryzen]: ~>$ curl -I https://www.youtube.com
HTTP/2 200
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

<img width="722" alt="image" src="https://user-images.githubusercontent.com/4016501/142176061-88ed8a98-6df0-4b50-91fd-63191b5b9ce5.png">

You may now turn `use_quic` to true if you are experiencing some issue when QUIC is not enabled, or you may not touch anything if "everything" works on your side.

**Closed** 2021-11-17 09:41 UTC
Labels: bug, type:youtube-change

**Comment by artenaki** [comment] 2021-11-28 10:39
Bonjour @unixfox
Where did you get curl with http3 support? This is an experimental option and as far as I know is not enabled by default.

Of course, I compiled curl --with-nghttp3 --with-ngtcp2 and openssl-quic library in Ubuntu 16.04 i386, it wasn't easy though. You probably have a package from [AUR](https://aur.archlinux.org/packages/curl-http3/) with quiche (rust)?
