### ISSUE TITLE
Where to insert the proxy list?

### ISSUE THREAD

**Issue by wilsden** [iv-org/invidious#1036] opened 2020-02-18 16:29 UTC
I have 100 + proxies ipv4
I registered in the config force_resolve : ipv4
Where to register my proxies? i can't understand it
Please help, thanks!

**Comment by unixfox** [comment] 2020-03-04 20:18
There is currently no way of using an external proxy in the configuration, what you have to do is to use a "wrapper" like proxychains to redirect the requests of invidious to your proxies.

**Comment by unixfox** [comment] 2021-05-27 06:44
Bump, now that we can use http2 it's possible to implement that.

**Comment by unixfox** [comment] 2021-08-07 07:26
Duplicate of https://github.com/iv-org/invidious/issues/301

**Closed by unixfox** 2021-08-07 07:26 UTC
Labels: question
