### ISSUE TITLE
[Bug] Can't play videos

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2946] opened 2022-03-02 12:02 UTC
**Describe the bug**
Sometimes, videos are unplayable. When clicking on play, the image in the player is reduced, the video duration is estimed at 0, and the apparent load is infinite.

**Steps to Reproduce**

1. Go to some video
2. Click on play

**Screenshots**
![Screenshot_20220302_130138](https://user-images.githubusercontent.com/22192600/156358096-fd4cd86a-753a-49b4-8846-cfa5c3cf5e09.png)

**Comment by unixfox** [comment] 2022-03-02 12:28
Can you give the instance that you used? The URL that you used?

**Comment by stemy2** [comment] 2022-03-02 12:34
It's really random, it can happens with any instance and any video, and sometimes, refreshing the page can fix it at least temporarly. This is why i don't give you the URL, i'm pretty sure you won't be able to reproduce the problem.

**Comment by unixfox** [comment] 2022-03-02 12:51
Do you have dash enabled or you didn't touch preferences?

**Comment by stemy2** [comment] 2022-03-02 13:02
> Do you have dash enabled or you didn't touch any preferences/parameters?
I don't know, could it fix my problem ?

**Comment by unixfox** [comment] 2022-03-02 13:09
You can try to enable dash in the preferences, that could fix some issues.

**Comment by unixfox** [comment] 2022-03-03 19:58
Closing because I can't really reproduce the issue.

**Closed by unixfox** 2022-03-03 19:58 UTC
Labels: bug

**Comment by trackhacs** [comment] 2022-12-26 21:14
had the same problem - but switching to DASH actually solved the problem for me.
