### ISSUE TITLE
[Bug] Missing hash key: "navigationEndpoint" (KeyError)

### ISSUE THREAD

**Issue by DerKaiser4709** [iv-org/invidious#4292] opened 2023-11-26 13:32 UTC
When ‘worbs’ are typed into the search bar, this log appars
**Steps to Reproduce**
1. 'Open invidious'
2. Search and type ‘worbs’

**Logs**
Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2023-11-26T13:27:51Z`
Route: `/search?q=worbs`
Version: `2023.11.21-9ce9c54 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:332:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:845:17 in 'parse_item'
  from src/invidious/yt_backend/extractors.cr:892:14 in 'extract_items'
  from src/invidious/search/processors.cr:12:18 in 'process'
  from src/invidious/routes/search.cr:55:17 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>
 Source code
 Documentation
Released under the AGPLv3 on GitHub.
 View JavaScript license information.
 View privacy policy.
 Donate
Current version: 2023.11.21-9ce9c54 @ master 

 - Browser (Brave):
 - Realme 3 Android

**Comment by jackwilsdon** [comment] 2023-11-26 13:33
Duplicate of #2530.

**Closed** 2023-11-26 14:11 UTC
Labels: bug
