### ISSUE TITLE
RefreshChannelsJob: xxxxxxxxxxxxxxxxx : Unexpected char '<' at 1:1

### ISSUE THREAD

**Issue by tmiland** [iv-org/invidious#1710] opened 2021-01-26 18:52 UTC
Been getting this error lately:

`RefreshChannelsJob: xxxxxxxxxxxxxxxxx : Unexpected char '<' at 1:1`

Personal feed hasn't been updated for 14 days now.

What gives?

**Comment by ytprivatecom** [comment] 2021-01-27 09:13
@tmiland Which instance?

**Comment by hackerncoder** [comment] 2021-01-27 13:16
Duplicate of or similar to: https://github.com/iv-org/invidious/issues/1637#issuecomment-755343086

**Comment by tmiland** [comment] 2021-01-28 16:15
Temporary solution:

Do: `tail -f /home/invidious/invidious/invidious.log | grep 'RefreshChannelsJob'`

Then take the `CHANNEL_ID` with the error: `Unexpected char '<' at 1:1`

And then do: `sudo -i -u postgres psql invidious -c "select * from "channels" where "id" like '%CHANNEL_ID%';"`

Then see under `Author`. If it's f.eks `News`, then do this:

First: `sudo -i -u postgres psql invidious -c "select * from "channels" where "author" like '%News%';"`

To see the results before deleting anything.

Then do: `sudo -i -u postgres psql invidious -c "delete from "channels" where "author" like '%News%';"` to delete the channel(s).

And so on, until there's no more topic channels left.

Profit! :+1:

**Closed** 2021-01-29 22:43 UTC
Labels: duplicate
