### ISSUE TITLE
[Bug] Invalid Int32: "@ServusChristi" (ArgumentError)

### ISSUE THREAD

**Issue by kithstack1** [iv-org/invidious#3421] opened 2022-11-21 09:13 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Title: `Invalid Int32: "@ServusChristi" (ArgumentError)`
Date: `2022-11-21T09:08:31Z`
Route: `/search?q=apostasy+report`
Version: `2022.11.02-09942dee @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@ServusChristi" (ArgumentError)
  from /usr/share/crystal/src/string.cr:422:83 in 'to_i32'
  from src/invidious/yt_backend/extractors.cr:172:26 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:36 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-11-21 20:10
Closing as a duplicate of #3394

**Closed by SamantazFox** 2022-11-21 20:10 UTC
Labels: bug
