### ISSUE TITLE
[Bug] Video doesnt open

### ISSUE THREAD

**Issue by gitgut2006** [iv-org/invidious#2558] opened 2021-11-03 17:36 UTC
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2021-11-03T17:21:56Z`
Route: `/embed/V2_4llLPc_g?feature=oembed`
Version: `2021.11.03-b41bc1c @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:146:9 in 'query_one?:as'
  from src/invidious/videos.cr:945:7 in 'get_video:region'
  from src/invidious/routes/embed.cr:122:15 in 'show'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>

**Comment by unixfox** [comment] 2021-11-03 17:37
Can you tell us which invidious instance did you use?

**Comment by gitgut2006** [comment] 2021-11-03 17:38
https://yewtu.be

**Comment by unixfox** [comment] 2021-11-03 17:39
Did you refresh the page? Does it fixes the issue?

**Comment by gitgut2006** [comment] 2021-11-03 17:40
It does

**Comment by KeshaunRocks** [comment] 2021-11-03 17:42
I've gotten the "Pool Retry Attempts Exceeded" too when attempting to view the video.

**Comment by unixfox** [comment] 2021-11-03 19:09
Thank you for your comments.

Duplicate of https://github.com/iv-org/invidious/issues/1582

**Closed by unixfox** 2021-11-03 19:09 UTC
Labels: bug
