### ISSUE TITLE
[Bug] On iPhone: Long videos not loading when in "Listen" mode

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4017] opened 2023-07-27 14:31 UTC
On iPhone: When opening videos in "Listening" mode (no video shown), sometimes the sound does not start (loading takes forever).
When choosing to watch the video (instead of just listening to it), the video starts immediately.

Example with a 2h video: https://www.youtube.com/watch?v=SS2gWoS86XY

This video (when watching as video and not as audio-only) starts immediately when watching it on my iphone. 
Listening to it: The loading spinner just turns forever

When listening to the same video on my Macbook: The loading happens instantly (works fine)

**Comment by unixfox** [comment] 2023-07-27 16:35
Duplicate of https://github.com/iv-org/invidious/issues/3623

**Closed by unixfox** 2023-07-27 16:35 UTC
Labels: bug
