### ISSUE TITLE
[Bug] Missing hash key: "audioStreams" (KeyError)

### ISSUE THREAD

**Issue by harpermg** [iv-org/invidious#3860] opened 2023-06-06 18:13 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Title: `Missing hash key: "audioStreams" (KeyError)`
Date: `2023-06-06T18:10:23Z`
Route: `/watch?v=0CTp1a-aCUM&listen=false`
Version: `2023.05.31-16ac3be8 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "audioStreams" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '??'
  from /usr/share/crystal/src/json/any.cr:249:3 in 'fmt_stream'
  from src/invidious/routes/watch.cr:128:18 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:502:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2023-06-06 19:30
Can you try cleaning the "videos" table in the database?

```bash
sudo su - postgres
psql invidious -c "DELETE FROM video * ;"
```

**Comment by unixfox** [comment] 2023-06-06 19:37
@harpermg which instance are you using?

**Comment by harpermg** [comment] 2023-06-06 20:37
privacydev.net

**Comment by SamantazFox** [comment] 2023-09-10 10:22
By now the problem should have been resolved?

**Comment by unixfox** [comment] 2023-09-17 15:19
Can't reproduce the issue anymore, closing.

**Closed by unixfox** 2023-09-17 15:19 UTC
Labels: bug
