### ISSUE TITLE
Resume playing

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#343] opened 2019-02-05 21:04 UTC
Partially watched videos can be marked differently, and you should be able to continue watching them.

**Comment by elypter** [comment] 2019-03-04 16:24
it would also be very helpful if it automatically asks you if you want to continue watching when reloading a video.

**Comment by dimqua** [comment] 2019-08-02 00:45
NewPipe recently got this feature!

**Comment by elypter** [comment] 2020-12-03 11:54
related #494

**Comment by unixfox** [comment] 2021-12-03 17:03
Duplicate of https://github.com/iv-org/invidious/issues/2024?

**Comment by unixfox** [comment] 2022-04-17 21:10
Duplicate of https://github.com/iv-org/invidious/issues/2024

**Closed by unixfox** 2022-04-17 21:10 UTC
Labels: enhancement
