### ISSUE TITLE
Error: Deutsche Welle channel 

### ISSUE THREAD

**Issue by Francomtois** [iv-org/invidious#2461] opened 2021-10-05 11:38 UTC
Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-10-05T11:30:12Z`
Route: `/channel/UCknLrEdhRCp1aegoMqRaCZg`
Version: `2021.10.03-347c189f @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'to_i'
  from src/invidious/helpers/utils.cr:120:64 in 'decode_length_seconds'
  from src/invidious/helpers/extractors.cr:77:113 in 'parse'
  from src/invidious/helpers/extractors.cr:40:16 in 'process'
  from src/invidious/helpers/extractors.cr:532:17 in 'extract_item'
  from src/invidious/helpers/extractors.cr:556:28 in 'extract_items'
  from src/invidious/helpers/helpers.cr:251:3 in 'extract_videos'
  from src/invidious/channels/videos.cr:72:19 in 'get_60_videos'
  from src/invidious/routes/channels.cr:38:22 in 'videos'
  from src/invidious/routes/channels.cr:5:5 in 'home'
  from src/invidious.cr:315:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2021-10-05 12:48
Duplicate of https://github.com/iv-org/invidious/issues/2449

**Closed by unixfox** 2021-10-05 12:48 UTC
