### ISSUE TITLE
[Bug] Bad link for collapser/expander in Reddit comments

### ISSUE THREAD

**Issue by k3lteris** [iv-org/invidious#3144] opened 2022-06-08 19:54 UTC
In the Reddit comments of the videos (click on "View Reddit comments" under a video), the [ - ] link to collapse a comment references void(0) instead of **javascript:void(0)**.

«a href="**void(0)**" data-onclick="toggle_parent"»[ - ]«/a»

These toogles lead to the main page of the instance of Invidious, instead of collapsing or expanding the comments.

**Comment by unixfox** [comment] 2022-06-08 20:00
Do you have javascript enabled?

**Comment by k3lteris** [comment] 2022-06-08 20:00
Javascript is enabled

**Comment by k3lteris** [comment] 2022-06-08 20:06
For example : https://yewtu.be/watch?v=05GPiKPylHY has Reddit comments.

Tested on a very new profile of Firefox 101.

![image](https://user-images.githubusercontent.com/93999015/172707191-2aa79717-9d98-42cc-9664-abb0c86e3c4f.png)

**Comment by unixfox** [comment] 2022-06-08 20:07
Duplicate of https://github.com/iv-org/invidious/issues/2412

**Closed by unixfox** 2022-06-08 20:07 UTC
Labels: bug
