### ISSUE TITLE
[Enhancement] Add `published` and `publishedText` String to `recommendedVideos`

### ISSUE THREAD

**Issue by SudoVanilla** [iv-org/invidious#4255] opened 2023-11-12 02:05 UTC
**Is your enhancement request related to a problem? Please describe.**
In Invidious's API, the date of recommended videos is not available as a string.
https://docs.invidious.io/api/#get-apiv1videosid

**Describe the solution you'd like**
Add `published` and `publishedText` to the `recommendedVideos` array for the Video ID. That way other frontends, such as PokeTube, can add the date to recommendations.

**Comment by RadoslavL** [comment] 2023-11-12 06:17
This is a duplicate of #3058. I am also currently working on this in #4149

**Closed** 2023-11-12 06:17 UTC
Labels: enhancement
