### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by prodphoenix** [iv-org/invidious#2279] opened 2021-07-27 00:24 UTC
**Describe the bug**
<-- no invidious instance i try will let me watch age restricted videos. this has never happened before and it's not because of my account, because i don't have one.-->

**Steps to Reproduce**
<-- Steps to reproduce the behavior:
1. song i was trying to watch the video for was 33rd blakk glass by city morgue,
2. click on the video
3. try to play it, it will not, wont even give you recommendations, only comments, which its usually the other way around so i dont know-->

**Screenshots**

**Additional context**
< using chrome and energy browser, which usually works perfectly, but neither are working on any instance i try
![Screenshot 2021-07-26 8 23 28 PM](https://user-images.githubusercontent.com/88010288/127075738-56715488-ed8b-4d18-bddd-809c95c94499.png)
-->
<- as you can see, no play button, nothing happens when i click, this happens on every video i try that is age restricted->

**Comment by syeopite** [comment] 2021-07-27 00:32
Duplicate of #2189

**Closed by syeopite** 2021-07-27 00:32 UTC
Labels: bug
