### ISSUE TITLE
[Feature request] Removing All UI from Embeds

### ISSUE THREAD

**Issue by alflennik** [iv-org/invidious#4000] opened 2023-07-23 16:31 UTC
**Is your feature request related to a problem? Please describe.**

A big issue when developing an experience built on top of YouTube is that, while there is a pretty good API for controlling the player, there is no way to remove the YouTube UI, A.K.A. the controls. This can be a pretty big issue, and here's just one example of the problem: I'm building a music player for music videos, and a feature I want to implement is normalizing the audio, because some songs sound super loud (looking at you, k-pop). The moment someone moves the YouTube volume to 100%, as a developer I lose the ability to normalize the audio. I'd like to build a custom audio control that leaves a certain amount of wiggle room at the top so I can raise and lower the volume slightly in the background.

**Describe the solution you'd like**

If there was an option to disable the embedded UI, along with an iframe API controlling the stuff like volume, play pause, etc. that need to be controlled, that would allow rich experiences to be built on top of YouTube.

**Describe alternatives you've considered**

I considered building an electron app just so I could inject some JS and CSS into the embed for hiding the controls, but then my experience won't work in a browser. I also considered writing a browser extension. In both cases it puts up big barriers that would make my app harder to use. I'm currently offering just the second-class experience.

**Additional context**

Thanks for working on this project.

**Comment by unixfox** [comment] 2023-07-23 17:48
duplicate of https://github.com/iv-org/invidious/issues/3705

**Closed by unixfox** 2023-07-23 17:48 UTC
Labels: feature-request
