### ISSUE TITLE
Unexpected char '<' at 1:1 (JSON::ParseException)

### ISSUE THREAD

**Issue by SpiCy0** [iv-org/invidious#1693] opened 2021-01-22 15:12 UTC
Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-01-22T15:10:00Z`
Route: `/channel/UCxLIJccyaRQDeyu6RzUsPuw`
Version: `2021.01.13-c7e65ce @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1715:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

Here ya go, I'm not exactly tech-savvy enough to know what this means, at least not in this field.

**Comment by SpiCy0** [comment] 2021-01-22 15:14
Looks like it happens on every channel

**Comment by hackerncoder** [comment] 2021-01-22 15:19
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Comment by SpiCy0** [comment] 2021-01-22 15:29
Like I said, I'm not the most tech-savvy, but just taking a look at the backtrace for #1637 vs the backtrace that I'm getting, they are significantly different.

**Comment by SpiCy0** [comment] 2021-01-22 20:27
It went away, and I haven't been able to recreate it.

**Closed** 2021-01-23 17:52 UTC
Labels: duplicate
