### ISSUE TITLE
[Enhancement] Add default playback speed options

### ISSUE THREAD

**Issue by Opening-Button-8988** [iv-org/invidious#3502] opened 2022-12-17 11:44 UTC
**Is your enhancement request related to a problem? Please describe.**
I would love to have more granular control over video playback speed, both for the current video and the default options.

**Describe the solution you'd like**
1. The option to specify the exact playback speed I want, both in the default preferences, as well as in the current video, anywhere between 0.1 and, well, whatever the maximum speed the browser allows (10x would probably be plenty). Keyboard shortcuts for adjusting the speed might be useful too, assuming they're not already present (I haven't checked).

**Describe alternatives you've considered**
I am able to adjust video playback speeds on both Youtube, as well as Invidious, using the following command in Console in Firefox developer settings: `$('video').playbackRate=2`

I think this command works in other sites too. I tried editing the player.js file in Invidious and I added an option in the list of possible playback rates, but it didn't work and I don't know why (I'm not a programmer).

**Additional context**
This document may or may not be useful as context: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/defaultPlaybackRate

It might be helpful to add that I make use of video playback speed very often and I couldn't imagine not having the ability to change video speeds. I watch most videos at 2x speed or above, and I often use speeds around 2x to 4x. There's a pretty big difference between say 2.7x and 3x, and that granular control makes all the difference. For anyone who doesn't even go above 1x speed: how do you have any time to get anything done in the day?

**Comment by Opening-Button-8988** [comment] 2022-12-17 11:45
Does anyone know how I could possibly add more default options to my Invidious instance? Running the above command every time I want to change the speed is tiresome.

**Comment by unixfox** [comment] 2022-12-18 11:00
Duplicate of https://github.com/iv-org/invidious/issues/3105

**Comment by Opening-Button-8988** [comment] 2022-12-19 03:55
> Duplicate of #3105

How is this a duplicate? I read the post and it's described as a bug related to video playback speed and volume. My post is a suggestion that is definitely not identical to that bug.

**Comment by unixfox** [comment] 2022-12-19 05:55
Oops sorry it's a duplicate of this one instead: https://github.com/iv-org/invidious/issues/533

**Closed by unixfox** 2022-12-19 05:55 UTC
Labels: enhancement
