### ISSUE TITLE
[Bug] Slow performance on Intel CPU

### ISSUE THREAD

**Issue by Ian-Drunkenson** [iv-org/invidious#3823] opened 2023-05-28 05:05 UTC
Invidious used to run quite well but all of a sudden videos are hardly loaded and it became inoperable.

Log:

> [production] Invidious is ready to lead at http://0.0.0.0:3000
2023-05-28 04:47:13 UTC [info] jobs: running ClearExpiredItems job
2023-05-28 04:47:17 UTC [info] jobs: ClearExpiredItems done.
2023-05-28 04:47:41 UTC [error] RefreshChannelsJob: UCWidwHMq-wJJOQ4ESNo-RdA : Deleted or invalid channel
2023-05-28 04:47:47 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 4123.65ms
2023-05-28 04:47:58 UTC [error] RefreshChannelsJob: UCQSoDH9eq-Px8G04xTvw-1g : Index out of bounds
2023-05-28 04:47:58 UTC [error] RefreshChannelsJob: UCQSoDH9eq-Px8G04xTvw-1g fiber : backing off for 00:02:00s
2023-05-28 04:48:17 UTC [info] 302 GET / 14.38ms
2023-05-28 04:48:17 UTC [info] 200 GET /feed/subscriptions 102.35ms
2023-05-28 04:48:17 UTC [info] 200 GET /js/watched_widget.js 677.28µs
2023-05-28 04:48:17 UTC [info] 200 GET /js/watched_indicator.js 169.1µs
2023-05-28 04:48:22 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 4334.65ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/7RRaRrra9YU/mqdefault.jpg 24610.92ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/4uoOG3iCFzI/mqdefault.jpg 20356.64ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/oZNKPslyprA/mqdefault.jpg 16315.51ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/ToxSvnab6FY/mqdefault.jpg 12329.71ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/IorNDZTTZC8/mqdefault.jpg 8249.64ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/h8OzyuQ-7Uk/mqdefault.jpg 4178.49ms
2023-05-28 04:48:42 UTC [info] 200 GET /feed/subscriptions 166.46ms
2023-05-28 04:48:42 UTC [info] 200 GET /apple-touch-icon.png?v=381a0e3 243.74µs
2023-05-28 04:48:43 UTC [info] 200 GET /api/v1/auth/subscriptions?fields=authorId 31.03ms
2023-05-28 04:49:04 UTC [info] 200 GET /vi/7RRaRrra9YU/mqdefault.jpg 20400.1ms
2023-05-28 04:49:04 UTC [info] 200 GET /vi/4uoOG3iCFzI/mqdefault.jpg 16327.33ms
2023-05-28 04:49:20 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 16337.02ms
2023-05-28 04:49:20 UTC [info] 200 GET /vi/h8OzyuQ-7Uk/mqdefault.jpg 16337.33ms
2023-05-28 04:49:32 UTC [info] 200 GET /vi/oZNKPslyprA/mqdefault.jpg 40708.63ms
2023-05-28 04:49:32 UTC [info] 200 GET /vi/ToxSvnab6FY/mqdefault.jpg 36645.47ms
2023-05-28 04:49:36 UTC [info] 200 GET /vi/IorNDZTTZC8/mqdefault.jpg 36658.21ms
2023-05-28 04:49:44 UTC [info] 200 GET /vi/AvH43hMTSMY/mqdefault.jpg 36569.58ms
2023-05-28 04:49:45 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 12238.14ms
2023-05-28 04:49:49 UTC [info] 200 GET /vi/8R7oCror4tA/mqdefault.jpg 16298.96ms
2023-05-28 04:50:01 UTC [info] 200 GET /vi/7qWaMX_9MwA/mqdefault.jpg 36703.78ms
2023-05-28 04:50:17 UTC [info] 200 GET /vi/vun1HL5EOcA/mqdefault.jpg 32526.18ms
2023-05-28 04:50:17 UTC [info] 200 GET /vi/NTg2ts5TwLM/mqdefault.jpg 40690.38ms
2023-05-28 04:50:29 UTC [info] 200 GET /vi/I1aWvqlK1E4/mqdefault.jpg 40651.76ms
2023-05-28 04:50:29 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 12328.35ms
2023-05-28 04:50:29 UTC [info] 200 GET /vi/u9OQMBPrFgI/mqdefault.jpg 36728.11ms
2023-05-28 04:50:29 UTC [info] 200 GET /vi/7L5ryfE4plM/mqdefault.jpg 12341.38ms
2023-05-28 04:50:29 UTC [info] 200 GET /vi/WcDahKG4j9Q/mqdefault.jpg 24529.82ms
2023-05-28 04:50:29 UTC [info] 200 GET /vi/kkm9aWOppT0/mqdefault.jpg 8302.96ms
2023-05-28 04:50:30 UTC [error] RefreshChannelsJob: UCVLD8m4YCxQyb2eUTMa9BGQ : Index out of bounds
2023-05-28 04:50:30 UTC [error] RefreshChannelsJob: UCVLD8m4YCxQyb2eUTMa9BGQ fiber : backing off for 00:04:00s

Compose:

`version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    container_name: invidious
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    container_name: invidious-db
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
`

**Comment by unixfox** [comment] 2023-05-28 09:11
Do you hourly restart it?

**Comment by Ian-Drunkenson** [comment] 2023-05-28 12:15
yes

**Comment by unixfox** [comment] 2023-05-28 12:39
People have reported the same issue on ARM: https://github.com/iv-org/invidious/issues/3740

Did you try if it is also slow with a freshly database install?

**Comment by Ian-Drunkenson** [comment] 2023-05-29 05:45
Yes, purged old installation and installed it fresh fron the scratch and still the same issue.

**Comment by unixfox** [comment] 2023-05-29 06:41
Are you sure something isn't wrongly configured? Did you try on another Linux server?

**Comment by Ian-Drunkenson** [comment] 2023-05-29 08:35
no,not yet. but I have some other services running on the server and thy work all fine. But Ill give it a try and will setup another server ant try it again.

**Comment by Ian-Drunkenson** [comment] 2023-05-29 15:25
I have set up an Ubuntu server and now it works again. Is it possible that the use proxy option in the settigs could cuase such a behavior? Do you know if Invidious uses the LAN's own DNS servers or others?

**Comment by unixfox** [comment] 2023-05-29 22:34
Invidious may not fallback easily to the second DNS server if the first one is down.

Yeah make sure everything is working well DNS wise. The only way is to temporarily test with public DNS servers.

**Comment by Ian-Drunkenson** [comment] 2023-05-30 05:51
so far it work ok with the new server. cant figuere out what was wrong on the old one. thx anyway for support.

**Comment by SamantazFox** [comment] 2023-05-30 18:01
Closing as the problem seem to be solved.

---

For anyone else landing here:
the low response time for static files but high response time for external resources such as thumbnails indicates that the problem is related to be network-related (likely DNS) and not caused by the CPU/RAM.

```
2023-05-28 04:48:17 UTC [info] 200 GET /js/watched_widget.js 677.28µs
2023-05-28 04:48:17 UTC [info] 200 GET /js/watched_indicator.js 169.1µs
2023-05-28 04:48:42 UTC [info] 200 GET /vi/4uoOG3iCFzI/mqdefault.jpg 20356.64ms
2023-05-28 04:48:42 UTC [info] 200 GET /vi/oZNKPslyprA/mqdefault.jpg 16315.51ms
```

**Closed by SamantazFox** 2023-05-30 18:01 UTC
Labels: bug
