### ISSUE TITLE
Bug when opening channel

### ISSUE THREAD

**Issue by aaronkurz** [iv-org/invidious#1659] opened 2021-01-12 10:25 UTC
I tried to click on a channel name to open the channel and the site said: "Looks like you've found a bug in Invidious. Please open a new issue on GitHub and include the following text in your message:"

```
Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-01-12T10:23:49Z`
Route: `/channel/UCiTjCIT_9EXV1Wp1cY0zaUA`
Version: `2020.12.09-2349a6a @ master`
<details>
<summary>Backtrace</summary>
<p>
   

Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1938:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from src/invidious/helpers/logger.cr:17:33 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???

</p>
</details>
```

**Comment by hackerncoder** [comment] 2021-01-12 10:30
This appears to be a duplicate of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

Duplicate of #1637

**Closed** 2021-01-12 13:53 UTC
Labels: duplicate
