### ISSUE TITLE
Channels / Playlists not working properly

### ISSUE THREAD

**Issue by CatsLover2006** [iv-org/invidious#1496] opened 2020-11-27 15:24 UTC
This is a issue with the build on invidious.kavin.rocks (0.20.1-99ba987), I have checked other instances and the same issue has occurred. Whenever I look up a channel or playlist, I get “looks like you found a bug in Invidious!”. I don’t know what causes it, but outside of this one thing, Invidious works perfectly on all my clients (even an iOS 6 iPod; good job with legacy compatibility).
Edit: sometimes it loads, sometimes it doesn’t (it loads the most often on the instance I picked)

**Comment by hackerncoder** [comment] 2020-11-27 16:09
The channels bug is known: #1494

**Comment by Coaggly** [comment] 2020-11-28 18:00
This is happening to me too. Yewtube is still not displaying some channels.  https://vid.encryptionin.space is saying 'Read timed out ', yewtube is saying ' Nil assertion failed '.

**Comment by Perflyst** [comment] 2020-11-28 21:04
Duplicate of  #1494

**Closed by Perflyst** 2020-11-28 21:04 UTC
