### ISSUE TITLE
Missing hash key: "navigationEndpoint" (KeyError)

### ISSUE THREAD

**Issue by TechD123** [iv-org/invidious#2737] opened 2021-12-24 15:19 UTC
Date: `2021-12-24T15:11:38Z`
Route: `/search?q=Facebook+requiem`
Version: `2021.12.24-b88da30 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/lib/crystal/core/json/any.cr:100:0 in '[]'
  from /usr/lib/crystal/core/json/any.cr:102:10 in 'dig'
  from /usr/lib/crystal/core/json/any.cr:215:3 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:253:41 in 'process'
  from src/invidious/yt_backend/extractors.cr:561:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:592:28 in 'extract_items'
  from src/invidious/search.cr:36:11 in 'search'
  from src/invidious/search.cr:227:20 in 'search'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by KeshaunRocks** [comment] 2021-12-25 12:03
Please see #2530

**Comment by unixfox** [comment] 2021-12-29 09:25
Duplicate of https://github.com/iv-org/invidious/issues/2530

**Closed by unixfox** 2021-12-29 09:25 UTC
