### ISSUE TITLE
[Bug] Audio-only mode not working on livestreams

### ISSUE THREAD

**Issue by carlo711** [iv-org/invidious#3468] opened 2022-12-04 12:06 UTC
**Describe the bug**
Audio-only mode not working on livestreams

**Steps to Reproduce**
Open stream for example lofi hiphop
Click on the headphones icon next to the title
Audio cuts off/stops

**Comment by SamantazFox** [comment] 2022-12-04 18:33
Duplicate of #597

**Closed by SamantazFox** 2022-12-04 18:33 UTC
Labels: bug
