### ISSUE TITLE
[Bug] Config.check_tables failed to parse true as Bool

### ISSUE THREAD

**Issue by lzap** [iv-org/invidious#4962] opened 2024-09-29 07:33 UTC
**Describe the bug**
The environmental parsed does not work with `INVIDIOUS_CHECK_TABLES=true`

**Steps to Reproduce**
1. Create `INVIDIOUS_CHECK_TABLES=true` env variable
2. Start the server
3. Config.check_tables failed to parse true as Bool

**Logs**
The error message appears and the process exits with 1.

I tried to pass `1` in as well but this appears to be YAML parser so I do not understand what is wrong here. I am working on Podman Quadlet setup where the only reasonable configuration is via environmental variables. Thanks.

**Comment by Fijxu** [comment] 2024-09-30 02:01
What error do you exactly get? I can use `INVIDIOUS_CHECK_TABLES=true|false` just fine.

![image](https://github.com/user-attachments/assets/116c5697-c8a8-418d-bad9-86ec91d256ec)

**Comment by unixfox** [comment] 2024-09-30 20:54
All of these custom environment variable has been tested in the past, they work great.

Closing as I can't reproduce the issue.

**Closed by unixfox** 2024-09-30 20:54 UTC
Labels: bug

**Comment by lzap** [comment] 2024-10-01 08:23
Apologies, hmmm, not sure what is wrong on my side.
