### ISSUE TITLE
[Feature request] "Channels" link missing from channel page

### ISSUE THREAD

**Issue by FavoritoHJS** [iv-org/invidious#4592] opened 2024-04-21 17:37 UTC
**Describe the bug**
The "channels" link in a channel's page is missing since a channel page layout change a few weeks(?) ago.
However, the content there still exists, usually under the "featured channels" section in youtube, usually at the very end of the channel page, though sometimes elsewhere.

**Steps to Reproduce**
1. Go to a channel with featured channels, such as [Louis Rossmann's](https://redirect.invidious.io/channel/UCl2mFZoRqjw_ELax4Yisf6w)
2. Notice there isn't a "Channels" link
3. Open the same channel in [Youtube](https://www.youtube.com/channel/UCl2mFZoRqjw_ELax4Yisf6w)
4. Notice there is a channel under the "Associated channels" section.

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/69703458/6891bcd4-b399-4477-bcaa-154f5905adcc)

**Comment by SamantazFox** [comment] 2024-04-21 18:58
Duplicate of https://github.com/iv-org/invidious/issues/4275

**Closed by SamantazFox** 2024-04-21 18:58 UTC
Labels: feature-request
