### ISSUE TITLE
Parse error when loading channel page

### ISSUE THREAD

**Issue by fchaix** [iv-org/invidious#1692] opened 2021-01-22 04:36 UTC
This is a fresh installation of Invidious, and so far, I could watch a few videos and subscribe a few channels without problems.
But this morning, I get this error, when I try get to any channel page : 

```html
Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-01-22T04:29:13Z`
Route: `/channel/UCR9Gcq0CMm6YgTzsDxAxjOQ`
Version: `2021.01.21-a1aa40f @ master`
<details>
<summary>Backtrace</summary>
<p>
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/lib/crystal/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/lib/crystal/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/lib/crystal/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/lib/crystal/slice.cr:229:5 in 'next_token'
  from ../../../usr/lib/crystal/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1715:20 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/lib/crystal/http/server.cr:498:5 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ???
</p>
</details>
```

**Comment by hackerncoder** [comment] 2021-01-22 07:43
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-01-22 09:26 UTC
