### ISSUE TITLE
[Bug] Direct link ain't working

### ISSUE THREAD

**Issue by qdhj** [iv-org/invidious#4875] opened 2024-08-24 11:17 UTC
**Describe the bug**
Shortened "direct link" that you get pressing on "share" -> "direct link" (https://yewtu.be/LXb3EKWsInQ) redirects you on the main invidous page (instead of https://yewtu.be/watch?v=LXb3EKWsInQ).

This error is in every browser I tried (Brave, Mullvad, Safari), both in Windows and iOS.
Still, for some reason embed link (https://yewtu.be/embed/LXb3EKWsInQ) works fully well.

![image](https://github.com/user-attachments/assets/e3bae58c-e50e-48bd-9ac7-64f5dd015861)

![image](https://github.com/user-attachments/assets/88179ec1-e094-4b8b-a2b3-56e450cb5242)

**Comment by absidue** [comment] 2024-08-24 11:53
Duplicate of #3933

**Closed** 2024-08-24 16:08 UTC
Labels: bug
