### ISSUE TITLE
[Bug] Trending endpoint of API is returning an error

### ISSUE THREAD

**Issue by keshavbhatt** [iv-org/invidious#1935] opened 2021-03-26 19:11 UTC
**Describe the bug**
The trending endpoint of API is returning an error when the type parameter is passed to it.

**Steps to Reproduce**
1- Go to https://invidious.snopyta.org/api/v1/trending?region=us&type=music
2- The API returning error message: Missing hash key

Full response:
`{"error":"Missing hash key: \"subMenu\"","errorBacktrace":"Missing hash key: \"subMenu\" (KeyError)\n  from /usr/share/crystal/src/hash.cr:1027:11 in '[]'\n  from /usr/share/crystal/src/json/any.cr:102:7 in '[]'\n  from src/invidious/trending.cr:15:12 in 'fetch_trending'\n  from src/invidious.cr:2214:22 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:212:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:17:35 in 'call'\n  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'\n  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'\n  from /usr/share/crystal/src/http/server.cr:468:13 in '->'\n  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from /usr/share/crystal/src/fiber.cr:92:34 in '->'\n  from ???\n"}`

**Comment by hackerncoder** [comment] 2021-03-26 19:12
This appears to be a duplicate of #1755. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-03-26 19:12 UTC
Labels: duplicate
