### ISSUE TITLE
[Bug] Live streams not loading on Yunohost Invidious version

### ISSUE THREAD

**Issue by saebaryo-xyz** [iv-org/invidious#3813] opened 2023-05-20 07:01 UTC
**Describe the bug**

Hello,

First of all, apologies if I am in the wrong place to report.

I've recently installed Invidious app on Yunohost and the only issue I've noticed is that Live Streams do not load.

I've read somewhere that it might be a reverse proxy config issue.

If that is the case indeed, what would be the name of the file I need to edit and what could be the correct config?

If not this issue what might be the problem?

Thank you everyone in advance!

**Steps to Reproduce**
<!-- Steps to reproduce the behavior:
1. Go to mytube.yorili.com
2. Search for any Live
3. Click Play
4. Loads indefinitely

**Additional context**
On Yunohost Debian based server.
Clients used Chrome based and Firefox based.

**Comment by absidue** [comment] 2023-05-20 07:27
Duplicate of #3811

**Comment by saebaryo-xyz** [comment] 2023-05-20 07:30
> Duplicate of #3811

My apologies for that.
However, in my case it is not on  Docker but Yunohost and I do not get any error.

**Comment by unixfox** [comment] 2023-05-20 08:23
- we do not officially support yunohost so please open the issue on yunohost issue tracker. Or don't use yunohost and install invidious through the official documentation then you may expect some support from us

- and it's a duplicate of #3811

**Closed** 2023-05-20 08:24 UTC
Labels: duplicate, invalid
