### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 3tyh86qvt** [iv-org/invidious#1683] opened 2021-01-19 14:26 UTC
Looks like you've found a bug in Invidious [when clicking on this link https://yewtu.be/watch?v=vBHild0PiTE]. Please open a new issue on GitHub and include the following text in your message: 

Title: `Unterminated string at 1:180547 (JSON::ParseException)`
Date: `2021-01-19T14:24:23Z`
Route: `/watch?v=vBHild0PiTE`
Version: `-c7e65ce @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unterminated string at 1:180547 (JSON::ParseException)
  from ../usr/lib/crystal/json/lexer.cr:371:7 in 'raise'
  from ../usr/lib/crystal/json/lexer/string_based.cr:21:12 in 'consume_string'
  from ../usr/lib/crystal/json/lexer.cr:61:37 in 'next_token'
  from ../usr/lib/crystal/json/parser.cr:108:11 in 'next_token'
  from ../usr/lib/crystal/json/parser.cr:83:11 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:49:18 in 'parse_array'
  from ../usr/lib/crystal/json/parser.cr:33:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:49:18 in 'parse_array'
  from ../usr/lib/crystal/json/parser.cr:33:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:85:19 in 'parse_object'
  from ../usr/lib/crystal/json/parser.cr:35:7 in 'parse_value'
  from ../usr/lib/crystal/json/parser.cr:13:12 in 'parse'
  from ../usr/lib/crystal/json.cr:131:5 in 'parse'
  from src/invidious/videos.cr:821:16 in 'extract_polymer_config'
  from src/invidious/videos.cr:965:3 in 'fetch_video'
  from src/invidious/videos.cr:941:17 in 'get_video'
  from src/invidious/videos.cr:932:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from src/invidious.cr:316:1 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:19:35 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/lib/crystal/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/lib/crystal/http/server.cr:513:5 in 'handle_client'
  from ../usr/lib/crystal/http/server.cr:468:13 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ../usr/lib/crystal/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-01-19 15:24
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-01-19 15:53 UTC
