### ISSUE TITLE
Nil assertion failed

### ISSUE THREAD

**Issue by gps05** [iv-org/invidious#1505] opened 2020-11-30 18:03 UTC
Date: `2020-11-30T17:51:05Z`
Route: `/channel/UCSvpaSUvYp35Nu75yWtyPEw`
Version: `0.20.1-78ae9ff @ master`
Backtrace: 
```
Nil assertion failed (NilAssertionError)
  from ../../../usr/share/crystal/src/nil.cr:106:5 in 'not_nil!'
  from src/invidious/channels.cr:805:16 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../../../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../../../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```

**Comment by tirz** [comment] 2020-11-30 18:11
Duplicate of https://github.com/iv-org/invidious/issues/1494

**Closed** 2020-11-30 18:39 UTC
Labels: duplicate
