### ISSUE TITLE
[Bug] First link on search results for "The Trials of Life Talking to Strangers"

### ISSUE THREAD

**Issue by enzotib** [iv-org/invidious#4648] opened 2024-04-26 15:22 UTC
1. Go to page i.devol.it
2. Search for "The Trials of Life Talking to Strangers"
3. Click on the first result, that should be https://i.devol.it/watch?v=fcXC0s1XMps
4. Error page shown

Log:

Title: `The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)`
Date: `2024-04-26T15:21:20Z`
Route: `/watch?v=fcXC0s1XMps`
Version: `2024.03.31-08390acd @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
The video returned by YouTube isn't the requested one. (Android client) (VideoNotAvailableException)
  from src/invidious/videos/parser.cr:155:5 in 'try_fetch_streaming_data'
  from src/invidious/videos/parser.cr:112:10 in 'extract_video_info:video_id'
  from /usr/share/crystal/src/hash.cr:1299:13 in 'fetch_video'
  from src/invidious/videos.cr:379:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:55:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:506:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2024-04-26 15:46
Duplicate of #4584

**Closed** 2024-04-26 15:46 UTC
Labels: bug
