### ISSUE TITLE
[Bug] When video failed to load it keeps try to load endlessly.

### ISSUE THREAD

**Issue by Feodor2** [iv-org/invidious#4865] opened 2024-08-21 06:52 UTC
**Describe the bug**
When video failed to load it keeps try to load endlessly, and this breaks to switch for other format.
Please limit number of attempts to the sane value, for example 5.

**Steps to Reproduce**
Take old pc like cor2duo or amd450, thats why I use Invidious there.
Try open video on the instance where the default format set to av1 or else not compatible with old systems.
Try switch for other format.

**Logs**

**Screenshots**

**Additional context**

**Comment by syeopite** [comment] 2024-08-21 06:54
Duplicate of #3632

**Closed** 2024-08-21 06:54 UTC
Labels: bug
