### ISSUE TITLE
[Bug] Missing JSON element "results" (BrokenTubeException)

### ISSUE THREAD

**Issue by kitl000** [iv-org/invidious#3309] opened 2022-09-12 18:52 UTC
**Logs**

**Screenshots**

**Additional context**

**Comment by kitl000** [comment] 2022-09-12 18:53
Title: `Missing JSON element "results" (BrokenTubeException)`
Date: `2022-09-12T18:52:04Z`
Route: `/watch?v=ufmXepybSng`
Version: `2022.09.08-805be880 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "results" (BrokenTubeException)
  from /usr/share/crystal/src/indexable.cr:73:26 in 'parse_video_info'
  from src/invidious/videos.cr:926:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:1129:10 in 'fetch_video'
  from src/invidious/videos.cr:1109:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-09-12 20:57
Will likely be fixed by https://github.com/iv-org/invidious/pull/3238

**Comment by SamantazFox** [comment] 2022-09-12 20:58
Closing as a duplicate of #3014

**Closed by SamantazFox** 2022-09-12 20:58 UTC
Labels: bug
