### ISSUE TITLE
[Bug] Unexpected '?' in line 1, column 1 (JSON :: ParseException)

### ISSUE THREAD

**Issue by skrandeks-kali** [iv-org/invidious#2687] opened 2021-12-01 10:36 UTC
Title: `Unexpected sign? ' in line 1, column 1 (JSON :: ParseException) `
 Date: `2021-12-01T10: 31: 22Z`
 Route: `/search?q=pubg+mob+%D0%BD%D0%B0%D1%80%D0%B5%D0%B7%D0%BA%D0%B8+`
 Version: `2021.11.29-0343b32f @ master`
 <details>
 <summary> Backtrace </summary>
 <p>
   
 ```
 Unexpected '?' in line 1, column 1 (JSON :: ParseException)
   из /usr/share/crystal/src/json/lexer.cr:331:7 в 'поднять'
   из /usr/share/crystal/src/json/lexer.cr:327:5 в 'unknown_char'
   из /usr/share/crystal/src/json/lexer.cr:326:11 в 'unknown_char'
   из /usr/share/crystal/src/slice.cr:213:5 в 'next_token'
   из /usr/share/crystal/src/json/parser.cr:13:12 в '_post_json'
   из src / invidious / search.cr: 36: 11 в поиске
   из src / invidious / search.cr: 232: 20 в поиске
   из /usr/share/crystal/src/primitives.cr:266:3 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из lib / kemal / src / kemal / filter_handler.cr: 21: 7 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из src / invidious / helpers / static_file_handler.cr: 167: 15 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call'
   из /usr/share/crystal/src/http/server/handler.cr:28:7 в 'call_next'
   из lib / kemal / src / kemal / init_handler.cr: 12: 7 в 'процессе'
   из /usr/share/crystal/src/http/server.cr:500:5 в '->'
   из /usr/share/crystal/src/primitives.cr:266:3 в 'run'
   из ???
 ```
 </p>
 </details>

**Comment by unixfox** [comment] 2021-12-01 10:41
Can you paste the keyword that you used when searching on invidious?

**Comment by SamantazFox** [comment] 2021-12-01 16:09
Duplicate of #2612

**Closed by SamantazFox** 2021-12-01 16:09 UTC
Labels: bug

**Comment by skrandeks-kali** [comment] 2021-12-22 07:27
Kali linux

ср, 1 дек. 2021 г., 15:41 Émilien Devos ***@***.***>:
