### ISSUE TITLE
[Bug] Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)

### ISSUE THREAD

**Issue by 1raj1** [iv-org/invidious#2884] opened 2022-02-09 14:42 UTC
**Describe the bug**

When trying to play video, error message appeared (quoted in "Logs" section).

**Steps to Reproduce**

1. Go to https://yewtu.be/watch?v=0Fnp5tnZkJg (or the same video on other Invidious instance).

**Logs**

Title: `Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)`
Date: `2022-02-09T14:27:30Z`
Route: `/watch?v=0Fnp5tnZkJg`
Version: `2022.02.09-4272ee7 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element &quot;twoColumnWatchNextResults&quot; (BrokenTubeException)
  from /usr/lib/crystal/core/json/any.cr:102:10 in &#39;extract_video_info:video_id&#39;
  from /usr/lib/crystal/core/hash.cr:1139:13 in &#39;get_video:region&#39;
  from src/invidious/routes/watch.cr:63:15 in &#39;handle&#39;
  from lib/kemal/src/kemal/route.cr:13:9 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from src/invidious/helpers/static_file_handler.cr:167:15 in &#39;call&#39;
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call&#39;
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in &#39;call_next&#39;
  from lib/kemal/src/kemal/init_handler.cr:12:7 in &#39;process&#39;
  from /usr/lib/crystal/core/http/server.cr:500:5 in &#39;-&gt;&#39;
  from /usr/lib/crystal/core/primitives.cr:266:3 in &#39;run&#39;
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in &#39;??&#39;
```
</p>
</details>

**Screenshots**

**Additional context**

Firefox 96.0
Ubuntu 20.04

**Comment by unixfox** [comment] 2022-02-09 14:44
Duplicate of https://github.com/iv-org/invidious/issues/2877

**Closed by unixfox** 2022-02-09 14:44 UTC
Labels: bug
