### ISSUE TITLE
[Enhancement] Add author verified status to video and popular API responses

### ISSUE THREAD

**Issue by Benjababe** [iv-org/invidious#4112] opened 2023-09-20 07:11 UTC
**Is your enhancement request related to a problem? Please describe.**

Tried checking for `authorVerified` using 2 of the API endpoints
- `api/v1/videos/:vid_id/`
- `api/v1/popular/`

Both did not return it whereas endpoints below do return `authorVerified`.
- `api/v1/channels/:channel_id/`
- `api/v1/search/`

Is it possible to include it in the video and popular API response if it isn't too much of a hassle? Thanks

**Describe the solution you'd like**

Include `authorVerified` next to `author` and inside `recommendedVideos` of the [video](https://docs.invidious.io/api/#get-apiv1videosid) and [popular](https://docs.invidious.io/api/#get-apiv1popular) API like the endpoints that support it.

**Describe alternatives you've considered**
Not including it.

**Comment by syeopite** [comment] 2023-09-22 01:33
Duplicate of #3323

**Closed** 2023-09-22 01:33 UTC
Labels: enhancement
