### ISSUE TITLE
can't open shorts[BUG]

### ISSUE THREAD

**Issue by goldenfreddyv** [iv-org/invidious#3662] opened 2023-02-26 09:15 UTC
Title: `Missing JSON element "reelPlayerHeaderSupportedRenderers" (BrokenTubeException)`
Date: `2023-02-26T09:09:54Z`
Route: `/channel/UCqFXLcQo_gG__MUxRrrXKag/shorts`
Version: `2023.02.22-0995e04 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "reelPlayerHeaderSupportedRenderers" (BrokenTubeException)
  from src/invidious/channels/videos.cr:159:9 in 'get_shorts'
  from src/invidious/routes/channels.cr:60:32 in 'shorts'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2023-02-26 09:18
Duplicate of https://github.com/iv-org/invidious/issues/3637

**Closed by unixfox** 2023-02-26 09:18 UTC
Labels: bug
