### ISSUE TITLE
[Bug] DB::PoolRetryAttemptsExceeded after login

### ISSUE THREAD

**Issue by mdespuits** [iv-org/invidious#2808] opened 2022-01-10 14:43 UTC
**Describe the bug**
After initially logging in, I do not see my feed. I get a bug report page.

**Steps to Reproduce**

1. Go to `/`
2. Login in with your credentials
3. See error (the same error occurred with an empty `referer` query parameter

**Logs**
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2022-01-10T14:38:33Z`
Route: `/login?referer=%2Ffeed%2Fpopular&type=invidious`
Version: `2022.01.09-d928b9ea @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_one?:as'
  from src/invidious/routes/login.cr:332:7 in 'login'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Screenshots**

**Additional context**
 - Browser (if applicable): Firefox (also occurred in Fluid.app)
 - OS (if applicable): macOS

**Comment by unixfox** [comment] 2022-01-10 14:50
Duplicate of https://github.com/iv-org/invidious/issues/1582
Please use another instance from https://api.invidious.io

**Closed by unixfox** 2022-01-10 14:50 UTC
Labels: bug
