### ISSUE TITLE
[Enhancement] Better UI

### ISSUE THREAD

**Issue by tamimology** [iv-org/invidious#4557] opened 2024-04-03 01:13 UTC
I came to see another UI, which is based on Invidious, why not combine both works and have it in 1 image? This will be easier to install and configure

check `wardpearce/materialious`

**Comment by unixfox** [comment] 2024-04-03 02:55
Duplicate of https://github.com/iv-org/invidious/issues/1950

**Closed** 2024-04-03 02:55 UTC
Labels: enhancement
