### ISSUE TITLE
[Bug] Control bar doesn't dissapear after changing video options

### ISSUE THREAD

**Issue by PORTB** [iv-org/invidious#3000] opened 2022-03-31 10:11 UTC
**Describe the bug**

After changing video quality options, the control bar does not disappear and stays visible forever. I am using the "invidious" player style, and I am using sponsorblock. 
**Steps to Reproduce**

1. Hover over the control bar and change the video quality (I am using DASH)
2. Move your mouse away
3. It will not disappear 

**Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/34615701/161031795-5740b787-bc34-4037-acc9-6c2337013219.png)

**Additional context**

Browser: Firefox 96.0.3-1 64 bit
OS: Windows 10 64 bit

**Comment by unixfox** [comment] 2022-03-31 11:18
Duplicate of https://github.com/iv-org/invidious/issues/1263

**Closed by unixfox** 2022-03-31 11:18 UTC
Labels: bug
