### ISSUE TITLE
[Bug] All the invidious instance and the video itself isn't working.

### ISSUE THREAD

**Issue by ProfessionalCoderAtGames** [iv-org/invidious#4614] opened 2024-04-26 03:17 UTC
I tried everything it told me to do. By refreshing it, using another instance, Reading the frequently asked questions and it hasn't been working! I don't know what else to use to watch videos since YouTube is saying that my account isn't working.

**Comment by animegrafmays** [comment] 2024-04-26 03:22
this is a duplicate of #4584

**Comment by gmestanley** [comment] 2024-04-26 03:30
This time however, it's consistent. Before just now, it would appear a few times until you refreshed the page enough that it would eventually disappear. And even before _that_, it would only appear occasionally and usually actually be momentary.

**Comment by animegrafmays** [comment] 2024-04-26 03:31
that is reflected in that issue

**Closed** 2024-04-26 04:18 UTC
Labels: bug

**Comment by W9JYD** [comment] 2024-09-16 06:21
This is nonsense. Lazy ass developer.

**Comment by HateHigsBoson** [comment] 2024-09-16 06:55
> This is nonsense. Lazy ass developer.

You absolute stupid fucking nigger piece of shit, you don't know the first fucking thing about why this is broken. The kikes at YouTube keep fucking IP banning Invidious, that's why it keeps fucking breaking. You should fucking kill yourself, if you weren't such a piece of shit nigger, I would tell you how to bypass YouTube's faggot ads 100% of the time without having to worry about them IP banning Invidious' servers. But no, you had to go and disparage the hard working folks who are doing everything they can against a fucking globohomo multi (((billion))) dollar pajeet company who is going to make you suck the cow shit off their dicks in 10 years. Fuck you dude, I wish there were harder slurs than nigger, cuz you're worse than a nigger.

**Comment by HateHigsBoson** [comment] 2024-09-16 07:00
LMFAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO BRO MARRIED FUCKING SEX DOLLS 
![image](https://github.com/user-attachments/assets/71aace41-8dea-4699-be9c-09b8fc25c9c4)

**Comment by W9JYD** [comment] 2024-09-16 07:01
@iv-org please flag above comment. This is unacceptable hate speech.

**Comment by HateHigsBoson** [comment] 2024-09-16 07:02
@iv-org please ban the above nigger, he's a coomer who has sex with dolls and should kill himself
