### ISSUE TITLE
Age-restricted videos can't be extracted/supported.

### ISSUE THREAD

**Issue by MrBrastavaya** [iv-org/invidious#2309] opened 2021-08-06 22:47 UTC
**Describe the bug**
Age-restricted videos won't play and will stay a thumbnail. Bug always happens on all instances and has been tested by me.

**Steps to Reproduce**
1. Go to any age-restricted video
2. Click on the play button
3. And the video won't work.
Example: http://iteroni.com/watch?v=EDIxTIi9Uzw

**Logs**
http://iteroni.com/watch?v=EDIxTIi9Uzw

**Additional context**
 - Browser (if applicable): Chrome
 - OS (if applicable): Chrome OS

**Comment by syeopite** [comment] 2021-08-06 22:57
Duplicate of #2189

**Closed by syeopite** 2021-08-06 22:57 UTC
Labels: bug
