### ISSUE TITLE
[Question] "The media could not be loaded, either because the server or network failed or because the format is not supported." - inv_sig_helper missing

### ISSUE THREAD

**Issue by Vamp898** [iv-org/invidious#4946] opened 2024-09-25 06:04 UTC
**Describe the bug**
Randomly (but the amount increases every day) videos do not load with the Error Message "The media could not be loaded, either because the server or network failed or because the format is not supported.".

It started with 1% of the Videos a week ago but i'm now at 90% of the Videos not playing due to this error, ratio increasing every day.

I have the exact same issue in NewPipe (not in yt-dlp), i also reported the bug there, but it was closed without any comment.

But the error in NewPipe is almost the same, the Player fails to play anything with the error, the format is not supported.

Happens unrelated to shorts or normal videos. I noticed that most Videos where this happens, when switching to youtube, i get offered an 1080p Premium Version, maybe there is an correlation but i've watched Videos with this option that worked fine... so maybe not.

**Steps to Reproduce**
Try to play this Video with Invidious https://www.youtube.com/watch?v=atfDZIZSfLY

**Logs**
Exception: Error while writing data to the client (HTTP::Server::ClientError)
  from /usr/lib/crystal/http/server/response.cr:256:9 in 'unbuffered_write'
  from /usr/lib/crystal/io/buffered.cr:163:14 in 'write'
  from /usr/lib/crystal/http/server/response.cr:97:7 in 'write'
  from /usr/lib/crystal/io.cr:1177:7 in 'copy'
  from src/ext/kemal_static_file_handler.cr:94:5 in 'send_file'
  from src/ext/kemal_static_file_handler.cr:185:13 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/lib/crystal/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/http/server.cr:521:5 in 'handle_client'
  from /usr/lib/crystal/http/server.cr:451:5 in '->'
  from /usr/lib/crystal/fiber.cr:143:11 in 'run'
  from /usr/lib/crystal/fiber.cr:95:34 in '->'
  from ???
Caused by: Error writing to socket (#<TCPSocket:0x761b9f8b8000>): Broken pipe (IO::Error)
  from /usr/lib/crystal/io/evented.cr:45:11 in 'write'
  from /usr/lib/crystal/crystal/system/socket.cr:89:5 in 'system_write'
  from /usr/lib/crystal/socket.cr:442:7 in 'unbuffered_write'
  from /usr/lib/crystal/io/buffered.cr:163:14 in 'write'
  from /usr/lib/crystal/http/server/response.cr:273:11 in 'unbuffered_write'
  from /usr/lib/crystal/io/buffered.cr:163:14 in 'write'
  from /usr/lib/crystal/http/server/response.cr:97:7 in 'write'
  from /usr/lib/crystal/io.cr:1177:7 in 'copy'
  from src/ext/kemal_static_file_handler.cr:94:5 in 'send_file'
  from src/ext/kemal_static_file_handler.cr:185:13 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/lib/crystal/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/lib/crystal/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/http/server.cr:521:5 in 'handle_client'
  from /usr/lib/crystal/http/server.cr:451:5 in '->'
  from /usr/lib/crystal/fiber.cr:143:11 in 'run'
  from /usr/lib/crystal/fiber.cr:95:34 in '->'
  from ???

**Screenshots**
![image](https://github.com/user-attachments/assets/dd9fa1f5-6b50-4ac4-a580-a6d0834700dd)

**Comment by Vamp898** [comment] 2024-09-25 06:06
Recent example: This Video played fine yesturday, no longer plays today
https://www.youtube.com/watch?v=OtejSh-trJQ

**Comment by Stoppedwumm** [comment] 2024-09-25 06:09
Is YouTube changing formats or what?

**Comment by m4teh** [comment] 2024-09-25 06:55
> Is YouTube changing formats or what?

Yeah they've definitely changed something up very recently.

**Comment by unixfox** [comment] 2024-09-25 07:05
Duplicate of https://github.com/iv-org/invidious/issues/4947

**Closed** 2024-09-25 07:07 UTC
Labels: question
