### ISSUE TITLE
[Bug] Captions not working on any instance

### ISSUE THREAD

**Issue by tazz4843** [iv-org/invidious#3498] opened 2022-12-14 16:00 UTC
**Describe the bug**
Captions do not work on any instance, even my selfhosted one behind HTTP Basic Auth which has extremely low traffic. This doesn't appear to be a duplicate of #2567, which is specifically for large instances.

**Steps to Reproduce**
1. Enable captions
2. Note the network request made for captions, and inspect its response.

**Logs**
```
WEBVTT
Kind: captions
Language: en

```

**Additional context**
Client:
Browser: Firefox 107.0.1
OS: SteamOS 3.4

Host:
OS: arm64 Debian 11 (invidious in Docker)

**Comment by DUOLabs333** [comment] 2022-12-14 19:17
This is a duplicate of #3455

**Closed** 2022-12-14 19:22 UTC
Labels: bug

**Comment by IrIougER** [comment] 2022-12-16 15:52
I have the same issue.   I host an instance that I only use.
