### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by omarroth** [iv-org/invidious#1320] opened 2020-08-01 21:39 UTC
Starting September 1st, I'm shutting down the user-facing portion of https://invidio.us and stepping away from development. You can read more [here](https://omar.yt/posts/stepping-away-from-open-source).

@Perflyst has been promoted to project owner.

**Comment by Perflyst** [comment] 2020-08-01 21:52
Please note that I am not a developer. Therefore, I will most likely not be able to implement breaking changes from YouTube in Invidious.
I will do my best to manage the issue section and to answer questions. Previous code collaborations were also invited to the GitHub organization.

**Comment by cloudrac3r** [comment] 2020-08-01 22:35
While I'm here at the top of the thread, I'll start a list of things you can switch to for youtube viewing alternatives.

The most obvious answer is to just go on youtube. If this isn't acceptable, read on.

You can go to https://instances.invidio.us to see a list of other instances that will hopefully stay running. Please pick random entries from that list to find your new home. If everyone picks the options at the top, those instances will likely be overwhelmed with new users, and become extremely shaky or forced to close entirely.

For android phones, use NewPipe. NewPipe does not rely on Invidious.

To download videos, use youtube-dl, or one of the many frontends for it.

My website, https://cadence.moe/cloudtube/subscriptions, uses the Invidious API. I will try to keep it running, since I use it myself, but at this point it is basically unmaintained.

FreeTube https://freetubeapp.io can either use the Invidious API or the built-in extractor. It is maintained and a rewrite of the code is being actively developed by Preston, and myself.

For an implementation of the API, my project here implements a few endpoints by calling the youtube-dl command line and reformatting the response into JSON on a webserver. I intend to develop this further. https://github.com/cloudrac3r/youtubedl-invidious

For RSS, youtube offers RSS feeds directly.

This list may be updated in the future.

**Comment by iAmNoVa-UXX** [comment] 2020-08-01 23:11
Thank you for what you have provided @omarroth we appreciate what you've done

**Comment by WandeingLagomorph793** [comment] 2020-08-01 23:51
Is this only for the invidio domain or does this affect every other domain alongside it?  I use Snopyta and Yewtube whenever the main domain has issues.

**Comment by Zero3K** [comment] 2020-08-02 04:16
> 
> 
> Is this only for the invidio domain or does this affect every other domain alongside it? I use Snopyta and Yewtube whenever the main domain has issues.

It only affects the invidio domain. It will eventually affect the other domains if no one can improve/fix the project as needed.

**Comment by pluja** [comment] 2020-08-02 07:00
I am building [Parasitter](https://github.com/pluja/Parasitter). It is an app to follow and watch Youtube and Twitter with privacy. It uses Nitter's RSS feeds and Invidiou's API and RSS feeds. I will try to keep it up and I will investigate to see if I can break de dependence with Invidious API.

**Comment by GauthierPLM** [comment] 2020-08-02 07:54
Thank you for your hard work.
You built more than a side project, you built a real alternative to YouTube, that respect privacy without cutting on features or requiring to give up on our subscriptions and watching habits.

Good luck for whatever you will do next, and please know that you built something really meaningful and should be proud of the work done, and your investment in this project.

**Comment by musq** [comment] 2020-08-02 09:33
I love your decision to take care of yourself!

**Comment by aadcg** [comment] 2020-08-02 11:17
Thank you for all the hard work!

**Comment by SuperSandro2000** [comment] 2020-08-02 13:04
The title of your post is very misleading. You are not stepping away any millimeter from open source software, just from maintaining invidious.

**Comment by CSDUMMI** [comment] 2020-08-02 16:25
@SuperSandro2000 I am thinking about learning Crystal.
Is is worth it?

**Comment by Draphar** [comment] 2020-08-02 17:07
I discover such an awesome project, and a week later *this* happens... thanks for you work though!

**Comment by CSDUMMI** [comment] 2020-08-02 19:01
It's not gone.
I have a question:
Is it at all possible for Invidious to join the Fediverse?

**Comment by resynth1943** [comment] 2020-08-02 20:04
Invidious in the fediverse would be interesting, indeed. Perhaps you could even create ActivityPub accounts for a YouTuber upon API request ...? And then have their videos posted in the stream?

All good ideas!

**Comment by robert5800** [comment] 2020-08-02 20:20
Wait does this mean that www.invidio.us will be shut down forever..? Sorry I'm kind of a noob.

**Comment by Booteille** [comment] 2020-08-02 20:50
Hi!

Thanks for the hard work you did past years, Omar, it has been very appreciated and you opened the way for different cool projets (Nitter, Bibliogram, etc.).
So, thank you very much for all you did for everyone.

I have two questions, though.
The first one is for you,  @omarroth: Are you about to give/sell the domain to someone? To @Perflyst? I am a bit worried that scammers or whatever would get the domain and scam users which don't know that this instance in unmaintained.

The second one is for you, @Perflyst. Since you are not a developer, are you willing to seek actively a second maintainer, which would help with programming? I know it can be pretty hard, especially since Crystal does not seem to be a very known language.

Anyway, thanks again, both of you, for what you did already for Invidious. It's really appreciated.

**Comment by Perflyst** [comment] 2020-08-02 21:23
The domain will not be sold, for now omarroth keeps it and if in any case he wants to get rid of it I am sure it will stay in the community.

 > are you willing to seek actively a second maintainer

I am not sure how that should work. The attention on Omar's blog post is now at its highest. There are threads on Reddit and Hackernews. After the whole thing flattens out again, it becomes even more difficult to find a new maintainer.

**Comment by Booteille** [comment] 2020-08-02 21:35
> The domain will not be sold, for now omarroth keeps it and if in any case he wants to get rid of it I am sure it will stay in the community.

Perfect. That's what I wanted to read!

> > are you willing to seek actively a second maintainer
> 
> I am not sure how that should work. The attention on Omar's blog post is now at its highest. There are threads on Reddit and Hackernews. After the whole thing flattens out again, it becomes even more difficult to find a new maintainer.

Yeah, definitely.

Maybe If you are willing to find another maintainer to help you on this side, maybe we could use this momentum and the community to help to find a Crystal developer.

Anyway, I am happy you decided to maintain the project.

**Comment by WandeingLagomorph793** [comment] 2020-08-03 01:16
What's the next recommended Instance for now? I usually try Snopyta but NoScript blocks the video (even after setting permissions) unless i use Dash quality only, but that only ever gives me 360p video when i use that. I also tried Yewtube but that wouldn't let me import my .us settings into it (Just says "A bug has been found in Invidious)

**Comment by ChaseHall** [comment] 2020-08-03 03:07
@WandeingLagomorph793 I've had success importing YouTube & Invidious data as ["youtube subscriptions"](https://i.imgur.com/jsnGN8z.png)

**Comment by WandeingLagomorph793** [comment] 2020-08-03 04:20
> @WandeingLagomorph793 I've had success importing YouTube & Invidious data as ["youtube subscriptions"](https://i.imgur.com/jsnGN8z.png)

Does it matter if it's .json? I used it's regular format for Snopyta and that transferred fine for that.

**Comment by Booteille** [comment] 2020-08-03 09:40
> What's the next recommended Instance for now? I usually try Snopyta but NoScript blocks the video (even after setting permissions) unless i use Dash quality only, but that only ever gives me 360p video when i use that. I also tried Yewtube but that wouldn't let me import my .us settings into it (Just says "A bug has been found in Invidious)

You should try any instance up to date.

Check https://instances.invidio.us/

**Comment by resynth1943** [comment] 2020-08-03 20:00
Honestly, looking at this issue now. Invidious is practically screaming for a URI scheme, e.g. `invidious://video/...`, so we can easily switch which instance we use.

**Comment by trymeouteh** [comment] 2020-08-03 22:45
Thanks for handing the project over to someone and not walking away it. And thank you for all you have done for invidious

**Comment by resynth1943** [comment] 2020-08-03 22:53
@Perflyst while I love that Omar Roth has made you a maintainer, I can't see how Invidious would keep up with YouTube's tomfoolery against Invidious without a dedicated maintainer that can code. As you said yourself, you are not a programmer, so who is going to keep the project's code up to date?

Has anyone offered to maintain this, yet?

**Comment by Perflyst** [comment] 2020-08-05 07:02
You are right, this is a problem we are aware of.

> Has anyone offered to do this, yet?

Nobody yet, but we all hope that someone is interested in developing the project further

**Comment by resynth1943** [comment] 2020-08-05 13:38
Hopefully... I would offer to help, but a lot of it is in Crystal.

**Comment by Hepativore** [comment] 2020-08-05 17:59
I understand omarroth's reasons for leaving Invidious, but I am not sure what to use as a replacement, now. This was the same fate of another YouTube frontend called Hooktube. The problem is that the YouTube website itself is almost unusable as it is bogged down with ads and finding many videos is difficult due to the horrible search algorithm that YouTube has not to mention all of the data-mining that Google does through YouTube. Finally, this is the only frontend that I have seen that gives you the option to stream videos in audio-only.

Another good thing about Invidious is the fact that there are several add-ons for Firefox that redirect YouTube links to their Invidious equivalent, as well as embed Invidious players in place of an embedded YouTube video on a website. If anybody can recommend a frontend that has similar support in terms of website add-ons, I will be much obliged. I took a look at Freetube.io, but it looks like you need to download it first to use it which I cannot do on my work computer.

I second the idea of omarroth finding a maintainer while he is away. Invidious is too useful of a website to let it languish.

**Comment by pluja** [comment] 2020-08-05 18:39
@Hepativore (or anyone reading this) If you are a developer, you are very welcome to contribute to [Parasitter](https://github.com/pluja/Parasitter) as I'm trying to make an alternative written in Python+Flask of what invidious was.

**Comment by Hepativore** [comment] 2020-08-05 19:14
> 
> 
> @Hepativore (or anyone reading this) If you are a developer, you are very welcome to contribute to [Parasitter](https://github.com/pluja/Parasitter) as I'm trying to make an alternative written in Python+Flask of what invidious was.

I am a histologist (biologist), not a programmer. I might be slightly better than average in terms of a few tricks here and there when it comes to computer stuff, but I would not be able to help you directly with Parasitter.

Will Parasitter also have its own website for those of us who cannot always use a downloadable app?

**Comment by pluja** [comment] 2020-08-05 19:25
@Hepativore yes, that is the idea. I already have the parasitter.net domain, but until a minimum viable product is not ready it won't be online.

**Comment by SimonBrazell** [comment] 2020-08-06 00:11
Hello @omarroth I want to start by thanking you for this marvellous service, you have achieved something truely great in this project and I hope you are very proud of it.

I'd like to help with the future maintenance of this project but unfortunately I know little about Crystal, however I am a Ruby developer so perhaps that's a start? 

Anyway, for now I work on the [Privacy Redirect extension](https://github.com/SimonBrazell/privacy-redirect) for both Chromium and Firefox, which makes use of the invidio.us service, where it is the default instance for Youtube redirects. Given the shutdown of this instance, I'm going to change this to instead be randomised on installation, picking an instance from the [list of available instances](https://instances.invidio.us/), which I've already done for Bibliogram, on request by @cloudrac3r, to help share the load around. Any instance owners who are listening to this thread and would not like me to do this, please let me know and I'll make sure your instance is not included.

Thanks again @omarroth, all the best in your future endeavours mate!

**Comment by resynth1943** [comment] 2020-08-07 01:26
> I second the idea of omarroth finding a maintainer while he is away. Invidious is too useful of a website to let it languish.

Agreed. I am pretty worried. I should probably cut down on my Invidious usage, but I am most worried about the people that might give in to YouTube if this module is broken without repair.

@pluja I love your module! If I'm reading it correctly, can it be used as a webapp?

**Comment by omarroth** [comment] 2020-08-07 23:40
> I'd like to help with the future maintenance of this project but unfortunately I know little about Crystal, however I am a Ruby developer so perhaps that's a start?

If you (or anyone else looking to contribute) has any questions about specific functionality or lines of code feel free to open a new issue here or message me on Matrix.

**Comment by pluja** [comment] 2020-08-08 07:58
> > I second the idea of omarroth finding a maintainer while he is away. Invidious is too useful of a website to let it languish.
> 
> Agreed. I am pretty worried. I should probably cut down on my Invidious usage, but I am most worried about the people that might give in to YouTube if this module is broken without repair.
> 
> @pluja I love your module! If I'm reading it correctly, can it be used as a webapp?

Not yet but it will soon!

**Comment by ExpandingMan** [comment] 2020-08-08 15:02
@omarroth , thanks so much for all of your hard work, it's super appreciated by so many people.  I also routinely use the super-clean invidious sites to demonstrate to people how the internet *should* have looked.

As far as a path forward goes, I've been mulling over a bit whether I want to do anything here, and I keep coming to the conclusion that really we probably just need something that uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) as a back-end.  It seems to be a very widely used tool and though it doesn't look like it has a particularly high truck factor, it seems unlikely to be going away any time soon.  After all, writing code to host a static site isn't hard or particularly painful, web scraping on the other hand is inhuman torture.

**Comment by cloudrac3r** [comment] 2020-08-08 15:06
> and I keep coming to the conclusion that really we probably just need something that uses youtube-dl as a back-end.

This is what I am trying to do with https://git.sr.ht/~cadence/Second . It will be an implementation of the API, so when it works fully, it can be used with any front-end that uses the API, like CloudTube and FreeTube.

**Comment by ExpandingMan** [comment] 2020-08-08 15:09
An important question though, does youtube-dl really not use the official google API's?  That seems like one of the essential design features of invidious and it would be a shame to move to tools that weren't true to that.

**Comment by cloudrac3r** [comment] 2020-08-08 15:26
youtube-dl does not use the APIs, and this is why you do not need to generate an API token to use it.

**Comment by user234683** [comment] 2020-08-11 02:49
> As far as a path forward goes, I've been mulling over a bit whether I want to do anything here, and I keep coming to the conclusion that really we probably just need something that uses youtube-dl as a back-end. It seems to be a very widely used tool and though it doesn't look like it has a particularly high truck factor, it seems unlikely to be going away any time soon.

I was doing this previously for my similar Youtube client and wouldn't recommend it long-term. The only advantage you really get is that the data for the watch page is provided to you. All the other pages in Youtube require your own scraping because youtube-dl is really only meant to be used for, well, downloading videos. Additionally, in order to add additional features, such as getting captions and the music list, it required modifying youtube-dl and maintaining a mini-fork inside my project. This made it a bit tedious to integrate changes from upstream. Plus, the youtube-dl code is quite old, has a lot of cruft, and I've found that it breaks more frequently than a more robust, custom backend (it also depends on the disable_polymer layout which Youtube might remove suddenly in the future). For this reason, I made my own backend with a greater focus on making it more resilient towards changes upstream from Youtube. The client is [here](https://github.com/user234683/youtube-local) for anyone who's interested.

**Comment by digitalcraftsman** [comment] 2020-08-13 12:48
To cite @SuperSandro2000 from an earlier comment: 
> Choosing niche programming languages for projects has its drawbacks.. sadly.

There's nothing wrong with Crystal itself and Invidious seems to be one major projects showcasing the capabilities of Crystal as a programming language. The Invidious project lost traction simply due to the lack of man power, i.e. developers that know Crystal.

Several people in this thread already showed interest in contributing to Invidious, but had no programming experience in Crystal. *So would it be feasable to port the codebase of Invidious to a more popular language, e.g. Python or Go?*

This could attract more contributors, thus distributing the effort of maintenance and development over multiple people. @pluja for example stated that he's working on a [project](https://github.com/pluja/Parasitter/tree/dev-indep#parasitter) written in Python that aims to provide a similar functionality as Invidious.

In general it might be interesting to have a general overview of 
- where the community sees Invidious realisticly in the future,
- how many people would be willing to contribute,
- and what the largest intersection of expertise (e.g. in a programming language / tool) of potential contributors is.

**Comment by zethexx** [comment] 2020-08-14 05:10
Maybe we could copy how NewPipe does it and use it in invidious (or some other web interface app that people might be creating). Its pretty well established already and does not have the limitations of youtube-dl. It would also address the issues with the video tab we're having now because if they want to do that again, they will have to affect newpipe as well. (I know its not a permanent solution but scraping youtube isn't permanent anyway)

And obviously the server will do the scraping, not the client (in newpipe it's a client-side app so the client does the scraping) like currently.

**Comment by digitalcraftsman** [comment] 2020-08-14 14:55
@zethexx the [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) library is Java-based Code and independent from the NewPipe app. So code reuse might be possible.

**Comment by digitalcraftsman** [comment] 2020-08-14 14:58
Another promising option is [Freetube](https://github.com/FreeTubeApp/FreeTube), an open source desktop YouTube player written in JavaScript. It's reliance on the Invidious' API and intentions to improve the quality of the codebase lead to an in-progress [rewrite of Freetube](https://github.com/FreeTubeApp/FreeTube-Vue). The rewrite cuts the dependency on Invidious by replacing the functionality of the Invidious API using already existing packages (e.g. [this](https://www.npmjs.com/package/yt-scraper) and [this](https://www.npmjs.com/package/yt-channel-info)) in the Javascript ecosystem. The current [state of the rewrite](https://github.com/FreeTubeApp/FreeTube-Vue#what-needs-to-be-done) looks already quite feature complete. 

You can find more information in a response to the future of the Invidious project by the maintainer of Freetube, @PrestonN.

In a joint effort the Freetube and Invidious community could maintain a shared library that scrapes all necessary metadata for an alternative Youtube-frontend, without relying on the Youtube API. While both projects share a common core, Freetube remains a desktop app while Invidious wraps the library in a web-based frontend.

**Comment by cloudrac3r** [comment] 2020-08-14 15:37
That's a good idea and is viable.

Again, I'm currently working on an implementation of the API in Python, which should also meet the goal of being compatible with an alternative front-end. https://git.sr.ht/~cadence/Second

**Comment by pluja** [comment] 2020-08-14 17:48
@cloudrac3r I like what you're doing with 'Second', I'll be taking a look to maybe integrate it with Parasitter.

**Comment by stephane-r** [comment] 2020-08-15 14:25
@digitalcraftsman i have developed an open source [android app](https://github.com/stephane-r/HoloPlay) which uses invidious API's too. Your idea is interesting !

**Comment by GitWaifu** [comment] 2020-08-16 04:15
can anyone amuse me by confirming that google doesn't rate limit or captcha blocking chinese VPN companies like Nord VPN or Express VPN because chinese government is effectively bribing google through unskippable embedded sponsorships in vlogs

**Comment by DalekDave** [comment] 2020-08-16 08:06
I apologize for keeping on "ranting" about this, but - as far as I can see - the only way to give the Invidious project a chance of finding a new developer and surviving into the future would be to thoroughly document it. IMHO, without that, it's doomed.

If it was thoroughly documented, the fact that much of it is written in Crystal would not be so much of a problem. I'm guessing that Crystal is just another procedural language and would be learnable.

If the project's architecture and functioning was thoroughly documented, it would be feasible to pick up the development.

Unfortunately, @omarroth 's kind offer to answer specific questions about the code would not be enough. It would take a proper enterprise on documentation, such as I proposed on Matrix.

I was sad to take down my own Invidious instance already. Google is shutting down Google Play Music very shortly, and is going to merge it into YouTube Music. I am betting that they will rewire their APIs.

If Omar can't be persuaded to undertake a detailed documentation effort with me and whatever other community members who are willing, then I would say this project is going to come to an end...

**Comment by pluja** [comment] 2020-08-16 13:25
Great progress today with Parasitter. Parasitter server is now MUCH less dependent with Invidious as I'm trying to make it a stand-alone option for watching youtube!

**Comment by WandeingLagomorph793** [comment] 2020-08-30 01:20
Figured I'd ask but does exporting data work if I export it from *any* instance? (Say I export data from Invidious.snopyta) or does that data only work when it's exported from the invidio.us domain?

**Comment by cloudrac3r** [comment] 2020-08-30 02:32
@WandeingLagomorph793 I believe it works to import data into other instances. Try it :)

**Comment by resynth1943** [comment] 2020-08-31 20:58
2 hours, now.

**Comment by resynth1943** [comment] 2020-08-31 23:00
Thanks for everything, @omarroth. It's officially September the 1st, 12:00AM. ❤️ 
Let's hope Invidious lives on, but if it doesn't, there are alternatives.

**Comment by Zero3K** [comment] 2020-08-31 23:02
Its not September 1st for the US though.

**Comment by resynth1943** [comment] 2020-08-31 23:04
Lol fair I guess. It is in the UK, so... 🎉

**Comment by unixfox** [comment] 2020-09-01 05:47
The shutdown won't happen automatically at midnight, I suspect that omarroth will just have to do it manually during the day but we don't know when he will do it.

**Comment by elypter** [comment] 2020-09-01 10:35
thanks for everything @omarroth. i am confident that this project lives on in its mirror instances but even if it doesn't it provided a great value while it was running.

**Comment by resynth1943** [comment] 2020-09-01 13:50
It's gone now, @unixfox. I'll be keeping an eye on this project...

**Comment by pluja** [comment] 2020-09-01 17:54
Checkout [Yotter](https://github.com/pluja/Yotter), the written-in-python Invidious alternative that I'm building. All contributors are really welcome and needed!

**Comment by notpushkin** [comment] 2020-09-03 14:51
Thank you so much for your great work, @omarroth!

Re: list of alternatives, [mpv](https://mpv.io) works in tandem with youtube-dl so you can play youtube videos by just passing a link, like `mpv https://www.youtube.com/watch?v=NICYIWy007c`.

Re: Invidious future: I think outsourcing the YouTube-facing portion to youtube-dl is the way to go, but we also need to start building a more decentralized solution, because we'll certainly have many instances like we have now with Invidious, and transparent cooperation between instances could be helpful to work around rate limits, bans, geo-restricted content etc.

@pluja @cloudrac3r Any chance you could cooperate on [Yotter](https://github.com/pluja/Yotter) / [Second](https://git.sr.ht/~cadence/Second)?

**Comment by notpushkin** [comment] 2020-09-03 15:16
For example, we could go like this:

- one frontend (i. e. on the invidio.us domain) that queries Second instances either directly from browser (needs JS enabled and CORS support) or from server (one more hop but should be OK for metadata)
- if a Second instance is down, another one is selected automatically (or can be switched manually if needed)
- `https://invidio.us/api/*` redirects to a random Second instance
- videos are played in a local player or, if DASH is needed, as an iframe from the selected Second instance's origin (if proxying support is enabled)
- if mpv/IINA/other YouTube-supporting player is installed, videos could be opened there instead (#806)
- [Web Monetization](https://webmonetization.org/) could be used to support Second instance owners, the Invidious project as a whole and of course video authors :)

**Comment by ExpandingMan** [comment] 2020-09-03 15:33
Seems like there are a number of exciting possibilities for alternatives.  I have been surveying the options a bit and have found the following:
- FreeTube is slow, buggy mess (the authors have pretty much admitted as such, so I'm not saying anything controversial here), but the Vue.js rewrite seems to be on a good track and seems quite usable already.
- NewPipe is really great, and is now what I use excslusively on mobile.  It's really unfortunate that it's very much a dedicated android app, written in Java.  Presumably it can be used elsewhere with Anbox, but it'll probably never be a good option for desktops.
- youtube-dl seems to be the most mature, well-maintained web-scraping back-end and a number of projects have been built over it, but unfortunately its functionality is very focused on downloading videos, so some of the most useful aspects of invidious (for me, at least) really just aren't available through youtube-dl (as far as I can tell).
- I haven't tried Yotter or Second myself, but they look promising.

I can help but feel that many of these projects conflate what I really think should be separate components.  Really what we need is a core web-scaping program, and then whatever else can be built on top of that.  youtube-dl almost is that, but again, it really seems totally focused on scraping videos, and there is some crucial metadata (particularly channels) that it doesn't seem to touch (please correct me if I'm wrong).

**Comment by user234683** [comment] 2020-09-04 02:06
@ExpandingMan My project [youtube-local](https://github.com/user234683/youtube-local) is another option. It has the scraping code separated into a module called `yt_data_extract`. There's also a list of similar projects at the bottom that might be worth looking into.

Advantages of `yt_data_extract`:
- Written in Python
- Decoupled from the rest of the project
- Lots of general-purpose abstractions specially designed for parsing the polymer format (polymer refers to the 2017-present "new" Youtube layout, and the JSON API it provides), instead of hardcoding the particular JSON key trees, which change regularly.

Disadvantages:
- Undocumented (I'm willing to write documentation if there's interest in using this)
- Does not return the same names/organization for data as the Invidious API does, so it cannot be used as a drop-in replacement without adjustment or a translation layer.
- No unit tests yet (something I'm planning on adding)
- The module only contains code for parsing polymer responses from the Youtube endpoints. It does not have the code for which particular requests to send out, such as what endpoints to use, in what order, and how to generate the continuation tokens necessary to use them (e.g. `https://www.youtube.com/browse_ajax?ctoken=[...]`). The request code is tightly coupled with the rest of the project.
- Probably rough around the edges, since this is just a small hobby project.

The most straightforward way to adapt this into a core web scraping program would be to write code around it that handles the requests, passes them to `yt_data_extract`, and then exposes an API in the Invidious format. I'm willing to provide pointers/guidance on this and answer questions, though I can't commit significant time to it.

**Comment by thestigmister** [comment] 2020-09-05 19:57
Not a technical comment, just me commenting on this situation.

Oh man, I really liked invidio.us. I don't even know if the other instances work cos they don't seem to at the moment.
I mainly used it cos I have a first gen iPad and the YouTube apps don't work pre iOS 6 (I've tried TubeFixer and it still doesn't work) so I was using invidio.us to watch YT videos on my iPad via browser.
Sure it wasn't my primary YT viewer but it was cool to be able to, especially with the big (albeit weirdly ratio'd) screen.

The alternatives mentioned like Cadence doesn't seem to work on my iPad. 
If anyone does know any other way to watch YT on old Apple devices, I'd really appreciate it.

**Comment by notpushkin** [comment] 2020-09-05 20:05
> if the other instances work

Some of them do, but apparently not all the time. [invidious.fdn.fr](https://invidious.fdn.fr/) was the most stable for me at the time I tested, but I've switched to running plain YouTube in a separate Mozilla container tab instead. I'm still hoping the Invidious ecosystem grows to be a bit more stable so I can use it once again!

**Comment by ImprovedTube** [comment] 2020-09-07 07:02
Indivio.us used to lead my watchlist for the unique API server powering features like this:
[google.com/Webstore/Annotations-restored](https://chrome.google.com/webstore/detail/annotations-restored-for/daabpdmgkghdbfljmeahnplkcldbeefg)  (which we were finally implementing too :/ )
Now this data wont be accessible anywhere soon. ( besides maybe another developer  starts over from whats at archive.org) 

What about decentralizing the API database? (Or just a download / torrent)   
Will it help right now, if anybody or we took custody of it for unlimited years

<img width="622" alt="youtube center" src="https://user-images.githubusercontent.com/25022245/92353990-b8629e00-f0e1-11ea-92e1-7c1fb81bbcda.png">
Why's everybody leaving? :( these projects are like baby alpacas 
<img width="351" alt="" src="https://user-images.githubusercontent.com/25022245/92352161-c0b8da00-f0dd-11ea-8561-332d9108e38d.png">
<img width="645" alt="youtube plus" src="https://user-images.githubusercontent.com/25022245/92353988-b7ca0780-f0e1-11ea-8b94-7247871bfef1.png">
-----

Many smiles to @omarroth @perflyst & Co  
<3

**Comment by ImprovedTube** [comment] 2020-09-07 07:04
Indivio.us used to lead my watchlist for the unique API server powering features like this:
[google.com/Webstore/Annotations-restored](https://chrome.google.com/webstore/detail/annotations-restored-for/daabpdmgkghdbfljmeahnplkcldbeefg)  (which we were finally implementing too :/ )
Now this data wont be accessible anywhere soon. ( besides maybe another developer  starts over from whats at archive.org) 

What about decentralizing the API database? (Or just a download / torrent)   
Will it help right now, if anybody or we took custody of it for unlimited years

<img width="622" alt="youtube center" src="https://user-images.githubusercontent.com/25022245/92353990-b8629e00-f0e1-11ea-92e1-7c1fb81bbcda.png">

**W**hy's everybody leaving? :/ these projects are like baby alpacas 
<img width="301" alt="" src="https://user-images.githubusercontent.com/25022245/92352161-c0b8da00-f0dd-11ea-8561-332d9108e38d.png">
<img width="645" alt="youtube plus" src="https://user-images.githubusercontent.com/25022245/92353988-b7ca0780-f0e1-11ea-8b94-7247871bfef1.png">
-----

Many smiles to @omarroth @perflyst & Co  
<3

**Comment by ImprovedTube** [comment] 2020-09-07 07:06
Indivio.us used to lead my watchlist for the unique API server powering features like this:
[google.com/Webstore/Annotations-restored](https://chrome.google.com/webstore/detail/annotations-restored-for/daabpdmgkghdbfljmeahnplkcldbeefg)  (which we were finally implementing too :/ )
Now this data wont be accessible anytime soon. ( besides maybe another developer  starts over from whats at archive.org) 

What about decentralizing the API database? (Or just a download / torrent)   
What about anybody or us taking custody of it?

<img width="622" alt="youtube center" src="https://user-images.githubusercontent.com/25022245/92353990-b8629e00-f0e1-11ea-92e1-7c1fb81bbcda.png">

#### Why's everybody leaving? :/ these projects are like baby alpacas 

<img width="301" alt="" src="https://user-images.githubusercontent.com/25022245/92352161-c0b8da00-f0dd-11ea-8561-332d9108e38d.png">
<img width="645" alt="youtube plus" src="https://user-images.githubusercontent.com/25022245/92353988-b7ca0780-f0e1-11ea-8b94-7247871bfef1.png">
-----

Many smiles to @omarroth @perflyst & Co  
<3

**Comment by unixfox** [comment] 2020-09-07 08:12
@ImprovedTube These projects aren't broken. Just run a local invidious instance and it will work fine just like it did when invidio.us was active.

**Comment by ImprovedTube** [comment] 2020-09-07 14:21
@unixfox no, they dont host a/the database. they didnt have traffic yet.

**Comment by ImprovedTube** [comment] 2020-09-07 14:23
@unixfox  they dont host a/the database. and didnt have relevant traffic yet. 
the puppy deserves a developer and to keep a database server
<img width="694" alt="" src="https://user-images.githubusercontent.com/25022245/92397007-49f3ff00-f126-11ea-817c-f2e8f1534a4c.png">

**Comment by ImprovedTube** [comment] 2020-09-07 14:24
@unixfox  they dont host a/the database. and didnt have relevant traffic yet. 
the puppy deserves a developer and to keep a database server
<img width="547" alt="Screenshot_372" src="https://user-images.githubusercontent.com/25022245/92397151-950e1200-f126-11ea-9334-83f5ef597f0c.png">

**Comment by ImprovedTube** [comment] 2020-09-07 14:27
@unixfox  they dont host a/the database. and didnt have relevant traffic yet.  it deserves a developer and to keep a database server
<img width="547" alt="Screenshot_372" src="https://user-images.githubusercontent.com/25022245/92397151-950e1200-f126-11ea-9334-83f5ef597f0c.png">

**Comment by ImprovedTube** [comment] 2020-09-07 14:56
@unixfox  they dont host a/the database. and didnt have relevant traffic yet.  
 it deserves a developer and to keep the database server

**Comment by cloudrac3r** [comment] 2020-09-07 15:00
@ImprovedTube, please try to avoid making so many edits. You could try reading your posts carefully a couple of times before pressing send. If you have additional information to add later on, consider putting it in a separate follow-up comment. :)

**Comment by ImprovedTube** [comment] 2020-09-07 15:26
hi @unixfox   i was referring to:   
- open source development for youtube:  Our niche wasn't efficient in the past years/decade: i hurt seeing projects pay a ton of effort and leave still on the verge to independence and having more than enough users and donations.

- about the database:  The other indivious instances,  dont host the database.  And didnt have relevant traffic yet. 
Indivious deserves a developer and to keep the database server

@cloudrac3r  Sure! you notice minor edits?

**Comment by ImprovedTube** [comment] 2020-09-07 15:29
hi @unixfox   i was referring to:   
- open source development for youtube:  Our niche wasn't efficient in the past years/decade: i hurt seeing projects pay a ton of effort and leave still on the verge to independence and having more than enough users and donations.

- the database:  The other indivious instances,  dont host the database.  And didnt have much traffic yet. 
Indivious deserves a developer and to keep the database server

@cloudrac3r  Sure! you notice minor edits? 😳

**Comment by tuxayo** [comment] 2020-09-07 18:40
@ImprovedTube 
> you notice minor edits?

I noticed this now: GitHub resend an email notification for each edit. Makes sense since GitHub allows to reply via email so one needs to somehow have the latest version otherwise that would cause confusion.

**Comment by ysodope** [comment] 2020-09-12 19:04
> Starting September 1st, I'm shutting down the user-facing portion of https://invidio.us and stepping away from development. You can read more [here](https://omar.yt/posts/stepping-away-from-open-source).
> 
> @Perflyst has been promoted to project owner.

There has to be software that can adapt to youtube implement I cant research atm fight tax forclosure but when I can I will do what I can to help

**Comment by MoistTowellettes** [comment] 2020-09-24 21:02
I would like to maintain invidious all I need to do is learn crystal which I should be able to do in the coming week with a new laptop coming, in three to four weeks from now I should be able to maintain invidious.

**Closed** 2020-10-15 14:26 UTC

**Comment by MoistTowellettes** [comment] 2020-10-28 22:45
I was never getting the promised laptop because I got scammed, I have one now but I cannot use it because it's on loan and is therefore heavily restricted in what is allowed to be downloaded, sorry guys.

**Comment by elypter** [comment] 2020-10-29 16:02
why not boot linux from an usb storage?

**Comment by MoistTowellettes** [comment] 2020-10-29 18:05
I'll try this.
