### ISSUE TITLE
[Bug] error 500 on/api/v1/storyboards/:ID?height=90

### ISSUE THREAD

**Issue by Talanor** [iv-org/invidious#4043] opened 2023-08-09 22:30 UTC
**Describe the bug**
Some videos, `/watch?v=cvmksJYzP5A&quality=medium`, for example. Generate a silent HTTP 500 error on local and public instances.

**Steps to Reproduce**
Go to yourinstance/watch?v=cvmksJYzP5A&quality=medium, doesn't work.

**Logs**
I don't see any relevant log even though I have configured log_level: Debug in my compose file.

**Screenshots**
N/A

**Additional context**
Firefox 102.14.0esr (64-bit)
Google Chrome 115.0.5790.171 (Official Build) (64-bit)

**Comment by markozajc** [comment] 2023-08-10 07:53
I assume this is related to https://github.com/iv-org/invidious/issues/4039 - both concern the storyboard not working.

**Comment by syeopite** [comment] 2023-08-10 18:47
Duplicate of #4039

---

#4037 introduced a regression when it comes to storyboards since YouTube doesn't return the data for storyboards when the workaround is applied. #4040 should fix it.

**Closed by syeopite** 2023-08-10 18:47 UTC
Labels: bug
