### ISSUE TITLE
Error when trying to access youtube channel

### ISSUE THREAD

**Issue by 518victor** [iv-org/invidious#1681] opened 2021-01-18 23:28 UTC
I am getting this error when trying to click on a youtube channel. I am using https://invidious.zee.li. 

Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-01-18T23:22:26Z`
Route: `/channel/UC3XdYJjWliOdKuZMNaTiP8Q`
Version: `2021.01.13-c7e65ce @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1715:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-01-19 08:16
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-01-19 15:54 UTC
