### ISSUE TITLE
Some playlists shows 0 videos even though they're not empty

### ISSUE THREAD

**Issue by rramiachraf** [iv-org/invidious#2616] opened 2021-11-14 19:25 UTC
**Describe the bug**
As the titles suggests, when I visit some playlists they don't show any videos but when I try to view it on YouTube I can then access videos from the playlist.

**Steps to Reproduce**
1. Go to any Invidious instance.
2. Visit this playlist for example `/playlist?list=PL8dPuuaLjXtNCG9Vq7vdvJytS-F-xGi7_`.
3. You'll notice that It contains 0 videos.
4. Click on `View playlist on YouTube`.
5. Dozens of videos going to appear.

**Screenshots**
Invidious:
![Invidious](https://i.imgur.com/ABvSszs.jpg)
YouTube:
![YouTube](https://i.imgur.com/agIn8Xj.jpg)

**Comment by SamantazFox** [comment] 2021-11-15 13:54
It could be because those videos are geo-restricted.
Try to use an invidious instance located in another country: https://instances.invidious.io

**Comment by unixfox** [comment] 2021-11-15 15:11
> It could be because those videos are geo-restricted. Try to use an invidious instance located in another country: [instances.invidious.io](https://instances.invidious.io)

Duplicate of https://github.com/iv-org/invidious/issues/92 then? Safe to close?

**Comment by SamantazFox** [comment] 2021-11-15 15:31
> Duplicate of #92 then? Safe to close?

Not sure. I've tried many different instances (yewtube, kavin's 3 instances, snopyta) and none show the playlist videos.

**Comment by rramiachraf** [comment] 2021-11-15 19:31
> It could be because those videos are geo-restricted. Try to use an invidious instance located in another country: https://instances.invidious.io

Not sure about that since I've tried every single public listed instance.

**Comment by SamantazFox** [comment] 2021-11-15 20:11
> Not sure about that since I've tried every single public listed instance.

Ok, so there is an issue somewhere else! Thanks for your report :)

**Comment by rramiachraf** [comment] 2021-11-15 21:00
Update: I tried the docker container on my local machine and It's showing 0 videos too, so the Geo-restriction is not an issue here at all.

**Comment by TheFrenchGhosty** [comment] 2021-11-17 19:55
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: #1898

**Comment by SamantazFox** [comment] 2022-01-19 16:10
Ok, so it's not related to geo-restriction at all.

It's just that those playlists are of a special kind: so called "learning playlists". And for those, youtube doesn't provide the number of videos (even though it's provided in search resullts and some other places).

![image](https://user-images.githubusercontent.com/52980486/150169881-301b26e9-627d-42d1-925c-e35d037d5fd6.png)

**Comment by rramiachraf** [comment] 2022-01-19 19:50
> Ok, so it's not related to geo-restriction at all.
> 
> It's just that those playlists are of a special kind: so called "learning playlists". And for those, youtube doesn't provide the number of videos (even though it's provided in search resullts and some other places).
> 
> ![image](https://user-images.githubusercontent.com/52980486/150169881-301b26e9-627d-42d1-925c-e35d037d5fd6.png)

Great work, you're absolutely right.
All the playlists which invidious shows 0 videos has a `Learning playlist` tag.

![Screenshot](https://i.imgur.com/vPFofO0.png "Screenshot")

**Comment by ChunkyProgrammer** [comment] 2023-03-23 02:28
I think this may be resolved now 
![image](https://user-images.githubusercontent.com/78101139/227084513-fd4041aa-14cf-40a8-bd15-09428ab1746e.png)

**Closed** 2023-09-16 23:08 UTC
Labels: bug, type:youtube-change, bounty, bounty:10$
