### ISSUE TITLE
[Bug] videos from more then 6 months ago don't appear in subscriptions

### ISSUE THREAD

**Issue by umikali222** [iv-org/invidious#4166] opened 2023-10-13 19:20 UTC
**Describe the bug**
videos from more then 6 months ago from some channels don't appear in subscriptions.
it's very inconsistent, I noticed this when the episodes 1, 2 of "We Turned New Zealand Into a Real-Life Board Game" from the channel "Jet Lag: The Game" wouldn't appear in subscriptions on my self-hosted docker-compose server, then I made a new account on the same server and subscribed to only that channel, all videos from more then 6 months ago, wouldn't appear. Then I tried it on https://invidious.io.lol/ , making a new account and subscribing only to that channel, but now it didn't show any videos from more then 9 months ago. Also a similar thing happened once, where I was subscribed to a channel (I completely forgot about it), and then when I restarted the docker-compose server, videos from that channel appeared in the subscriptions

**Steps to Reproduce**
1. Create a new account on an invidious instance e.g. https://invidious.io.lol/
2. Subscribe to the [channel called "Jet Lag: The Game"](https://invidious.io.lol/channel/UCxkM67T_Iele-mRVUiBkRqg)
3. Go to subscriptions
4. Compare subscriptions to the channel

**Comment by unixfox** [comment] 2023-10-13 19:31
Closing as I can't replicate the issue on a properly configured instance like https://invidious.flokinet.to

![image](https://github.com/iv-org/invidious/assets/4016501/50614183-c9de-412c-bff0-e48cefa46756)

Also in local I can't reproduce the issue either.

You will need to contact the owner of the instance invidious.io.lol for fixing the issue. Or use another instance on https://instances.invidious.io that allow registration.

**Closed by unixfox** 2023-10-13 19:31 UTC
Labels: bug
