### ISSUE TITLE
[Bug] Can't search - self hosted instance (docker)

### ISSUE THREAD

**Issue by ysarkain** [iv-org/invidious#3384] opened 2022-11-09 20:38 UTC
**Describe the bug**
When I try to search, nothing happens. 

**Steps to Reproduce**
1. Click on search box
2. Enter terms to search for
3. hit enter

I can, however, search by manually crafting the URL e.g. https://invidious-instance/search?q="test".

**Additional context**
Current version: 2022.11.02-09942dee @ master
Browser: Brave

**Comment by unixfox** [comment] 2022-11-23 09:17
Can't reproduce, closing...

**Closed by unixfox** 2022-11-23 09:17 UTC
Labels: bug
