### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KodiColdkeys** [iv-org/invidious#2618] opened 2021-11-15 04:41 UTC
Title: `Unexpected char 'C' at line 1, column 1 (JSON::ParseException)`
Date: `2021-11-15T04:38:21Z`
Route: `/data_control?referer=%2Fwatch%3Fv%3DKIZp9F_-b2o`
Version: `2021.11.14-0835e5df @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'C' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:331:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:327:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:243:10 in 'consume_number'
  from /usr/share/crystal/src/json/lexer.cr:63:7 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:108:11 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:9:5 in 'initialize'
  from /usr/share/crystal/src/json/parser.cr:6:3 in 'new'
  from /usr/share/crystal/src/json.cr:135:5 in 'parse'
  from src/invidious.cr:833:27 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:68:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>
 - Browser (if applicable):Edge
 - OS (if applicable):Win10-64
-->

**Comment by SamantazFox** [comment] 2021-11-15 13:49
CSV aren't supported yet on invidious: https://github.com/iv-org/invidious/issues/2319
Proposed alternative for importing a csv on invidious: https://github.com/iv-org/invidious/issues/2319#issuecomment-900358678

**Comment by SamantazFox** [comment] 2021-11-15 13:51
Closing, as it is a duplicate of #2319

**Closed by SamantazFox** 2021-11-15 13:51 UTC
Labels: bug
