### ISSUE TITLE
Page doesn't load to this YT site to allow viewing all videos on members page

### ISSUE THREAD

**Issue by daviddorian222** [iv-org/invidious#1847] opened 2021-03-03 18:42 UTC
Can't load 'The KMG Show' webpage show list page from Invidious:

Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-03T18:37:34Z`
Route: `/channel/UCsX7wTn2PXUXjrONO4ZBnfw`
Version: `2021.02.04-ec82c1f @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
  from src/invidious.cr:1716:20 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-03-03 18:44
This appears to be a duplicate of #1838. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-03-03 18:44 UTC
Labels: duplicate
