### ISSUE TITLE
Random Videos in other tabs starting unexpectedly 

### ISSUE THREAD

**Issue by elypter** [iv-org/invidious#327] opened 2019-01-31 00:53 UTC
i am using firefox 64 on windows 10. it now happened the 4 or 5th time that a video from a completely unrelated tab start playing. as far as i remember it is triggered by loading a new tab or starting to play another invidio.us video

**Comment by omarroth** [comment] 2019-01-31 18:02
You may have `autoplay` enabled, otherwise there's not much else I could suggest, since I'm having trouble reproducing.

**Comment by elypter** [comment] 2019-02-01 01:53
i dont have it enabled and i never had. its a weird bug becase it affects other tabs. maybe it was a firefox bug. i report if it keeps happening.

**Comment by elypter** [comment] 2019-06-03 16:40
it has been quite a while since the last time this happened so i assume whatever caused it is now fixed.

**Comment by Zero3K** [comment] 2019-06-29 03:36
Its not fixed for me.

**Comment by Zero3K** [comment] 2019-09-20 17:28
Its still happening.

**Comment by elypter** [comment] 2020-12-03 11:56
its very rare but probably not solved yet. last time it happened about 2 months ago.

**Comment by elypter** [comment] 2020-12-22 16:25
it happened many times yesterday and today so it definitely is still a problem

**Comment by Zero3K** [comment] 2021-12-23 01:55
Bump

**Comment by unixfox** [comment] 2021-12-23 06:41
> Bump

Still happening?

**Comment by unixfox** [comment] 2022-01-02 17:46
Closing due to a lack of replies.

Might be fixed because a lot of code changed since almost more than 1 year.

**Closed by unixfox** 2022-01-02 17:46 UTC
Labels: bug
