### ISSUE TITLE
[Bug] Invalid Int32: @Knorkatorstumpen (ArgumentError)

### ISSUE THREAD

**Issue by zseri** [iv-org/invidious#3405] opened 2022-11-19 09:57 UTC
**Describe the bug**
Parsing error while searching for specific term (probably also happens for others).

**Steps to Reproduce**
Go to https://invidious.snopyta.org/search?q=Knorkator

**Logs**
Title: `Invalid Int32: @Knorkatorstumpen (ArgumentError)`
Date: `2022-11-19T09:50:09Z`
Route: `/search?q=Knorkator`
Version: `2022.11.02-09942dee @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: @Knorkatorstumpen (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Additional context**

**Comment by zseri** [comment] 2022-11-19 10:03
https://github.com/iv-org/invidious/blob/09942dee6621e7047a63dffcc61b3bbf78cef2c6/src/invidious/yt_backend/extractors.cr#L169-L173

**Comment by SamantazFox** [comment] 2022-11-19 11:35
Closing as a duplicate of #3394

**Closed** 2022-11-19 11:35 UTC
Labels: bug, duplicate
