### ISSUE TITLE
[Bug] Videos not loading, Status code: 404

### ISSUE THREAD

**Issue by carallo** [iv-org/invidious#2244] opened 2021-07-09 10:38 UTC
Hi! First of all thanks for your amazing work!
I am having issues, I've tried many different istances (not all though but I will keep trying) but I still cannot seem to get any video to play. I get results and homepage top videos, but as soon as I try to play one the video is unable to load and I get this error:

`{
  "requestConfig": {
    "url": "videos/kxrWLP0KX5E",
    "method": "get",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "params": {
      "fields": "type,title,videoId,videoThumbnails,storyboards,description,descriptionHtml,publishedText,viewCount,likeCount,dislikeCount,paid,premium,isFamilyFriendly,author,authorId,authorThumbnails,subCountText,lengthSeconds,rating,formatStreams,recommendedVideos"
    },
    "baseURL": "https://viewtube.io/api/",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 30000,
    "withCredentials": true,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1
  },
  "responseData": {
    "status": 500,
    "message": "Status code: 404"
  },
  "message": "Request failed with status code 500"
}`

It's weird, about a week ago I was able to play a couple of videos but then it suddenly stopped.

**Comment by unixfox** [comment] 2021-07-09 14:00
Which public instances did you test? Which videos did you test?

**Comment by unixfox** [comment] 2021-07-11 08:45
Closing as a lack of replies and unable to reproduce the issue with the video ID kxrWLP0KX5E.

**Closed by unixfox** 2021-07-11 08:45 UTC
Labels: bug

**Comment by carallo** [comment] 2021-07-12 10:00
Sorry for the late reply!
Actually today seems to be working using the snopyta istance. On Firefox I had to disable ublock origin, which seemed to weridly be blocking the video loading (but I recall having already tried disabling it before, with no luck). Still have to try other istances and combinations but for now it seems to be working. Thank you!

**Comment by unixfox** [comment] 2021-07-12 10:49
I just tried with the given video (https://yewtu.be/watch?v=qFCeCPpfnhQ&quality=dash) and it loads fine on both Firefox and Chromium.
Could you open the network monitor and share a screenshot of the 404 errors? You should be able to access to it using F12.

**Comment by carallo** [comment] 2021-07-12 10:59
So, I've switched to the yewtu.be istance and I checked other videos were working, but still this one is not.
Here's screenshots from Firefox and Brave, I'm on Windows right now, but Linux seemed to suffer from the same issues.

![viewtubeBrave](https://user-images.githubusercontent.com/32939683/125276820-f5567d00-e310-11eb-861e-eea4ded5be17.png)
![viewtubeBrave2](https://user-images.githubusercontent.com/32939683/125276826-f687aa00-e310-11eb-8074-65487b02b340.png)
![viewtube](https://user-images.githubusercontent.com/32939683/125276827-f7204080-e310-11eb-8dba-92218ba747be.png)

**Comment by unixfox** [comment] 2021-07-12 12:01
viewtube.io is not even publicly listed on the public instances list: https://docs.invidious.io/Invidious-Instances.md
How is viewtube.io even related to Invidious? It's a completely other project??? You should instead report the issue on the viewtube project if there is a github repository.

**Comment by carallo** [comment] 2021-07-12 12:04
> 
> 
> viewtube.io is not even publicly listed on the public instances list: https://docs.invidious.io/Invidious-Instances.md
> How is viewtube.io even related to Invidious? It's a completely other project??? You should instead report the issue on the viewtube project if there is a github repository.

Hey @unixfox, I'm so terribly sorry! They do have an active github repository and I was sure I posted this issue on their tracker. I must have made confusion with tabs, I don't know how I can have mislooked this. Sorry, sorry, sorry!

**Comment by syeopite** [comment] 2021-07-12 12:13
Viewtube relies on Invidious from what I can see
