### ISSUE TITLE
[Bug] Google blocking videos again (please sign in)

### ISSUE THREAD

**Issue by mooleshacat** [iv-org/invidious#4972] opened 2024-10-03 01:37 UTC
**Describe the bug**

It appears that it is possible YT stepped up it's game. Just now every video I click on shows the "please sign in" message. It was just working all day up until seconds ago.

Either that, or they've blanket blocked VPN services. My instance uses a VPN because otherwise they'd just ban my naked IP.

Update: it must be the VPN block because after switching around getting blocked still , eventually I hit a VPN IP in the US that works. Maybe the signature helper or po-token stuff needs to be looked at again, somehow I am being detected and blocked.

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Using invidious over VPN

**Comment by mooleshacat** [comment] 2024-10-03 01:50
problem solved I guess

**Comment by unixfox** [comment] 2024-10-03 05:55
Duplicate of https://github.com/iv-org/invidious/issues/4734

**Closed** 2024-10-03 05:56 UTC
Labels: bug

**Comment by retrocaster** [comment] 2024-10-03 21:55
@mooleshacat It's not a VPN block. The same thing happened to me starting today on my locally hosted private instance which is on a residential IP address from Xfinity.
