### ISSUE TITLE
"Next page" link does not show

### ISSUE THREAD

**Issue by arankaren** [iv-org/invidious#1682] opened 2021-01-19 02:00 UTC
Results of the paging is displayed duplicate

https://invidious.048596.xyz/search?q=gnu%20linux&page=1
https://invidious.048596.xyz/search?q=gnu%20linux&page=2
https://invidious.048596.xyz/search?q=gnu%20linux&page=3

Current version: 2021.01.14-900e3bb

**Comment by hackerncoder** [comment] 2021-01-19 08:17
This appears to be a duplicate of #1480. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-01-19 15:54 UTC
