### ISSUE TITLE
[Bug] Missing hash key: "selected" (KeyError)

### ISSUE THREAD

**Issue by zlpynof** [iv-org/invidious#3154] opened 2022-06-20 12:30 UTC
Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-06-20T12:24:22Z`
Route: `/channel/UCAXKoxJLJj-Zm-Ulk4jRUJw/community`
Version: `2022.06.20-5d32f51 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/lib/crystal/core/json/any.cr:100 in '[]'
  from /usr/lib/crystal/core/json/any.cr:155:3 in 'fetch_channel_community'
  from src/invidious/routes/channels.cr:84:26 in 'community'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by projjalm** [comment] 2022-06-20 12:53
same problem here while trying to open playlists of a specific channel.

**Comment by unixfox** [comment] 2022-06-20 14:46
@zlpynof On which server did you test that?

**Comment by TheFrenchGhosty** [comment] 2022-06-20 18:58
@zlpynof @unixfox I did notice this issue on my instance.

This seems to be something that happen on and off, it's super inconsistent and goes away after a refresh.

My guess is that it's an issue on YouTube's end.

**Comment by SamantazFox** [comment] 2022-06-20 20:53
I found out why. It's because that part of the code doesn't fully use the innertube API, so it's gettign rate limited.

**Comment by TheFrenchGhosty** [comment] 2022-06-20 20:54
@SamantazFox I also noticed it on playlists... also if it's rate limited why is it gone after a refresh?

**Comment by SamantazFox** [comment] 2022-06-20 21:47
@TheFrenchGhosty because there is enough delay between two requests to the endpoint :)

**Comment by zlpynof** [comment] 2022-06-22 08:54
> @zlpynof On which server did you get that error?

yewtu.be, also tried on invidious.snopyta.org

**Comment by Rebmiami** [comment] 2022-06-29 12:53
I got the same error while trying to open /channel/UCaHT88aobpcvRFEuy4v5Clg/community on two instances (https://yewtu.be/ and https://invidious.esmailelbob.xyz/)

Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-06-29T12:48:45Z`
Route: `/channel/UCaHT88aobpcvRFEuy4v5Clg/community`
Version: `2022.06.13-6c73614 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '[]'
  from src/invidious/channels/community.cr:16:133 in 'fetch_channel_community'
  from src/invidious/routes/channels.cr:84:26 in 'community'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by Skidout** [comment] 2022-07-01 17:55
I am also getting the same error. It's on every channel and instance I tried, which is at least 5 of each. Also tried on two different devices (Windows and iOS) and browsers (Firefox and Brave)
Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-07-01T17:53:31Z`
Route: `/channel/UC4QZ_LsYcvcq7qOsOhpAX4A/playlists`
Version: `2022.06.13-6c73614 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '[]'
  from src/invidious/yt_backend/extractors_utils.cr:87:70 in 'process'
  from src/invidious/yt_backend/extractors.cr:640:8 in 'extract_items'
  from src/invidious/channels/playlists.cr:33:13 in 'fetch_channel_playlists'
  from src/invidious/routes/channels.cr:59:27 in 'playlists'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by hcording** [comment] 2022-07-02 15:25
Also consistently getting this error on /channel/UCV6mNrW8CrmWtcxWfQXy11g/playlists on the yewtu.be instance, regardless of browser and platform.

**Comment by TheFrenchGhosty** [comment] 2022-07-03 13:11
Duplicate of #3152

**Closed by TheFrenchGhosty** 2022-07-03 13:11 UTC
Labels: bug
