### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FreeBornAngel** [iv-org/invidious#3264] opened 2022-08-12 17:38 UTC
**Describe the bug**
Videos only play a few seconds at a time.

**Steps to Reproduce**
Open video, try to watch.

**Logs**
No issues flagged in console.

**Screenshots**
https://invidious.kavin.rocks/watch?v=Y_OyWFCI3IM&local=true&dark_mode=true

I use brave on linux mint.

**Additional context**
This has been an ongoing thing for months.,

**Comment by unixfox** [comment] 2022-08-12 18:30
Please post the instance used and the version of the instance.

**Comment by stephan-dev** [comment] 2022-08-12 19:18
Similar bug, on Linux Mint, too, since today. But I realized that I have the same problem on... dailymotion... and youtube. @FreeBornAngel : can you test on dailymotion and youtube ?

**Comment by FreeBornAngel** [comment] 2022-08-12 22:51
Sorry, I highlighted text and expected it to be overwritten, but it wasn't.

Current version: 2022.08.07-9cc0418 @ master

**Comment by unixfox** [comment] 2022-08-13 07:03
Does it work better on other public instances: https://instances.invidious.io?

**Comment by unixfox** [comment] 2022-08-14 07:38
Closing due to lack of replies.

And can't reproduce the issue on other instances.

**Closed by unixfox** 2022-08-14 07:38 UTC
Labels: bug

**Comment by FreeBornAngel** [comment] 2022-08-14 16:14
Yes, yewtu.be works just fine.
This instance pops up often through privacy redirect, https://chrome.google.com/webstore/detail/privacy-redirect/pmcmeagblkinmogikoikkdjiligflglb/related, but I just replace the url with yewtu.be and it works fine.
This instance plays a few seconds, stops, plays a few seconds, stops, not usable.
