### ISSUE TITLE
[Feature request] Custom Playback Speeds & Higher Playback speeds.

### ISSUE THREAD

**Issue by Box-boi** [iv-org/invidious#3377] opened 2022-11-01 02:46 UTC
**Describe the solution you'd like**

- Custom playback speed like newpipe. example (1.67x, 1.86x)
- Higher playback speeds like newpipe(upto 3x) or like youtube revanced(upto 5x)

**Comment by SamantazFox** [comment] 2022-11-02 17:39
Closing as a duplicate of #533

**Closed** 2022-11-02 20:59 UTC
Labels: duplicate, feature-request
