### ISSUE TITLE
[Feature request] [Usability] Add search button within the search bar 

### ISSUE THREAD

**Issue by cibolog** [iv-org/invidious#3010] opened 2022-04-08 05:48 UTC
Ditto. It's extremely frustrating when I """away""" from the keyboard with only mouse/touchpad to use - and I have no option to click the search button cause it does not exist.

**Comment by SamantazFox** [comment] 2022-04-08 20:10
Duplicate of #529

**Closed by SamantazFox** 2022-04-08 20:10 UTC
Labels: feature-request
