### ISSUE TITLE
"Looks like you've found a bug in Invidious"

### ISSUE THREAD

**Issue by hernanmd** [iv-org/invidious#2795] opened 2022-01-09 21:36 UTC
Just copy pasted a Youtube URL link https://youtube.com/playlist?list=OLAK5uy_nhbgb5jympXrXP_I3Obf_KE0iRL0Fx2rg

Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2022-01-09T21:33:49Z`
Route: `/playlist?list=OLAK5uy_nhbgb5jympXrXP_I3Obf_KE0iRL0Fx2rg`
Version: `2022.01.05-3bb7fbb2 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/pool.cr:177:11 in 'query:args'
  from lib/db/src/db/query_methods.cr:46:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:7 in 'query_one?:as'
  from src/invidious/database/playlists.cr:164:12 in 'exists?'
  from src/invidious/views/playlist.ecr:64:27 in 'show'
  from src/invidious.cr:318:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-01-09 22:00
which instance did you use?

**Comment by unixfox** [comment] 2022-01-09 22:03
Duplicate of https://github.com/iv-org/invidious/issues/1582

**Closed by unixfox** 2022-01-09 22:03 UTC

**Comment by hernanmd** [comment] 2022-01-09 22:16
> which instance did you use?

Just discovered this 3 minutes ago, I don't know how to find which instance I used sorry.
