### ISSUE TITLE
[Bug] Found this, was told to post here

### ISSUE THREAD

**Issue by uncle-phil** [iv-org/invidious#2714] opened 2021-12-10 18:59 UTC
**Describe the bug**

I went to invidious.xamh.de and looked into the preferences, changed the default front page to trending, but did not save, then went back in browser to the front page and manually selected trending. Then this message appeared:

Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-12-10T18:54:40Z`
Route: `/feed/trending`
Version: `2021.12.08-bace1fdc @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'to_i'
  from src/invidious/helpers/utils.cr:24:64 in 'decode_length_seconds'
  from src/invidious/yt_backend/extractors.cr:82:11 in 'parse'
  from src/invidious/yt_backend/extractors.cr:40:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:327:20 in 'parse'
  from src/invidious/yt_backend/extractors.cr:288:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:582:28 in 'extract_items'
  from src/invidious/yt_backend/extractors_utils.cr:33:3 in 'extract_videos'
  from src/invidious/trending.cr:19:3 in 'fetch_trending'
  from src/invidious/routes/feeds.cr:54:24 in 'trending'
  from src/invidious.cr:317:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Steps to Reproduce**

**Logs**

Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-12-10T18:54:40Z`
Route: `/feed/trending`
Version: `2021.12.08-bace1fdc @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'to_i'
  from src/invidious/helpers/utils.cr:24:64 in 'decode_length_seconds'
  from src/invidious/yt_backend/extractors.cr:82:11 in 'parse'
  from src/invidious/yt_backend/extractors.cr:40:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:327:20 in 'parse'
  from src/invidious/yt_backend/extractors.cr:288:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:582:28 in 'extract_items'
  from src/invidious/yt_backend/extractors_utils.cr:33:3 in 'extract_videos'
  from src/invidious/trending.cr:19:3 in 'fetch_trending'
  from src/invidious/routes/feeds.cr:54:24 in 'trending'
  from src/invidious.cr:317:1 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Screenshots**

**Additional context**

**Comment by unixfox** [comment] 2021-12-10 19:18
Duplicate of https://github.com/iv-org/invidious/issues/2708

**Closed by unixfox** 2021-12-10 19:18 UTC
Labels: bug
