### ISSUE TITLE
[Bug] DASH video causes video to never load.

### ISSUE THREAD

**Issue by Arcane-Cube** [iv-org/invidious#2661] opened 2021-11-25 14:59 UTC
**Describe the bug**

When using the 'DASH' video quality, the video never loads.

**Steps to Reproduce**
 Spinning circle for eternity.

**Logs**

Nothing unusual in the logs.
**Screenshots**

**Additional context**

**Comment by unixfox** [comment] 2021-11-25 16:22
Which instance are you using? Which video did you test?

**Comment by unixfox** [comment] 2021-11-27 17:42
Can't reproduce, closing due to a lack of replies.

**Comment by Arcane-Cube** [comment] 2021-11-28 00:22
> Which instance are you using? Which video did you test?

invidious.kavin.rocks

**Comment by unixfox** [comment] 2021-11-28 08:48
> > Which instance are you using? Which video did you test?
> 
> invidious.kavin.rocks

Then please try other instances from the list: https://api.invidious.io/ and tell us if it's working on the other ones.

**Comment by Arcane-Cube** [comment] 2021-11-30 17:11
> > > Which instance are you using? Which video did you test?
> > 
> > 
> > invidious.kavin.rocks
> 
> Then please try other instances from the list: https://api.invidious.io/ and tell us if it's working on the other ones.

It does not appear to be working on any of the other instances either.

**Comment by unixfox** [comment] 2021-11-30 17:35
> > > > Which instance are you using? Which video did you test?
> > > 
> > > 
> > > invidious.kavin.rocks
> > 
> > 
> > Then please try other instances from the list: [api.invidious.io](https://api.invidious.io/) and tell us if it's working on the other ones.
> 
> It does not appear to be working on any of the other instances either.

Could you please give us a bit more details than just "it's not working", you aren't helping us...

Your browser, if you have JS enabled or not, the extensions that you are using. And open your dev tools with F12 and post a screenshot of the "network" tab from the new window opened by the F12 key.

**Comment by Arcane-Cube** [comment] 2021-12-01 15:12
> > > > > Which instance are you using? Which video did you test?
> > > > 
> > > > 
> > > > invidious.kavin.rocks
> > > 
> > > 
> > > Then please try other instances from the list: [api.invidious.io](https://api.invidious.io/) and tell us if it's working on the other ones.
> > 
> > 
> > It does not appear to be working on any of the other instances either.
> 
> Could you please give us a bit more details than just "it's not working", you aren't helping us...
> 
> Your browser, if you have JS enabled or not, the extensions that you are using. And open your dev tools with F12 and post a screenshot of the "network" tab from the new window opened by the F12 key.

Sorry about that. I am using Brave browser on Windows 10, I do indeed have javascript enabled, the issue persists across browsers (tested with Firefox and Chrome). Here is the screenshot:
https://imgur.com/twWk9Mz

**Comment by SamantazFox** [comment] 2021-12-01 16:26
Does it happen on all videos, too? Is that some music video (like Vevo)?

**Comment by unixfox** [comment] 2021-12-01 16:39
Could you give us the video ID that you used?

**Comment by Moth-Tolias** [comment] 2021-12-10 08:31
i've been getting something similar, but changing to dash quality seems to have fixed it.

**Comment by nao20010128nao** [comment] 2021-12-10 11:00
I was able to reproduce possibly the same issue with this video: https://invidious.kavin.rocks/watch?v=SYFXiEVnUT0
Though I'd suggest to shut this issue.

OS: Ubuntu 21.04
Browser: Firefox 94.0

![image](https://user-images.githubusercontent.com/10355528/145563304-bf9710ea-f877-426b-8f7c-3ac6d60f7cec.png)

**Comment by unixfox** [comment] 2021-12-13 12:07
Unfortunately we can't really do anything, it's just the content that is encrypted on the youtube side.

**Closed by unixfox** 2021-12-13 12:07 UTC
Labels: not-reproducible
