### ISSUE TITLE
new bug report.

### ISSUE THREAD

**Issue by atemlaw** [iv-org/invidious#1518] opened 2020-12-01 19:54 UTC
Date: `2020-12-01T19:50:53Z`
Route: `/feed/trending`
Version: `0.20.1-dd35877 @ master`
Backtrace: 
```
Read timed out (IO::TimeoutError)
  from ../usr/lib/crystal/io/evented.cr:120:45 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:119:3 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:59:9 in 'unbuffered_read'
  from ../usr/lib/crystal/io/buffered.cr:239:12 in 'fill_buffer'
  from ../usr/lib/crystal/io/buffered.cr:82:9 in 'read'
  from lib/pool/src/pool.cr:53:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:7 in 'fetch_trending'
  from src/invidious.cr:1971:22 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/lib/crystal/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/lib/crystal/http/server.cr:513:5 in 'handle_client'
  from ../usr/lib/crystal/http/server.cr:468:13 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ../usr/lib/crystal/fiber.cr:92:34 in '->'
  from ???
```

**Comment by TheFrenchGhosty** [comment] 2020-12-01 21:35
Duplicate of: #1514

**Closed by TheFrenchGhosty** 2020-12-01 21:35 UTC
Labels: duplicate
