### ISSUE TITLE
English words when using other languages

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#455] opened 2019-03-27 23:00 UTC
When using any other language than English, some English words are still used : 

Some place where I noticed it (There's maybe more) : 

https://i.imgur.com/vtJfgWa.jpg

https://i.imgur.com/sOeIk7z.jpg

https://i.imgur.com/CjEbAhJ.png

**Comment by elypter** [comment] 2019-03-28 02:24
add "search" in the search field to the list

**Comment by omarroth** [comment] 2019-04-15 00:49
The login text should be fixed with 05513bcd1e45584137143570980d8d636f9e2816.

@elypter You'll have to clarify what you're referring to. The "search" placeholder appears to be translated correctly for me and in the screenshots provided.

**Comment by elypter** [comment] 2019-04-15 01:41
it is now working as intended now. maybe i missed the fix or the fix was recent. anyway, great job!

**Comment by CSDUMMI** [comment] 2019-05-04 10:24
Could you please close this issue, if it is fixed?

**Comment by omarroth** [comment] 2019-05-04 15:31
Translations are still missing for dates (`October 24, 2009` in the example), which is why this hasn't been closed yet.

**Comment by CSDUMMI** [comment] 2019-05-06 12:27
I think I have another translation issue:
On changing the language to german (de)
the "Show annotations" link didn't change.

**Comment by CSDUMMI** [comment] 2019-05-06 12:33
I noted that many fields in de.json are empty, why is that?

**Comment by omarroth** [comment] 2019-05-06 12:35
Empty fields means those phrases haven't been translated yet. Support for annotations was merged a couple days ago so likely "Show annotations" and related text haven't been translated.

**Comment by CSDUMMI** [comment] 2019-05-06 12:38
So, could I help with translating or who translates?

**Comment by omarroth** [comment] 2019-05-06 12:41
Please do! If it's easier for you you can use [Weblate](https://hosted.weblate.org/projects/invidious/translations/) or you can translate the file directly and open a PR.

**Comment by CSDUMMI** [comment] 2019-05-06 13:40
Auto translation is no option?

**Comment by CSDUMMI** [comment] 2019-05-06 13:57
Otherwise:
Could you link Weblate or any other way to help
the development of Invidious in the footer?

**Comment by omarroth** [comment] 2019-05-17 19:07
Sure, there's been mention of an `/about` page (see #227) which would be a good place for providing more information for translators.

**Comment by TheFrenchGhosty** [comment] 2019-10-17 03:01
> Translations are still missing for dates (`October 24, 2009` in the example), which is why this hasn't been closed yet.

Player controls are also missing translations

**Comment by TheFrenchGhosty** [comment] 2020-12-02 16:21
Still an issue.

**Comment by SamantazFox** [comment] 2021-09-02 11:00
Closing in favor of #1951.

**Closed** 2021-09-02 11:05 UTC
Labels: bug, type:client-side
