### ISSUE TITLE
[Feature request] Add a "Search" / "Go" button to the default frontend

### ISSUE THREAD

**Issue by jpodolski** [iv-org/invidious#4855] opened 2024-08-16 23:21 UTC
- **Is your feature request related to a problem? Please describe.**
I will occasionally use Invidious on a flip phone that can only navigate the web with "mouse" inputs, and by typing into text fields; there is no "return" or "enter" key when interacting with a page. This means I can type into the searchbar, but I cannot submit my query.

- **Describe the solution you'd like**
Altering the GUI to include a "go" or "search" button next to the search input field that submits the search query when pressed.

- **Describe alternatives you've considered**
Currently, I search on youtube.com to load a video, then replace the FQDN in my address bar with that of my preferred instance. I will try to submit this change myself if I have time since it is a simple, small request that mostly benefits me.

Thank you developers for all your hard work--I have donated to the project and I hope to try running my own instance soon.

**Comment by ChunkyProgrammer** [comment] 2024-08-20 06:44
I think this will be fixed when https://github.com/iv-org/invidious/pull/4706 gets merged

**Comment by syeopite** [comment] 2024-08-20 07:12
Duplicate of #529

**Closed by syeopite** 2024-08-20 07:12 UTC
Labels: feature-request
