### ISSUE TITLE
Error when logging in with Google

### ISSUE THREAD

**Issue by Kwinnieprince** [iv-org/invidious#1304] opened 2020-07-27 10:47 UTC
```
Expected Array for #[](index : Int), not Int64
Traceback:
Getting lookup...done, returned 404.
Getting challenge...done, returned 400.
```
I get this message with Safari and Firefox developer edition
invidious returns an 500 error and does not place any cookies for google

**Comment by Perflyst** [comment] 2020-07-31 19:09
Duplicate of #754

**Closed by Perflyst** 2020-07-31 19:09 UTC
Labels: bug
