### ISSUE TITLE
[Bug] Search failure: Invalid Int32: "@SomeUsername"

### ISSUE THREAD

**Issue by deriv** [iv-org/invidious#3394] opened 2022-11-15 12:08 UTC
**Describe the bug**
I was searching for content, and instead of seeing results of the search, invidious reported a bug being found.

**Steps to Reproduce**
I was not able to reproduce the error. It was the very first time ever seeing such an issue with any Invidious-instance.

**Logs**

Title: `Invalid Int32: "@RealLifeLore" (ArgumentError)`
Date: `2022-11-15T11:51:52Z`
Route: `/search?q=reallifelore`
Version: `2022.11.02-09942de @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@RealLifeLore" (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Screenshots**

**Additional context**

Browser: Firefox 106.0.5
Instance: https://invidious.namazso.eu

**Comment by tirz** [comment] 2022-11-16 22:35
Title: `Invalid Int32: "@LowkoTV" (ArgumentError)`
Date: `2022-11-16T22:21:35Z`
Route: `/search?q=lowko`
Version: `2022.10.25-0c7919f @ master`

<details>
<summary>Backtrace</summary>
<p>
```
Invalid Int32: "@LowkoTV" (ArgumentError)
  from /usr/lib/crystal/core/int.cr:957:11 in 'to_i32'
  from /usr/lib/crystal/core/string.cr:333:5 in 'short_text_to_number'
  from /invidious/src/invidious/yt_backend/extractors.cr:172:20 in 'process'
  from /invidious/src/invidious/yt_backend/extractors.cr:615:17 in 'extract_item'
  from /invidious/src/invidious/yt_backend/extractors.cr:646:28 in 'extract_items'
  from /invidious/src/invidious/search/processors.cr:12:14 in 'process'
  from /invidious/src/invidious/routes/search.cr:55:18 in 'search'
  from /invidious/src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /invidious/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /invidious/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

I think I had the same bug.
It seems to be triggered while parsing the link to a channel (and not by the list of videos).

**Comment by SamantazFox** [comment] 2022-11-18 00:01
Thanks for the report! Though, I'm unable to reproduce... Maybe some Youtube A/B testing?

**Comment by tempname1024** [comment] 2022-11-18 10:01
Title: `Invalid Int32: "@ThenNow" (ArgumentError)`
Date: `2022-11-18T09:56:42Z`
Route: `/search?q=then+and+now`
Version: `2022.11.17-516efd2d @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@ThenNow" (ArgumentError)
  from /usr/lib/crystal/core/int.cr:957:11 in 'to_i32'
  from /usr/lib/crystal/core/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

Ran into this today as well, resolved upon refresh.

**Comment by irimi1** [comment] 2022-11-19 08:14
I encountered the same bug when searching for `colelangs`. I found that it was reproducible about 30-40% of the times I tried, the instance I use is iv.catgirl.cloud (for quickly reproducing maybe). The term searched doesn’t seem to matter.

Title: `Invalid Int32: "@ColeLangs" (ArgumentError)`
Date: `2022-11-19T08:09:30Z`
Route: `/search?q=colelangs`
Version: `2022.11.02-09942dee @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@ColeLangs" (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'to_i'
  from src/invidious/helpers/utils.cr:176:12 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'parse'
  from src/invidious/yt_backend/extractors.cr:159:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'regular'
  from src/invidious/search/query.cr:116:30 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/routing.cr:162:20 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-11-19 09:54
Yay, I managed to get a faulty search repeatedly, and to extract the JSON!

Here is what a normal reponse should look like:
```json
"channelRenderer": {
  "channelId": "UCLam0sFSS0qA_DXGXsn8YGA",
  "title": {
    "simpleText": "AERO CHORD"
  },
  "navigationEndpoint": {...},
  "thumbnail": {...},
  "descriptionSnippet": {...},
  "shortBylineText": {...},

  // 76 videos -> good
  "videoCountText": {
    "runs": [
      {
        "text": "76"
      },
      {
        "text": " videos"
      }
    ]
  },

  "subscriptionButton": {
    "subscribed": false
  },
  "ownerBadges": [...],

  // 116k subs -> good
  "subscriberCountText": {
    "accessibility": {
      "accessibilityData": {
        "label": "116K subscribers"
      }
    },
    "simpleText": "116K subscribers"
  },

  "subscribeButton": {...},
  "longBylineText": {...}
}
```

Here's what a faulty one looks like:
```json
"channelRenderer": {
  "channelId": "UCLam0sFSS0qA_DXGXsn8YGA",
  "title": {
    "simpleText": "AERO CHORD"
  },
  "navigationEndpoint": {...},
  "thumbnail": {...},
  "descriptionSnippet": {...},
  "shortBylineText": {...},

  // video count = 116k subs ???
  "videoCountText": {
    "accessibility": {
      "accessibilityData": {
        "label": "116K subscribers"
      }
    },
    "simpleText": "116K subscribers"
  },

  "subscriptionButton": {
    "subscribed": false
  },
  "ownerBadges": [...],

  // subs count = yes.
  "subscriberCountText": {
    "simpleText": "@TheAeroChord"
  },

  "subscribeButton": {...},
  "longBylineText": {...}
}
```

**Comment by zseri** [comment] 2022-11-19 12:22
Can the search be made a bit more tolerant regarding malformed search entries, such that all parsable entries get returned, and a option is presented to report the unparsable ones (preferably including their raw content to figure out what's wrong)?

**Comment by drago333** [comment] 2022-11-19 16:01
Keep getting the error in the last 45 mins with different search strings. Search completely unusable.

**Comment by piquark6046** [comment] 2022-11-20 10:33
Title: `Invalid Int32: "@komq" (ArgumentError)`
Date: `2022-11-20T10:27:35Z`
Route: `/search?q=%EC%BD%94%EB%A7%88`
Version: `2022.11.17-e726eaf @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@komq" (ArgumentError)
  from /usr/lib/crystal/core/int.cr:957:11 in 'to_i32'
  from src/invidious/helpers/utils.cr:176:3 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:56:7 in 'search'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-11-20 21:50
Yup, it's utterly inconsistent (Thanks YT). but at least, I've a quick fix done:

![image](https://user-images.githubusercontent.com/52980486/202927996-6e38558e-e20f-426f-9c9f-1a3697f3135d.png) ![image](https://user-images.githubusercontent.com/52980486/202928011-ba2fe76e-0a4c-4487-a4d2-910e6072ad7a.png)

**Comment by SamantazFox** [comment] 2022-11-20 22:32
It looks like they're repurposing the fields to change what's displayed in the search results without having to change other code (like client JS)?
![image](https://user-images.githubusercontent.com/52980486/202928669-b2508b1b-cb30-448e-9a6a-6d6c1c78fc11.png)

Though, it seems that the results on YT are very consistent (by that I mean "always broken", i.e `VideoCountText` has the number of subs and `subscriberCountText` has the handle).

**Comment by GageeGh0stt** [comment] 2022-12-08 22:55
I'm having this issue as well! :( 
I was trying to look up my favorite music artist today and it gave me this message. I hope it can be fixed soon! No pressure tho! :))) 

![image](https://user-images.githubusercontent.com/120141583/206584044-83f70e88-2a16-448d-9f02-b194a18e3d39.png)

[https://youtube.076.ne.jp/watch?v=vZWfEqqfDaM](url)

**Comment by alejandroandreu** [comment] 2022-12-20 09:36
Not sure if relevant, but I'll add this happens on my RPi instance and NOT on some public instances. Therefore, I think it might be related to the arm64 architecture?

**Comment by unixfox** [comment] 2022-12-20 10:07
It happens on all the invidious instances, whenever they are running arm64 or not.

**Comment by zseri** [comment] 2022-12-20 15:53
@alejandroandreu https://github.com/iv-org/invidious/issues/3394#issuecomment-1321261688 it's just youtube search results are seemingly getting fudged to avoid messing with the frontend youtube code, but which impacts other frontends which then can't easily parse the results anymore.

**Comment by pH142857** [comment] 2022-12-22 21:55
Same bug I think:

Title: `Invalid Int32: "@ScienceEtonnante" (ArgumentError)`
Date: `2022-12-22T21:52:41Z`
Route: `/search?q=science+%C3%A9tonnante`
Version: `2022.11.17-516efd2d @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@ScienceEtonnante" (ArgumentError)
  from /usr/share/crystal/src/string.cr:422:83 in 'to_i32'
  from src/invidious/yt_backend/extractors.cr:172:26 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:36 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by alejandroandreu** [comment] 2023-01-02 10:10
You're totally right @unixfox . I arrived to that conclusion since I couldn't reproduce this issue in many public instances. Then I realized what was different _on my end_: Docker image with tag `latest-arm64` has an older version of Invidious than `latest`.

I then proceeded to build the Docker image myself on my Raspberry Pi with the following command (on `master`):
```sh
sudo docker build -f docker/Dockerfile.arm64 --build-arg release=1 --build-arg disable_quic=1 .
```

My Invidious version is now: `2022.11.22-5160d8ba @ master`

Search queries that would make Invidious break before are now working. The issue might not be _completely_ resolved in this version, but at least it fixed the issues I was personally facing.

**Comment by unixfox** [comment] 2023-01-02 11:07
> You're totally right @unixfox . I arrived to that conclusion since I couldn't reproduce this issue in many public instances. Then I realized what was different _on my end_: Docker image with tag `latest-arm64` has an older version of Invidious than `latest`.

That's not true, `latest-arm64` is at the same version of the tag `latest`:
![image](https://user-images.githubusercontent.com/4016501/210222894-68b32610-06be-422c-a9dd-e03fb5885ef0.png)

source: https://quay.io/repository/invidious/invidious?tab=tags

> Search queries that would make Invidious break before are now working. The issue might not be _completely_ resolved in this version, but at least it fixed the issues I was personally facing.

Please take my word for it, like I said in https://github.com/iv-org/invidious/issues/3394#issuecomment-1359117371, this is issue **IS NOT** architecture dependent. It happens on all the docker images of invidious. It's just random.

**Comment by mk-pmb** [comment] 2023-01-03 17:29
Is this bug about the new URL "at username" style for user channel URLs, like https://yewtu.be/@Jules1 ? Or should I open a new feature request for their support?

**Comment by SamantazFox** [comment] 2023-01-03 21:18
@mk-pmb  This issue is about the `Invalid Int32` error on the search page.

For the support of `.../@username` URLs, please see #3358.

**Comment by DUOLabs333** [comment] 2023-01-04 01:29
This issue seems to be superseded by #3460 (this no longer happens to me).

**Comment by SamantazFox** [comment] 2023-01-22 23:31
Closing, as the problem was fixed

**Closed by SamantazFox** 2023-01-22 23:31 UTC
Labels: bug, type:youtube-change, module:search
