### ISSUE TITLE
Read timed out (IO::TimeoutError)

### ISSUE THREAD

**Issue by Zani1** [iv-org/invidious#1680] opened 2021-01-18 12:37 UTC
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-01-18T12:22:35Z`
Route: `/embed/mCZq66Ks1ZI?enablejsapi=1&origin=https%3A%2F%2Fwww.cyber-knife.net&autoplay=0&continue=0&dark_mode=true&hl=de&listen=0&local=1&loop=0&nojs=0&player_style=youtube&quality=medium&thin_mode=false`
Version: `2021.01.14-900e3bb @ serving3`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from ../../../usr/share/crystal/src/gc/boehm.cr:110:5 in 'unbuffered_read'
  from ../../../usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from ../../azhao/invidious/lib/pool/src/pool.cr:55:7 in 'checkout'
  from ../../azhao/invidious/src/invidious/helpers/utils.cr:33:14 in 'get_video:region'
  from ../../azhao/invidious/src/invidious/routes/embed/show.cr:96:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-01-18 13:10
This appears to be a duplicate of #1508. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-01-18 16:55 UTC
Labels: duplicate

**Comment by Zani1** [comment] 2021-01-18 21:44
I am sorry, I just did what the instructions on my screen said: 
start a new issue and copy/paste the text below. 
I am no programmer and do not have any clue what in detail this is all about.
Please feel free to close the issue. THX
