### ISSUE TITLE
[Bug] Community posts do not display the author name

### ISSUE THREAD

**Issue by ChunkyProgrammer** [iv-org/invidious#3523] opened 2022-12-30 15:50 UTC
**Describe the bug**
Community posts do not display the author name

**Steps to Reproduce**
1. Go to https://redirect.invidious.io/channel/UCYVU6rModlGxvJbszCclGGw/community
2. See empty name

**Screenshots**
![image](https://user-images.githubusercontent.com/78101139/210088392-347890dd-11cd-4116-9a13-74e36d313cb4.png)

**Comment by unixfox** [comment] 2022-12-30 16:50
Duplicate of https://github.com/iv-org/invidious/issues/1612

**Closed by unixfox** 2022-12-30 16:50 UTC
Labels: bug
