### ISSUE TITLE
Read timed out (IO::TimeoutError)

### ISSUE THREAD

**Issue by darklighskully** [iv-org/invidious#1508] opened 2020-12-01 01:36 UTC
Date: `2020-12-01T01:31:13Z`
Route: `/watch?v=pQkCajVVozY&list=IVPLdUMKCAApvVwyDyfjZY5mWAKEjRcVObN`
Version: `0.20.1-4acfd2c @ master`
Backtrace: 
```
Read timed out (IO::TimeoutError)
  from ../usr/lib/crystal/io/evented.cr:120:45 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:119:3 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:59:9 in 'unbuffered_read'
  from ../usr/lib/crystal/io/buffered.cr:239:12 in 'fill_buffer'
  from ../usr/lib/crystal/io/buffered.cr:82:9 in 'read'
  from lib/pool/src/pool.cr:53:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:7 in 'fetch_video'
  from src/invidious/videos.cr:943:13 in 'get_video'
  from src/invidious/videos.cr:926:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:53:15 in 'handle'
  from src/invidious.cr:299:1 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/lib/crystal/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/lib/crystal/http/server.cr:513:5 in 'handle_client'
  from ../usr/lib/crystal/http/server.cr:468:13 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ../usr/lib/crystal/fiber.cr:92:34 in '->'
  from ???
```
what does it mean?

**Comment by saltycrys** [comment] 2020-12-01 10:54
Thank you for your bug report!

This is the oldest report so here's a collection of the duplicates:
- https://github.com/iv-org/invidious/issues/1510 on `/watch` route
- https://github.com/iv-org/invidious/issues/1511 on `/channel` route
- https://github.com/iv-org/invidious/issues/1512 on `/feed/trending` route

**Comment by rex4539** [comment] 2020-12-02 12:38
Title: `Read timed out (IO::TimeoutError)`
Date: `2020-12-02T12:35:46Z`
Route: `/channel/UCiJiqEvUZxT6isIaXK7RXTg`
Version: `2020.12.01-ff3b53e @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from ../usr/lib/crystal/io/evented.cr:120:45 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:119:3 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:59:9 in 'unbuffered_read'
  from ../usr/lib/crystal/io/buffered.cr:239:12 in 'fill_buffer'
  from ../usr/lib/crystal/io/buffered.cr:82:9 in 'read'
  from lib/pool/src/pool.cr:53:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:7 in 'get_about_info'
  from src/invidious.cr:2475:15 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/lib/crystal/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/lib/crystal/http/server.cr:513:5 in 'handle_client'
  from ../usr/lib/crystal/http/server.cr:468:13 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ../usr/lib/crystal/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by FireMasterK** [comment] 2020-12-03 17:57
This is a duplicate of #1132?

**Comment by TheFrenchGhosty** [comment] 2020-12-03 23:45
@FireMasterK Previous issues didn't affect the frontend, this one is actually displayed in the frontend, instead of the content.

**Comment by FireMasterK** [comment] 2020-12-05 06:36
Here's one when fetching comments.

```
{"error":"Read timed out","errorBacktrace":"Read timed out (IO::TimeoutError)\n  from ../usr/share/crystal/src/io/evented.cr:120:45 in 'wait_readable'\n  from ../usr/share/crystal/src/io/evented.cr:119:3 in 'wait_readable'\n  from ../usr/share/crystal/src/io/evented.cr:59:9 in 'unbuffered_read'\n  from ../usr/share/crystal/src/io/buffered.cr:239:12 in 'fill_buffer'\n  from ../usr/share/crystal/src/io/buffered.cr:82:9 in 'read'\n  from lib/pool/src/pool.cr:53:7 in 'checkout'\n  from src/invidious/helpers/utils.cr:33:7 in 'fetch_youtube_comments'\n  from src/invidious.cr:2789:18 in '->'\n  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'\n  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'\n  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:212:5 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:94:12 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:158:7 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/handlers.cr:70:5 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from src/invidious/helpers/logger.cr:16:5 in 'call'\n  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'\n  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'\n  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'\n  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'\n  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'\n  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'\n  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'\n  from ???\n"}
```

**Comment by 7415963987456321** [comment] 2020-12-06 00:52
Got a similar one when selecting the News category: 
Title: `Read timed out (IO::TimeoutError)`
Date: `2020-12-06T00:50:50Z`
Route: `/feed/trending?type=News®ion=US`
Version: `-64c6dfd @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from ../usr/lib/crystal/io/evented.cr:120:45 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:119:3 in 'wait_readable'
  from ../usr/lib/crystal/io/evented.cr:59:9 in 'unbuffered_read'
  from ../usr/lib/crystal/io/buffered.cr:239:12 in 'fill_buffer'
  from ../usr/lib/crystal/io/buffered.cr:82:9 in 'read'
  from lib/pool/src/pool.cr:53:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:7 in 'fetch_trending'
  from src/invidious.cr:1912:22 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/lib/crystal/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/lib/crystal/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/lib/crystal/http/server.cr:513:5 in 'handle_client'
  from ../usr/lib/crystal/http/server.cr:468:13 in '->'
  from ../usr/lib/crystal/primitives.cr:255:3 in 'run'
  from ../usr/lib/crystal/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by johan-bjareholt** [comment] 2020-12-11 06:42
Here's one when I opened a link to a video from an external site

Title: `Read timed out (IO::TimeoutError)`
Date: `2020-12-11T06:38:06Z`
Route: `/watch?v=GSudn0qB6u0`
Version: `2020.12.04-527f408 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from ../../../usr/share/crystal/src/gc/boehm.cr:110:5 in 'unbuffered_read'
  from ../../../usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from lib/pool/src/pool.cr:55:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:14 in 'get_video:region'
  from src/invidious/routes/watch.cr:53:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from src/invidious/helpers/logger.cr:17:33 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by stemy2** [comment] 2021-01-04 12:05
```
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-01-04T12:01:53Z`
Route: `/watch?v=XVdv3Vtgous&local=true&dark_mode=true&autoplay=0`
Version: `2021.01.03-28dac81 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from ../../../usr/share/crystal/src/gc/boehm.cr:110:5 in 'unbuffered_read'
  from ../../../usr/share/crystal/src/io/buffered.cr:240:5 in 'read'
  from lib/pool/src/pool.cr:55:7 in 'checkout'
  from src/invidious/helpers/utils.cr:33:14 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>
```

**Comment by stemy2** [comment] 2021-01-14 19:26
If i restart the invidious service, the problem disappears (temporarly ?).

**Comment by L1pE** [comment] 2021-05-31 17:56
Clicked timestamped link. At first was a "500 internal server error" in a blank page, after refresh this came up.
Title: `Read timed out (IO::TimeoutError)`
Date: `2021-05-31T17:51:30Z`
Route: `/watch?v=XS0p670-Td8&t=246&local=true&quality=dash&dark_mode=true&volume=50&autoplay=0`
Version: `2021.05.26-4a45d10 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Read timed out (IO::TimeoutError)
  from /usr/share/crystal/src/io/evented.cr:135:5 in 'wait_readable'
  from /usr/share/crystal/src/io/evented.cr:119:3 in 'wait_readable'
  from /usr/share/crystal/src/io/evented.cr:59:9 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:239:12 in 'fill_buffer'
  from /usr/share/crystal/src/io/buffered.cr:82:9 in 'read'
  from lib/pool/src/pool.cr:53:7 in 'checkout'
  from src/invidious/helpers/utils.cr:35:7 in 'fetch_video'
  from src/invidious/videos.cr:956:13 in 'get_video'
  from src/invidious/videos.cr:939:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from src/invidious.cr:282:1 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-04-17 21:32
This issue seems to be fixed.

**Closed by unixfox** 2022-04-17 21:32 UTC
Labels: bug, type:server-side
