### ISSUE TITLE
[Bug] Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)

### ISSUE THREAD

**Issue by gax1985** [iv-org/invidious#4024] opened 2023-08-01 02:08 UTC
Title: `Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)`
Date: `2023-08-01T02:02:05Z`
Route: `/feed/trending`
Version: `2023.04.10-961cae2 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)
  from /usr/share/crystal/src/socket/addrinfo.cr:132:7 in 'initialize'
  from /usr/share/crystal/src/gc/boehm.cr:192:5 in 'io'
  from /usr/share/crystal/src/http/client.cr:671:5 in 'send_request'
  from /usr/share/crystal/src/http/client.cr:651:20 in '_post_json'
  from src/invidious/trending.cr:20:14 in 'trending'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2023-08-01 05:58
Duplicate of #3821

---

This is a DNS issue on your end.

**Closed by syeopite** 2023-08-01 05:58 UTC
Labels: bug
