### ISSUE TITLE
[Bug] Youtube Import Fails

### ISSUE THREAD

**Issue by thunderclap82** [iv-org/invidious#2404] opened 2021-09-15 01:47 UTC
I was trying to import my subscription csv file when the following error popped up and said I should report it here.

```
Title: `Unexpected char 'C' at line 1, column 1 (JSON::ParseException)`
Date: `2021-09-15T01:42:54Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2021.09.13-947fe4f @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char 'C' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/lexer.cr:376:7 in 'raise'
  from /usr/share/crystal/src/json/lexer.cr:372:5 in 'unexpected_char'
  from /usr/share/crystal/src/json/lexer.cr:371:11 in 'unexpected_char'
  from /usr/share/crystal/src/slice.cr:225:5 in 'next_token'
  from /usr/share/crystal/src/json/parser.cr:13:12 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>
```

**Comment by syeopite** [comment] 2021-09-15 01:48
Duplicate of #2319

**Closed by syeopite** 2021-09-15 01:48 UTC
Labels: bug
