### ISSUE TITLE
[Bug] Missing hash key: "selected" (KeyError)

### ISSUE THREAD

**Issue by MINETUBE02** [iv-org/invidious#3172] opened 2022-06-30 19:06 UTC
**Describe the bug**

**Steps to Reproduce**

1. Go to https://yewtu.be/channel/UC_aEa8K-EOJ3D6gOs7HcyNg/playlists
2. See error.

**Logs**

Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-06-30T18:53:45Z`
Route: `/channel/UC_aEa8K-EOJ3D6gOs7HcyNg/playlists`
Version: `2022.06.30-dabc3fe @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/lib/crystal/core/json/any.cr:100 in '[]'
  from /usr/lib/crystal/core/json/any.cr:155:3 in 'process'
  from src/invidious/yt_backend/extractors.cr:640:20 in 'extract_items'
  from src/invidious/channels/playlists.cr:34:20 in 'fetch_channel_playlists'
  from src/invidious/routes/channels.cr:59:27 in 'playlists'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Screenshots**

![Screenshot 2022-06-30 115534](https://user-images.githubusercontent.com/55697597/176757664-8f19dff3-be32-46c2-99bd-d13aa7c326e4.png)

**Additional context**

 - Browser Chrome
 - OS Windows 10 Pro x64
 - Version 20H2
 - OS Build 19042.985

**Comment by unixfox** [comment] 2022-06-30 19:45
Duplicate of https://github.com/iv-org/invidious/issues/3154

**Closed by unixfox** 2022-06-30 19:45 UTC
Labels: bug
