### ISSUE TITLE
Some videos can't be played 

### ISSUE THREAD

**Issue by aleemaheer** [iv-org/invidious#4072] opened 2023-08-25 06:35 UTC
Api is returning all video parameters correctly.
But video is not playing in any format.
This problem is with some videos not specifically to all videos of specific channels

Here is a link you can check which is not playing.
https://yewtu.be/watch?v=ACaXjBohgNE

**Comment by nurdyAuv** [comment] 2023-08-25 18:31
This video works fine on my personal instance. 

But does not work on: vid.priv, invidious.no-logs or yewtu.be. 
It could be something as simple as they haven't updated those instances yet, I know the latest release fixed a lot of player issues I was having.

**Comment by syeopite** [comment] 2023-08-25 18:37
Duplicate of #4045

**Comment by syeopite** [comment] 2023-08-25 18:44
> https://yewtu.be/watch?v=ACaXjBohgNE

Actually this looks more like a case of geo-restrictions. If you enable proxy/dash the video works. 

Related: #92

**Closed** 2023-08-25 18:44 UTC
Labels: bug

**Comment by unixfox** [comment] 2023-08-25 19:06
It's an issue only on yewtu.be, I'm looking into a fix.

**Comment by unixfox** [comment] 2023-08-25 20:57
Sorry for the troubles! It's fixed on yewtu.be
