### ISSUE TITLE
[Bug] Exception raised when video title contains emoji

### ISSUE THREAD

**Issue by mascali33** [iv-org/invidious#2691] opened 2021-12-02 01:23 UTC
**Describe the bug**

When launching a video with an emoji in the title, it raises an exception, same behavior occurs when searching a video and an emoji is in a title

**Steps to Reproduce**

1. Go to an instance of indivious
2. Search for a video with emojis, or access it with the "v" param
3. Exception

**Logs**

Title: `Unexpected char '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-12-02T01:13:50Z`
Route: `/watch?v=GAjSIarxKmc`
Version: `2021.12.01-438b3343 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '' at line 1, column 1 (JSON::ParseException)
  from /usr/lib/crystal/core/json/lexer.cr:116:0 in 'raise'
  from /usr/lib/crystal/core/json/lexer.cr:330:0 in 'unexpected_char'
  from /usr/lib/crystal/core/json/lexer.cr:326:11 in 'unexpected_char'
  from /usr/lib/crystal/core/json/lexer.cr:243:10 in 'consume_number'
  from /usr/lib/crystal/core/json/lexer.cr:63:7 in 'next_token'
  from /usr/lib/crystal/core/json/parser.cr:108:11 in 'next_token'
  from /usr/lib/crystal/core/json/parser.cr:9:5 in 'initialize'
  from /usr/lib/crystal/core/json/parser.cr:6:3 in 'new'
  from /usr/lib/crystal/core/json.cr:135:5 in 'parse'
  from src/invidious/yt_backend/youtube_api.cr:438:20 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'player:video_id:params:client_config'
  from src/invidious/videos.cr:834:3 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:978:3 in 'fetch_video'
  from src/invidious/videos.cr:968:13 in 'get_video'
  from src/invidious/videos.cr:951:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from src/invidious.cr:317:1 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/lib/crystal/core/http/server/request_processor.cr:51:11 in 'process'
  from /usr/lib/crystal/core/http/server.cr:515:5 in 'handle_client'
  from /usr/lib/crystal/core/http/server.cr:468:13 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /usr/lib/crystal/core/fiber.cr:92:34 in '->'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Additional context**

- Chrome v96
- ArchLinux (kernel 5.15.5)

Indivious instance runs on arm64

**Comment by mascali33** [comment] 2021-12-02 01:33
Looks like the error doesn't occur consistently :\ tried other videos and even the same video and it works??
Anyway, this should be investigated as it happens sometimes :\

**Comment by SamantazFox** [comment] 2021-12-02 01:49
This is a duplicate of #2612.
FYI: the problem has nothing to do with emojis. It is due do a bug in the HTTP library which doesn't properly decompress the response from youtube servers.

If you own the instance, you can try #2677 :)

**Closed by SamantazFox** 2021-12-02 01:49 UTC
Labels: bug
