### ISSUE TITLE
Previews are not showing up

### ISSUE THREAD

**Issue by armin567ip** [iv-org/invidious#4039] opened 2023-08-08 17:31 UTC
Hi. I self hosted Invidious on my Ubuntu VPS server. All things are good but there is a problem. When I play a video and I move my mouse over the timeline . It has to show the previews of the next minutes of the video. but it shows nothing. should I enable it or sth?

**Comment by armin567ip** [comment] 2023-08-08 17:37
one more question. how can i enable open in new tab for videos. I noticed its enable on some public instances but for me its not.
On my instance when I right click on the videos the option called "Open video in new tab" is not enabled

**Comment by markozajc** [comment] 2023-08-09 23:52
> one more question. how can i enable open in new tab for videos. I noticed its enable on some public instances but for me its not. On my instance when I right click on the videos the option called "Open video in new tab" is not enabled

"Open video in new tab" is enabled on hd720/medium quality videos and disabled on DASH quality videos. That's because DASH streams the video in chunks, which means the video source is a blob URL that can't be opened in a standalone tab. If you want to open videos like that, you can add `&quality=hd720` to the end of the URL or change the preferred video quality to hd720 in the settings, but that will limit you to 1280×720 picture resolution.

**Comment by armin567ip** [comment] 2023-08-10 05:56
> > one more question. how can i enable open in new tab for videos. I noticed its enable on some public instances but for me its not. On my instance when I right click on the videos the option called "Open video in new tab" is not enabled
> 
> "Open video in new tab" is enabled on hd720/medium quality videos and disabled on DASH quality videos. That's because DASH streams the video in chunks, which means the video source is a blob URL that can't be opened in a standalone tab. 
> 
> If you want to open videos like that, you can add `&quality=hd720` to the end of the URL or change the preferred video quality to hd720 in the settings, but that will limit you to 1280×720 picture resolution.

Thank you. Can you also tell me about this preview thing. I also tried a public instance. Wasn't showing any preview. Is the problem with Invidious or what?

**Comment by syeopite** [comment] 2023-08-10 07:27
Unfortunately it is. #4037 introduced a regression that broke previews. Once #4040 is merged it should be fixed. 

Can you try compiling #4040? Once video cache clears the video previews should be working again

**Comment by syeopite** [comment] 2023-08-27 07:28
Fixed by #4040

**Closed by syeopite** 2023-08-27 07:28 UTC
Labels: bug
