### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pilotcorocoro** [iv-org/invidious#2414] opened 2021-09-19 15:58 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

Title: `cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)`
Date: `2021-09-19T15:55:00Z`
Route: `/data_control?referer=%2Ffeed%2Fsubscriptions`
Version: `2021.09.19-87f46a7 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/share/crystal/src/json/any.cr:228:5:228 (TypeCastError)
  from /usr/share/crystal/src/json/any.cr:228:5 in 'as_a'
  from src/invidious.cr:823:33 in '->'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>
**Screenshots**

**Additional context**
< the subscriptions come from yewtu.be >
 - Browser (if applicable):firefox
 - OS (if applicable):linux
-->

**Comment by unixfox** [comment] 2021-09-19 15:58
Duplicate of https://github.com/iv-org/invidious/issues/2319

**Closed by unixfox** 2021-09-19 15:58 UTC
Labels: bug
