### ISSUE TITLE
[Bug] materialized view "subscriptions_b9fc8ea879dd53b8354c0de303229b2c120e80f469353b2f5" has not been populated (PQ::PQError)

### ISSUE THREAD

**Issue by DayOfCats** [iv-org/invidious#3125] opened 2022-05-27 14:51 UTC
**Describe the bug**

I can't load subscription videos unless they are notifications.

**Steps to Reproduce**
`materialized view "subscriptions_b9fc8ea879dd53b8354c0de303229b2c120e80f469353b2f5" has not been populated (PQ::PQError)`

**Logs**

INVIDIOUS

search
deathwillcome
LOG OUT
It looks like you found a bug in Invidious!

Before reporting a bug, make sure that you have:

tried to refresh the page
tried to use another instance
read the Frequently Asked Questions (FAQ)
searched for existing issues on GitHub

If none of the above helped, please open a new issue on GitHub (preferably in English) and include the following text in your message (do NOT translate that text):

Title: `materialized view "subscriptions_b9fc8ea879dd53b8354c0de303229b2c120e80f469353b2f5" has not been populated (PQ::PQError)`
Date: `2022-05-27T14:38:26Z`
Route: `/feed/subscriptions`
Version: `2022.05.24-c2d91c95 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
materialized view "subscriptions_b9fc8ea879dd53b8354c0de303229b2c120e80f469353b2f5" has not been populated (PQ::PQError)
  from lib/pg/src/pq/connection.cr:202:22 in 'handle_error'
  from lib/pg/src/pq/connection.cr:184:9 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'query_all:as'
  from /usr/share/crystal/src/reference.cr:28:3 in 'get_subscription_feed'
  from src/invidious/routes/feeds.cr:97:29 in 'subscriptions'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>
 Source code
 Documentation
Released under the AGPLv3 on GitHub.
 View JavaScript license information.
 View privacy policy.
 Donate
Current version: 2022.05.24-c2d91c95 @ master
**Screenshots**

![Screenshot_20220527-104107](https://user-images.githubusercontent.com/106392300/170722101-e475a1ca-4907-4b3a-b413-a77c0633d224.png)

**Additional context**

I have had this problem on windows and android, and on Microsoft edge, dickduckgo browser and brave browser. Based on my research, the problem appears to maybe be caused by the deletion of a "NO" from the code of the webpage. This probably being done by my neighbor who has been hacking me because he's a cyberterrorist. Please try to fix the issue, and find all the information you can on him. I know who he is, and I am an IT student, and I will help in any way I can. The police say they need a report on him thay does not come from me to do anything.

**Comment by unixfox** [comment] 2022-05-27 19:06
Duplicate of https://github.com/iv-org/invidious/issues/3123

**Closed by unixfox** 2022-05-27 19:06 UTC
Labels: bug
