### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Minty4614** [iv-org/invidious#2590] opened 2021-11-12 13:21 UTC
Title: `Could not check out a connection in 5.0 seconds (DB::PoolTimeout)`
Date: `2021-11-12T13:21:02Z`
Route: `/watch?v=y1xZ_kAhjMc`
Version: `2021.11.08-21879da8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Could not check out a connection in 5.0 seconds (DB::PoolTimeout)
  from /usr/share/crystal/src/int.cr:540:9 in 'checkout'
  from src/invidious/yt_backend/connection_pool.cr:34:14 in '_post_json'
  from src/invidious/yt_backend/youtube_api.cr:317:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:970:10 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2021-11-12 13:24
Caused by #2577, which should be fixed now.  If you're using a public instance, expect it to get resolved in the coming hours as instances update!

**Closed by syeopite** 2021-11-12 13:24 UTC
Labels: bug
