### ISSUE TITLE
[Discussion] Huge bandwidth consumption

### ISSUE THREAD

**Issue by Jerroder** [iv-org/invidious#4328] opened 2023-12-09 23:11 UTC
**Describe the bug**

I am self-hosting Invidious at home, with a 1Gbps fiber and with OPNsense as a firewall/router. The screenshot below is a traffic report of 450Mbps coming to the WAN interface and then Invidious' IP (`2001:(...)9c`) answers back at 361Mbps. It already happened before when I only had IPv4. This happens every few seconds to every few minutes.
Now this isn't someone spamming or DDoSing because I use a reverse proxy, so that traffic would be forwarded to Nginx' IP, this is really directly to invidious, as if it made the request first and this is a response? However the responses are going to the SLAAC address (`::ff:fe::`) and not a privacy address so that's weird.
I looked up the IPs it's coming from and it seems to come from my ISP, and I've had this problem with 2 ISPs so I don't believe it's something on their end.

This is obviously extremely hard to troubleshoot, I'm just curious if anyone has noticed the same behavior?

**Steps to Reproduce**

I have no idea

**Logs**

**Screenshots**

![invidious](https://github.com/iv-org/invidious/assets/29119296/297ffdb5-2c50-4f2b-bc7f-c688532515da)

**Additional context**

Invidious is running on Debian 12, behind OPNsense 23.7.9.

**Comment by unixfox** [comment] 2023-12-18 22:13
How many subscriptions do you have? Is this a single user instance? Do you have pubsub enabled?

**Comment by rderensy** [comment] 2023-12-18 22:18
I got 53 subscriptions and I'm the only user. Pubsub is disabled.

**Comment by unixfox** [comment] 2023-12-18 22:24
Sounds like invidious just refreshing the channels every 30 minutes. You can change the frequency if you prefer to consume less traffic: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L324C2-L324C2

Your issue looks a lot like this one: https://github.com/iv-org/invidious/issues/3234

Make sure that you have `decrypt_polling: false`, otherwise you will run into https://github.com/iv-org/invidious/issues/3234#issuecomment-1207185944

**Comment by rderensy** [comment] 2023-12-19 13:53
> Sounds like invidious just refreshing the channels every 30 minutes. You can change the frequency if you prefer to consume less traffic: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L324C2-L324C2

But is it supposed to consume so much bandwidth? 400Mbps over 15sec is 750MB, is it reloading all the thumbnails of all the channels?

> Your issue looks a lot like this one: https://github.com/iv-org/invidious/issues/3234

Ah, it didn't show up when I searched, didn't think about searching for "traffic", sorry!

> Also make sure that you have decrypt_polling: false, otherwise you will run into https://github.com/iv-org/invidious/issues/3234#issuecomment-1207185944

Not sure I understand this, is the decryption function's settings that big?

**Comment by absidue** [comment] 2023-12-20 06:33
@rderensy No it's not loading thumbnails. Disable the full refresh option if you have it enabled, as that makes Invidious fetch all pages of videos for each channel you are subscribed to. YouTube paginates at 30 items and each response will be 200kb+ of JSON, if it's not compressed, because sending small responses is something YouTube doesn't know how to do. So it adds up quite quickly.

**Comment by rderensy** [comment] 2023-12-20 11:22
`full_refresh` is already false for me

**Comment by unixfox** [comment] 2023-12-21 07:20
Do you take into account my last comment? Did it help?

**Comment by rderensy** [comment] 2023-12-21 17:47
I see the traffic peaks every few minutes, not every 30 minutes so I don't think it's subscriptions refreshing.

> Also make sure that you have decrypt_polling: false, otherwise you will run into https://github.com/iv-org/invidious/issues/3234#issuecomment-1207185944

That would prevent me from seeing music videos right? What would it change for the bandwidth?

**Comment by absidue** [comment] 2023-12-21 19:03
@rderensy Pretty sure it doesn't work anymore anyway, so you might as well just disable it.

**Comment by unixfox** [comment] 2024-11-01 21:06
Closing as a lot as changed since then, decrypt_polling is gone. Please comment here if you can still reproduce the issue.

**Closed by unixfox** 2024-11-01 21:06 UTC
Labels: discussion
