### ISSUE TITLE
[Bug] Missing hash key: "adaptiveFormats" (KeyError)

### ISSUE THREAD

**Issue by rammjet** [iv-org/invidious#4885] opened 2024-08-28 18:47 UTC
Only seems to happen on live streams that have been online for months.  Other videos are good.  This has been happening for the past several days.  Other instances work fine.

`Title: `Missing hash key: "adaptiveFormats" (KeyError)`
Date: `2024-08-28T18:41:03Z`
Route: `/watch?v=mhJRzQsLZGg`
Version: `2024.08.26-4782a67 @ (HEAD detached at v2.20240825.2)`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "adaptiveFormats" (KeyError)
  from /usr/share/crystal/src/hash.cr:1151:9 in '??'
  from /usr/share/crystal/src/json/any.cr:261:3 in 'adaptive_fmts'
  from src/invidious/routes/watch.cr:123:5 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:141:11 in 'run'
  from ???
```
</p>
</details>`

**Comment by evilantishad0w** [comment] 2024-08-29 20:44
#4734 - don't know if this is new behavior though, bug report says it applies to all videos, not specific streams.

**Comment by evilantishad0w** [comment] 2024-08-29 22:10
There's a fix for the issue at the bottom of that bug report.  I haven't tried it because it isn't simple to implement and I suspect everything will break if it's pushed to mainline and I'd have to rebuild the instance.  So I will wait too.

**Comment by rammjet** [comment] 2024-08-29 22:52
The fix in the bug report works!

Make a backup of your existing docker-compose.yml
Run a docker command and obtain two credentials
Update the docker-compose.yml to change "latest" to "master" and add credentials and a section to docker-compose.yml
Run

**Comment by unixfox** [comment] 2024-08-29 23:44
Duplicate of https://github.com/iv-org/invidious/issues/4734

**Closed by unixfox** 2024-08-29 23:44 UTC
Labels: bug
