### ISSUE TITLE
[Feature request] Share config/parameters between different instances

### ISSUE THREAD

**Issue by filt3rek** [iv-org/invidious#2706] opened 2021-12-08 13:56 UTC
Hej !

One again, many thanks for your work.
I use Invidious with a little script that takes me into the "best" (the first one) instance according to this sort : `https://api.invidious.io/instances.json?sort_by=health,users`
But that means that I change instances sometimes.
My question is : Could it be somehow done (maybe through cookies or something like that), that it keeps the parameters/config set please ? For example, I want the quality always be "medium" (not 720hd), and it's reinitialized on every instances...

Thanks for reading,
Cheers

**Comment by unixfox** [comment] 2021-12-08 14:51
Duplicate of https://github.com/iv-org/invidious/issues/2515

**Closed by unixfox** 2021-12-08 14:51 UTC
Labels: feature-request

**Comment by MintMain21** [comment] 2023-04-05 20:24
@filt3rek 

https://github.com/MintMain21/Invidious-URL-Parameters-Userscript
