### ISSUE TITLE
[Bug] users table auto growing until disk is full

### ISSUE THREAD

**Issue by LennyPenny** [iv-org/invidious#2766] opened 2022-01-05 19:02 UTC
**Describe the bug**
My users table seems to be auto growing until the disk is full and the database crashes. I'm investigating to see which column/row is growing so much

```
root@9e7add804e1d:/#  psql invidious --user *** -f table_size.sql
    table_schema    |       table_name        | row_estimate |   total    |   index    |   toast    |   table
--------------------+-------------------------+--------------+------------+------------+------------+------------
 public             | users                   |            3 | 22 GB      | 32 kB      | 22 GB      | 152 kB
 public             | channel_videos          |        93863 | 26 MB      | 10 MB      | 8192 bytes | 16 MB
```

**Steps to Reproduce**

**Comment by unixfox** [comment] 2022-01-05 19:07
Duplicate of https://github.com/iv-org/invidious/issues/2042

**Comment by SamantazFox** [comment] 2022-01-09 21:10
Nope, it's a different problem. I'm re-opening to explain what's going on

Note, this is fixed in 790b7afccaeb880e8b77c1df6a4cc6654c222006

**Comment by SamantazFox** [comment] 2022-01-09 21:24
Ok, so to explain that: the function `fetch_channel` used to take the following parameters:
- channel ID (`String`) - mandatory
- database object (`DB`) - mandatory
- "Pull all videos" flag (`Bool`)  - optional
- language code (`String`) - optional

During my DB code cleanup PR (#2685), I removed all extra `DB` objects from the different functions and instead used the already global variable `PG_DB`. But I forgot one function call, in the refresh channels job (the worst place).

Because of type infering (the compiler automatically determines the parameter and variables data types), the `fetch_channel` function had the following parameters:
- channel ID `String` - mandatory
- "Pull all videos" flag (either `DB` or `Bool`) - optional
- language code (`String`) - optional

And because the DB object passed in not `nil` (i.e, the DB is connected), that has the same effect as passing `true`, and it will reload all of the channel videos into the DB, effectively filling up the user's notifications.

**Comment by SamantazFox** [comment] 2022-01-09 22:37
poke @artemislena, @hys0star, @TechnicalSuwako, @FireMasterK, @RiversideRocks, @namazso, @ItsSt0ne and @11Tuvork28

**Comment by RiversideRocks** [comment] 2022-01-09 22:42
Agree 100%, it chews up a ton of space

**Comment by SamantazFox** [comment] 2022-01-09 22:56
> Agree 100%, it chews up a ton of space

This is fixed in the latest docker image / latest commit on master (from today)

**Comment by unixfox** [comment] 2022-01-10 14:34
@ItsSt0ne Could you please stop running a VACUUM FULL on your instance? This is blocking the postgresql requests made by invidious return this error: `PoolRetryAttemptsExceeded`

**Comment by martadinata666** [comment] 2022-01-12 05:39
uh, 250GB invidious DB usage here. do we need to manually clean up? or automated after application update?

**Comment by unixfox** [comment] 2022-01-12 09:21
> uh, 250GB invidious DB usage here. do we need to manually clean up? or automated clean up after application update?

execute this postgresql command: `VACUUM FULL;`

**Comment by unixfox** [comment] 2022-01-16 16:04
Reopening as it's still an issue for big instances.

**Comment by unixfox** [comment] 2022-01-16 18:06
Oops it's this one that should stay opened: https://github.com/iv-org/invidious/issues/2042

**Closed by unixfox** 2022-01-16 18:06 UTC
Labels: bug

**Comment by unixfox** [comment] 2022-01-18 09:30
@SamantazFox I think there is still a remaining issue because the users table is growing much master than before on my instance. Before the merge of the database improvment I had to VACUUM every week, now it's every 10 minutes.

**Comment by SamantazFox** [comment] 2022-01-25 14:59
@unixfox I'll try to go as fast as I can on the subject of a migration framework for the DB, so we can start pushing structures changes, to make it easier for the DB and the disk.
