### ISSUE TITLE
[Bug]+The+video+returned+by+YouTube+isn't+the+requested+one.+(Android+client)+(VideoNotAvailableException)

### ISSUE THREAD

**Issue by Sharanyane** [iv-org/invidious#4500] opened 2024-03-29 03:04 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by Sharanyane** [comment] 2024-03-29 03:05
![image](https://github.com/iv-org/invidious/assets/165348382/6d41bab0-4a07-4570-9328-76570e1087c5)

**Comment by megascrapper** [comment] 2024-03-29 04:46
Duplicate of #4498

**Closed** 2024-03-29 04:54 UTC
Labels: bug
