### ISSUE TITLE
[Feature request] Add an “Embed” option whenever there's an error

### ISSUE THREAD

**Issue by Jonas-Persson-temp** [iv-org/invidious#5098] opened 2024-12-03 12:45 UTC
When I see this error:
![image](https://github.com/user-attachments/assets/c97d9c7d-8e41-42e1-a26e-a2fab2ce0370)

I want there to be an • **Embed** option (e.g. clicking on embed redirects you from __yewtu.be/watch?v=fo0bArBAZ__ to __youtube.com/embed/fo0bArBAZ__), I hate using the sluggish keyboard on my TV whenever it happens.
• **Go to YouTube** would play ads and the official website always takes a lot of time to load, especially on TV.

I don't know what language is being used or how to contribute to this project, but here are some snippets (may not work):
```crystal
def convert_to_embed_link(video_url : String) : String
	# Extract the video ID from the URL
	if video_url =~ %r{(?:https?://)?(?:www\.)?([^/]+)/(?:watch\?v=)([^&]+)}
		video_id = $2
		return "https://youtube.com/embed/#{video_id}"
	end
	return video_url # Return the original URL if it doesn't match
end
```
```crystal
embed_link = convert_to_embed_link(env.request.resource)
# Usage example
<p>#{translate(locale, "videoinfo_youTube_embed_link")}: <a href="#{embed_link}">#{embed_link}</a></p>
```

**Comment by unixfox** [comment] 2024-12-03 13:06
Duplicate of https://github.com/iv-org/invidious/pull/4985

**Closed by unixfox** 2024-12-03 13:06 UTC
Labels: feature-request
