### ISSUE TITLE
Import  data not work

### ISSUE THREAD

**Issue by bigkitttty** [iv-org/invidious#1351] opened 2020-08-24 21:23 UTC
it says  Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to admin@invidious.tube.  help

**Comment by TheFrenchGhosty** [comment] 2020-08-25 00:42
Duplicate of https://github.com/iv-org/invidious/issues/1338

**Closed by TheFrenchGhosty** 2020-08-25 00:42 UTC
