### ISSUE TITLE
[Bug] Can't see comments anywhere

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1972] opened 2021-04-02 21:45 UTC
**Describe the bug**
I tested many instances but none of them is able to show the comments. There's just an empty space at the place where they are supposed to be.

**Steps to Reproduce**

1. Go to a random video on any instance

**Additional context**

 - Browser (if applicable): firefox
 - OS (if applicable): debian

**Comment by syeopite** [comment] 2021-04-02 23:20
Duplicate of #1965

**Closed** 2021-04-02 23:56 UTC
Labels: bug
