### ISSUE TITLE
[Bug] Vertical black bars on Firefox

### ISSUE THREAD

**Issue by kurokawa90** [iv-org/invidious#2261] opened 2021-07-18 13:09 UTC
Hi-
1. There seems to be an issue on Firefox with vertical black bars on videos due to odd ratio (I guess?). This is true for all instances tried. However, it works perfectly on Brave the scaling is fine. Is it an issue of settings on Firefox?  
2. Is there a way to choose/customize the size of the player or it is now just one fixed size (could not find anything on wiki about the customization)?
Many thanks!

**Comment by syeopite** [comment] 2021-07-18 13:39
Duplicate of #1880. But your findings here are rather interesting though. Could you post them over at that thread? Thanks.

**Closed by syeopite** 2021-07-18 13:39 UTC
Labels: bug
