### ISSUE TITLE
[Bug] tried to import playlists from YouTube/Google takeout, each time resulted in an error

### ISSUE THREAD

**Issue by cre8tions-eth** [iv-org/invidious#4961] opened 2024-09-29 05:24 UTC
Title: `Index out of bounds (IndexError)`
Date: `2024-09-29T05:22:55Z`
Route: `/data_control?referer=%2Ffeed%2Fsubscriptions`
Version: `2024.08.26-4782a67 @ (HEAD detached at v2.20240825.2)`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from src/invidious/routes/preferences.cr:284:14 in 'update_data_control'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:141:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2024-09-30 20:54
Duplicate of https://github.com/iv-org/invidious/issues/4069

**Closed by unixfox** 2024-09-30 20:54 UTC
Labels: bug
