### ISSUE TITLE
[Bug] Age restricted videos cannot play.

### ISSUE THREAD

**Issue by DADESUPER** [iv-org/invidious#2275] opened 2021-07-25 11:31 UTC
**Describe the bug**
Age restricted videos cannot play. API error is returned.

**Steps to Reproduce**
1) Open any age restricted video
2) API error pops up. Video does not play

**Additional context**
Not just an invidious bug. all of the "youtube downloader" sytle websites and apps are unable to download age restricted videos. I think what's going on (based on an error returned while trying to test video downloads using jdownloader) is the api that is used to get the video will not give you the stream link unless you're logged into a youtube account if the video is age restricted, so any app that isn't connected to a youtube account will be unable to download or stream age restricted videos unless you provide an official youtube session cookie. Hopefully it can be fixed without needing to provide that.

**Comment by syeopite** [comment] 2021-07-25 11:47
Duplicate of #2189

**Closed by syeopite** 2021-07-25 11:47 UTC
Labels: bug
