### ISSUE TITLE
[Bug]  Missing JSON element "videoDetails" (BrokenTubeException)

### ISSUE THREAD

**Issue by 2011** [iv-org/invidious#3562] opened 2023-01-15 10:05 UTC
**Describe the bug**

Received message "It looks like you found a bug in Invidious!"

**Steps to Reproduce**
1. Entered this URL: https://invidious.snopyta.org/watch?v=6Dm-jLBgbzE
2. See error

**Logs**
```
Title: `Missing JSON element "videoDetails" (BrokenTubeException)`
Date: `2023-01-15T09:47:48Z`
Route: `/watch?v=6Dm-jLBgbzE`
Version: `2022.11.22-5160d8ba @ master`

<details>
<summary>Backtrace</summary>
<p>
   
Missing JSON element "videoDetails" (BrokenTubeException)
  from /usr/share/crystal/src/array.cr:108:31 in 'parse_video_info'
  from src/invidious/videos/parser.cr:90:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:366:10 in 'fetch_video'
  from src/invidious/videos.cr:354:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???

</p>
</details>
```

**Comment by unixfox** [comment] 2023-01-15 10:42
Duplicate of https://github.com/iv-org/invidious/issues/3402

**Closed by unixfox** 2023-01-15 10:42 UTC
Labels: bug
