### ISSUE TITLE
[Bug] Missing hash key: "navigationEndpoint" (KeyError)

### ISSUE THREAD

**Issue by Szkodnix** [iv-org/invidious#3510] opened 2022-12-20 21:33 UTC
**Describe the bug**
When I try to search "ghostbuster electro swing" I get this error

**Steps to Reproduce**

**Logs**
Title: `Missing hash key: "navigationEndpoint" (KeyError)`
Date: `2022-12-20T21:31:03Z`
Route: `/search?q=ghostbuster+electro+swing`
Version: `2022.11.22-5160d8ba @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "navigationEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1077:11 in '[]'
  from /usr/share/crystal/src/json/any.cr:103:7 in '[]'
  from /usr/share/crystal/src/json/any.cr:139:5 in 'dig'
  from src/invidious/yt_backend/extractors.cr:688:12 in 'get_browse_id'
  from src/invidious/yt_backend/extractors.cr:265:41 in 'parse'
  from src/invidious/yt_backend/extractors.cr:252:16 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'regular'
  from src/invidious/search/query.cr:116:30 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/routing.cr:162:20 in '->'
  from lib/kemal/src/kemal/route.cr:12:26 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:162:16 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:515:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from /usr/share/crystal/src/fiber.cr:98:34 in '->'
  from ???
```
</p>
</details>

**Additional context**

**Comment by unixfox** [comment] 2022-12-21 06:01
Duplicate of https://github.com/iv-org/invidious/issues/2530

**Closed** 2022-12-21 06:01 UTC
Labels: bug
