### ISSUE TITLE
[Bug] Missing hash key: "browseEndpoint" (KeyError)

### ISSUE THREAD

**Issue by gokugodki** [iv-org/invidious#3388] opened 2022-11-11 19:09 UTC
hi it me again sam now iteroni  give me this Title: `Missing hash key: "browseEndpoint" (KeyError)`
Date: `2022-11-11T18:31:59Z`
Route: `/watch?v=Kh0BeeFMj34`
Version: `2022.11.02-09942de @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "browseEndpoint" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '[]'
  from /usr/share/crystal/src/json/any.cr:144:5 in 'parse_related_video'
  from src/invidious/videos.cr:1011:9 in 'parse_video_info'
  from src/invidious/videos.cr:926:12 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:1129:10 in 'fetch_video'
  from src/invidious/videos.cr:1109:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-11-16 08:06
Duplicate of https://github.com/iv-org/invidious/issues/3349

**Closed by unixfox** 2022-11-16 08:06 UTC
Labels: bug
