### ISSUE TITLE
[Bug] Arithmetic overflow (OverflowError)

### ISSUE THREAD

**Issue by pythonian23** [iv-org/invidious#3532] opened 2023-01-03 05:06 UTC
**Describe the bug**

**Steps to Reproduce**
1. Search "8.5 bit"

**Logs**

**Screenshots**

**Additional context**

Title: `Arithmetic overflow (OverflowError)`
Date: `2023-01-03T05:05:43Z`
Route: `/search?q=8.5+bit`
Version: `2023.01.01-8e50f2d1 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Arithmetic overflow (OverflowError)
  from src/invidious/yt_backend/extractors.cr:173:63 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:106:36 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2023-01-03 21:45
Duplicate of #3451

**Closed** 2023-01-03 21:45 UTC
Labels: bug, duplicate
