### ISSUE TITLE
Bug Found: Unexpected char '<' at 1:1

### ISSUE THREAD

**Issue by DreamsInCS** [iv-org/invidious#1777] opened 2021-02-14 18:29 UTC
Hi, all! Thanks again for blessing us with something as incredible as Invidious!
I came across this bug page while attempting to view someone's profile page.
If it helps any, I was on the invidious.zapashcanon.fr instance.
The error log is below.  I hope it helps. Cheers!

Title: `Unexpected char '<' at 1:1 (JSON::ParseException)`
Date: `2021-02-14T18:22:50Z`
Route: `/channel/UCXrCM2xBMRDUINv6S3wgr_w`
Version: `2021.01.12-cc3f019 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1715:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-02-14 18:31
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-02-14 18:31 UTC
Labels: duplicate
