### ISSUE TITLE
Some videos only work with dash and will never load from googlevideo.com

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#1345] opened 2020-08-20 21:37 UTC
This issue is made to regroup other issues where this problem was reported.

You are encouraged to comment with more examples.

https://github.com/iv-org/invidious/issues/1134

https://github.com/iv-org/invidious/issues/1131

**Comment by DontUseGithub** [comment] 2021-03-13 15:20
youtube-dl works with these URLS on the SAME IP
also the rest of the page works

so i conclude there is some bug in the fetcher for music videos (maybe look at the youtube-dl fetcher?)

**Comment by DontUseGithub** [comment] 2021-03-13 15:46
also i did some stupid scripting to find out which parameters youtube-dl and invidious keep the same on blocked videos and what differs.
Following parameters differ on a blocked video:

- aitags
- clen
- dur
- itag
- lmt
- lsig
- mime
- sig
- sparams
- txp

the lsig parameter overlaps on non blocked videos

while i tried this with only 1 blocked video and with only one working, it seems to be an indicator that youtube-dl is doing something slightly different on video url extraction

**Comment by DontUseGithub** [comment] 2021-03-13 19:06
i found an interesting article on that matter:
[reverse engineering youtube](https://tyrrrz.me/blog/reverse-engineering-youtube)

> You may notice that some videos, mostly the ones uploaded by verified channels, are protected. This means that their media streams and DASH manifests cannot be directly accessed by URL — a 403 error code is returned instead. To be able to access them, you need to decipher their signatures and then modify the URL appropriately.
> 
> For muxed and adaptive streams, the signatures are part of the extracted metadata. DASH streams themselves are never protected, but the actual manifest may be — the signature is stored as part of the URL.
> 
> A signature is a string made out of two sequences of uppercase letters and numbers, separated by period. Here’s an example: 537513BBC517D8643EBF25887256DAACD7521090.AE6A48F177E7B0E8CD85D077E5170BFD83BEDE6BE6C6C.
> 
> When your browser opens a YouTube video, it transforms these signatures using a set of operations defined in the player source code, putting the result as an additional parameter inside URLs. To repeat the same process from code, you need to locate the JavaScript source of the player used by the video and parse it.
> 
so it seems videos are "protected" by a signature

**Comment by unixfox** [comment] 2022-02-07 22:21
Can't reproduce the issue if proxy is enabled, all the video listed here load fine.
Closing in favor of https://github.com/iv-org/invidious/issues/2850 for forcing proxying.

**Closed by unixfox** 2022-02-07 22:21 UTC
Labels: bug, type:server-side
