### ISSUE TITLE
JSON Parse Exception: Unterminated String

### ISSUE THREAD

**Issue by CSDUMMI** [iv-org/invidious#1555] opened 2020-12-08 16:49 UTC
I have recently got the following error from this Invidious instance: [vid.mint.lgbt](https://vid.mint.lgbt/watch?v=GzWffFXpI1w)

I am asked to present to you, the following text as an explaination:
```
Title: `Unterminated string at 1:150670 (JSON::ParseException)`
Date: `2020-12-08T16:46:05Z`
Route: `/watch?v=GzWffFXpI1w`
Version: `2020.12.07-68552b6 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unterminated string at 1:150670 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer/string_based.cr:63:8 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:49:11 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:49:11 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:107:11 in 'extract_polymer_config'
  from src/invidious/videos.cr:964:10 in 'get_video:region'
  from src/invidious/routes/watch.cr:53:15 in 'handle'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from src/invidious/helpers/logger.cr:17:33 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>
```

**Comment by TheFrenchGhosty** [comment] 2020-12-08 16:58
Duplicate of #1535

**Closed by TheFrenchGhosty** 2020-12-08 16:58 UTC

**Comment by FireMasterK** [comment] 2020-12-09 08:15
I don't see how this is a duplicate? The exceptions and routes are different.

Title: `Unterminated string at 1:83796 (JSON::ParseException)`
Date: `2020-12-09T08:12:12Z`
Route: `/latest_version?id=bfawUJ7K2J8&itag=22`
Version: `2020.12.08-eea6f5c @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unterminated string at 1:83796 (JSON::ParseException)
  from ../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../usr/share/crystal/src/json/lexer/string_based.cr:21:12 in 'consume_string'
  from ../usr/share/crystal/src/json/lexer.cr:61:37 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:108:11 in 'next_token'
  from ../usr/share/crystal/src/json/parser.cr:83:11 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:49:18 in 'parse_array'
  from ../usr/share/crystal/src/json/parser.cr:33:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:49:18 in 'parse_array'
  from ../usr/share/crystal/src/json/parser.cr:33:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:85:19 in 'parse_object'
  from ../usr/share/crystal/src/json/parser.cr:35:7 in 'parse_value'
  from ../usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from ../usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/videos.cr:820:16 in 'extract_polymer_config'
  from src/invidious/videos.cr:964:3 in 'fetch_video'
  from src/invidious/videos.cr:948:13 in 'get_video'
  from src/invidious/videos.cr:931:1 in 'get_video:region'
  from src/invidious.cr:4113:11 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by TheFrenchGhosty** [comment] 2020-12-09 15:20
@FireMasterK Same error = same issue
