### ISSUE TITLE
[Bug] Visit any channel page: Unexpected token '' at line 1, column 1, all instances

### ISSUE THREAD

**Issue by sozofu** [iv-org/invidious#1840] opened 2021-03-03 06:13 UTC
Describe the bug
Unexpected token, upon visiting any channel page. Tried with multiple channels and on multiple instances.

Steps to Reproduce

    Click any channel, any instance link, i.e. (https://tube.connect.cafe/channel/UCgRr2pZaGeaZVN6LfbvQk9w)
    Error page appears

Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-03T05:56:02Z`
Route: `channel/UCgRr2pZaGeaZVN6LfbvQk9w`
Version: `2021.03.02-3af4207 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1709:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???

**Comment by hackerncoder** [comment] 2021-03-03 10:12
This appears to be a duplicate of #1838. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed** 2021-03-03 10:13 UTC
Labels: duplicate
