### ISSUE TITLE
[Bug] This content isn't available.

### ISSUE THREAD

**Issue by Abyssgrowth** [iv-org/invidious#4023] opened 2023-07-30 02:28 UTC
**Describe the bug**

Since recently, when i try to watch videos on yewtube the whole video is a black screen with a white text visible saying "this content isn't available." It happens on ALOT of videos sadly, but not all. What is this all about?
Have only tested this on yewtu.be

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by syeopite** [comment] 2023-07-30 03:38
Duplicate of https://github.com/iv-org/invidious/issues/3822

***

Unfortunately, YouTube has recently started trying to block Invidious. This is one outcome of that.

**Closed by syeopite** 2023-07-30 03:38 UTC
Labels: bug

**Comment by unixfox** [comment] 2023-07-30 06:49
Please post the video IDs
