### ISSUE TITLE
video won't play

### ISSUE THREAD

**Issue by FreeBornAngel** [iv-org/invidious#1982] opened 2021-04-05 19:45 UTC
Forgive my computer illiteracy, but here is a bug report.

Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2021-04-05T19:43:19Z`
Route: `/watch?v=v0Bu3M4r4K4&local=true&dark_mode=true&autoplay=0`
Version: `2021.04.03-ab0a131 @ disablequic`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/pool.cr:177:11 in 'query:args'
  from lib/db/src/db/query_methods.cr:46:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:7 in 'query_one?:as'
  from src/invidious/videos.cr:934:15 in 'get_video'
  from src/invidious/videos.cr:933:1 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from src/invidious.cr:311:1 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2021-04-05 20:33
Duplicate of #1582

**Closed** 2021-04-05 20:47 UTC
Labels: duplicate
