### ISSUE TITLE
[Feature request] Support plyr player

### ISSUE THREAD

**Issue by MaximilianGT500** [iv-org/invidious#2755] opened 2022-01-02 16:35 UTC
Support the plyr player: https://github.com/sampotts/plyr

--------

Original comment:

Hello, i would like to use another player or the normal player because I just don´t like Player.JS

**Comment by unixfox** [comment] 2022-01-02 16:45
Please specify which player you want instead of video.js (the default invidious player library).

Every player need to be thoroughly integrated with invidious.

**Comment by MaximilianGT500** [comment] 2022-01-02 16:46
I like to use: https://github.com/sampotts/plyr

**Comment by unixfox** [comment] 2022-01-02 17:10
Thank you for sharing that player, I didn't know it existed.

And for using the default player you can disable javascript and you will get the default player of the browser.

**Comment by MaximilianGT500** [comment] 2022-01-02 17:13
Ah, thank you. I really like the player and would be happy if I can use it someday, can you tell me where the path of the files is to edit the HTML in the Docker installation?

**Comment by unixfox** [comment] 2022-01-02 17:40
> Ah, thank you. I really like the player and would be happy if I can use it someday, can you tell me where the path of the files is to edit the HTML in the Docker installation?

You can't do that, I already said:

> Every player need to be thoroughly integrated with invidious.

**Comment by MaximilianGT500** [comment] 2022-01-02 17:43
No i mean i want to edit the HTML Style like: https://youtube.076.ne.jp/feed/popular

**Comment by unixfox** [comment] 2022-02-01 07:30
Duplicate of https://github.com/iv-org/invidious/issues/544

**Closed by unixfox** 2022-02-01 07:30 UTC
Labels: blocked, feature-request
