### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by s191ed** [iv-org/invidious#2793] opened 2022-01-09 18:10 UTC
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2022-01-09T18:10:07Z`
Route: `/`
Version: `2022.01.08-67cb8b71 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_one?:as'
  from src/invidious.cr:250:10 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in '->'
  from lib/kemal/src/kemal/filter_handler.cr:58:23 in 'call_block_for_path_type'
  from lib/kemal/src/kemal/filter_handler.cr:16:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-01-09 19:12
Which instance did you use?

**Comment by unixfox** [comment] 2022-01-09 19:14
Closing as duplicate of https://github.com/iv-org/invidious/issues/1582

**Closed by unixfox** 2022-01-09 19:14 UTC
Labels: bug
