### ISSUE TITLE
Search in Hebrew has broken

### ISSUE THREAD

**Issue by kobo98** [iv-org/invidious#2176] opened 2021-06-18 21:09 UTC
When I search the web for hebrew terms it refers to the ASCII representation of the word,

For example when I search "שלום", which is hello in hebrew, it shows titles which has the ASCII code of שלום in the title,

Instead of showing results for the actual word, for example:

![image](https://user-images.githubusercontent.com/6390539/122616161-8891ef00-d092-11eb-8bac-c791392ee298.png)

Search url:  https://yewtu.be/search?q=%D7%A9%D7%9C%D7%95%D7%9D

This is true to every instance of Invidious and I started to experience it from the beginning of the month,

Thank you.

**Comment by syeopite** [comment] 2021-06-18 21:10
Duplicate of #2140

**Closed by syeopite** 2021-06-18 21:10 UTC
Labels: bug

**Comment by SamantazFox** [comment] 2021-06-19 16:57
> Duplicate of #2140

More importantly: fixed in #2155!

@kobo98 please be patient, the bug will disappear as instance maintainers upgrade to latest version :)
