### ISSUE TITLE
[Bug] Random translations

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2860] opened 2022-02-03 21:45 UTC
**Describe the bug**
I'm currently on a french youtuber page, and some of the titles and text are translated in english for no reason. And if i click on a video with english title, the title is on french on the video page.

**Logs**

**Screenshots**
First image: the title and the youtubers name is on english
Second image: what i see after clicking on the video on the first image:title and youtuber's name is on french.
Third image: you can see not all titles are translated.
________________________________________________________________________________________________________
![Screenshot_20220203_224021](https://user-images.githubusercontent.com/22192600/152434075-c3984ade-35c9-4587-8269-c64fa3a471b2.png)
________________________________________________________________________________________________________
![Screenshot_20220203_224103](https://user-images.githubusercontent.com/22192600/152434115-49ca4c9b-3ecf-4c75-9e3d-46263148d3a0.png)
________________________________________________________________________________________________________
![Screenshot_20220203_224346](https://user-images.githubusercontent.com/22192600/152434175-53ccec58-cf09-462c-8de1-b78de84ad776.png)
________________________________________________________________________________________________________
**Additional context**

**Comment by unixfox** [comment] 2022-02-03 21:57
Not sure if it's a bug, it's just YouTube that recently started to translate every single videos.

As we are providing by default to YouTube that the language is only English then YouTube sends to us directly the translated title because it thinks we don't speak French: https://github.com/iv-org/invidious/blob/master/src/invidious/yt_backend/youtube_api.cr#L155

I don't think it's possible to retrieve the original title.

**Comment by SamantazFox** [comment] 2022-02-06 17:47
Sadly, it's not a bug, but a youtube "feature".
If you can, ask the creator(s) to disable auto-translation of their video titles.

See issue #1356 for more details.

**Comment by unixfox** [comment] 2022-02-06 17:50
Duplicate of https://github.com/iv-org/invidious/issues/1356 then

**Closed by unixfox** 2022-02-06 17:50 UTC
Labels: bug, can't fix
