### ISSUE TITLE
[Bug] Visit any channel page: Unexpected token '' at line 1, column 1

### ISSUE THREAD

**Issue by jdtech3** [iv-org/invidious#1838] opened 2021-03-03 02:04 UTC
**Describe the bug**
Unexpected token (seems to be nonexistent JSON when it's expecting JSON data?) upon visiting any channel page. Tried with multiple channels and on multiple instances.

**Steps to Reproduce**
1. Click any channel link, i.e. (https://yewtu.be/channel/UC-SV8-bUJfXjrRMnp7F8Wzw)
2. Error page appears

**Logs (from yewtu.be instance)**

Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-03T02:01:38Z`
Route: `/channel/UC-SV8-bUJfXjrRMnp7F8Wzw`
Version: `2021.03.02-3af4207 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1709:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by jdtech3** [comment] 2021-03-03 02:18
Seems to be related to a YouTube API change: [related YouTube-DL issue](https://github.com/ytdl-org/youtube-dl/issues/28289#issuecomment-789362801)

**Comment by user234683** [comment] 2021-03-03 04:43
It's a pretty simple change since it's just a JSON wrapper that passes the same continuation/ctoken. I implemented it in my Python project [here](https://github.com/user234683/youtube-local/blob/master/youtube/channel.py#L112)

**Comment by hackerncoder** [comment] 2021-03-03 10:12
Selecting this issue for this bug since it has the most activity and information about the bug and potential solution. All further bug reports of this bug should be commented here, and new issues reporting it should be closed as a duplicate of this.

To other contributors: please check if the labels are correct.

**Comment by yidakra** [comment] 2021-03-03 12:17
Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-03T12:14:28Z`
Route: `/channel/UCK-zlnUfoDHzUwXcbddtnkg`
Version: `2021.03.02-fc8c555 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1709:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by atropos112** [comment] 2021-03-03 14:20
I am getting (a lot of) messages of the following type

```
invidious_1  | 2021-03-03 14:13:55 UTC [error] RefreshChannelsJob: UC6nSFpj9HTCZ5t-N3Rm3-HA fiber : backing off for 1.00:00:00s
invidious_1  | 2021-03-03 14:13:55 UTC [error] RefreshChannelsJob: UCVls1GmFKf6WlTraIb_IaJg : unexpected token '<EOF>' at line 1, column 1
```

Is this the same issue ? (figured ill ask before making a bug report of my own)

**Comment by ddvarpdd** [comment] 2021-03-03 19:08
One of user-side workarounds for now is to access channel RSS feed by adding /feed/ before URL.
Example: https://invidious.snopyta.org/feed/channel/UCAL3JXZSzSm8AlZyD3nQdBA
Though it's usable only if using Firefox with [rsspreview](https://github.com/aureliendavid/rsspreview) addon, or its older version with native RSS feed previews.

**Comment by jtagcat** [comment] 2021-03-03 23:21
@hackerncoder: Please pin this to lessen duplicates.

**Comment by noarchwastaken** [comment] 2021-03-04 06:29
Aside from not being able to visit channel pages, I also can't subscribe to channels:

```
2021-03-04 06:25:14 UTC [info] 500 POST /subscription_ajax?action_create_subscription_to_channel=1&r
edirect=false&c=UC9PO3VWOcE2DiSHUHLZs18w 98.43ms
Exception: unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'fetch_channel'
  from src/invidious/channels.cr:205:1 in 'get_channel'
  from src/invidious.cr:533:7 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```

Importing subscriptions doesn't work either, invidious will just return to subscription manager with 0 subscriptions after hitting "Import".

**Comment by Quix0r** [comment] 2021-03-04 10:27
Another example, it worked some days ago:
````
Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-04T10:26:52Z`
Route: `/channel/UCVtVOddS0ms54kntAYXIVGg`
Version: `2021.02.11-28302c8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
  from src/invidious.cr:1716:20 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>
````
Commit id 9687d432fd28f8f5d47ca7da4c8c67fc2f5763de

**Comment by drozdikd** [comment] 2021-03-04 13:41
> Another example, it worked some days ago:
> 
> ```
> Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
> Date: `2021-03-04T11:17:10Z`
> Route: `/channel/UCVtVOddS0ms54kntAYXIVGg`
> Version: `2021.03.03-9687d43 @ master`
> <details>
> <summary>Backtrace</summary>
> <p>
> unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
>   from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
>   from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
>   from /usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
>   from /usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
>   from src/invidious.cr:1709:20 in '->'
>   from lib/kemal/src/kemal/route.cr:13:9 in '->'
>   from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
>   from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
>   from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
>   from /usr/share/crystal/src/http/server.cr:498:5 in '->'
>   from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
>   from ???
> </p>
> </details>
> ```
> 
> Commit id [9687d43](https://github.com/iv-org/invidious/commit/9687d432fd28f8f5d47ca7da4c8c67fc2f5763de)

Nearly same line of text (header is same exc time) I get too at yewtu.be. At invidious.tube, there is different version _[Version: `2021.03.03-9687d43 @ master`]_ and I have everywhere ??? after 'from' below unexpected token, at invidious.site, it simply says "This channel does not exist."

**Comment by obscurerev** [comment] 2021-03-04 16:26
This happens on every invidious instance I go on.

**Comment by gabor-ig** [comment] 2021-03-05 05:48
Same issue on my private instance... when trying to view any youtube channel.

Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-05T05:47:28Z`
Route: `/channel/UC3XTzVzaHQEd30rQbuvCtTQ`
Version: `2021.03.03-9687d43 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1709:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by MPeti1** [comment] 2021-03-05 10:15
A new bug report. Do new ones provide any more useful information?

Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-05T10:11:20Z`
Route: `/channel/UCR_SK7ir_2c5V493u13qIGQ`
Version: `2021.03.01-44f30c0 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1718:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by schleussinger** [comment] 2021-03-05 10:39
pull request 1849 has a workaround. 

Assuming you are building from master, heres what i did, it fixed the problem for my instance:

```
sudo -i -u invidious
cd invidious
git fetch origin pull/1849/head:channelfix
git checkout channelfix
shards update && shards install
crystal build src/invidious.cr --release
exit
sudo systemctl restart invidious.service

```

**Comment by sereinity** [comment] 2021-03-05 10:41
Yewtu.be seems to have been fixed

**Comment by unixfox** [comment] 2021-03-05 11:52
> Yewtu.be seems to have been fixed

Indeed, I've deployed the code from the pull request #1849.

**Comment by gabor-ig** [comment] 2021-03-05 14:56
Is there a fix for a Docker-based setup?

Mar 5, 2021 11:39:35 schleussinger <notifications@github.com>:

**Comment by nathgit** [comment] 2021-03-05 15:25
I don't know when exactly it started, but I've been having the same problem for a few days now (on Chrome OS if that matters).. I use primarily the snopyta domain, so I didn't know if anybody was having the same issue or if it was just me, or maybe just a problem with that domain.

**Comment by LennyPenny** [comment] 2021-03-05 18:54
@gabor-ig made this pr (https://github.com/iv-org/invidious/pull/1868) to make PR testing easier for docker setup in the future:)

**Comment by gabor-ig** [comment] 2021-03-05 20:08
Hello, thanks a lot. Can you give me a pointer, how I can actually use 
this? I basically just cloned the repo and did docker-compose up -d :-D

On 2021-03-05 19:54, Lennart Bernhardt wrote:

> @gabor-ig [1] made this pr (#1868 [2]) to make PR testing easier for 
> docker setup in the future:)
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].


Links:
------
[1] https://github.com/gabor-ig
[2] https://github.com/iv-org/invidious/pull/1868
[3] 
https://github.com/iv-org/invidious/issues/1838#issuecomment-791614802
[4]

**Comment by xeronull** [comment] 2021-03-06 09:05
tle: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-06T09:03:36Z`
Route: `/channel/UCvIL0fhX8_NOvL3D0hUmiIw`
Version: `2021.03.02-fc8c555 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:37:7 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:13:12 in 'parse'
  from /usr/share/crystal/src/json.cr:131:5 in 'parse'
  from src/invidious/channels.cr:945:20 in 'get_60_videos'
  from src/invidious.cr:1709:20 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:17:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:468:13 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

**Comment by xeronull** [comment] 2021-03-06 09:15
> > Yewtu.be seems to have been fixed
> 
> Indeed, I've deployed the code from the pull request #1849.

can confirm, yewtu.be is still working on my end

**Comment by unixfox** [comment] 2021-03-06 09:35
@TheFrenchGhosty can be closed I guess now that https://github.com/iv-org/invidious/pull/1849 got merged.

**Closed** 2021-03-06 09:49 UTC
Labels: bug, priority:critical, type:youtube-change

**Comment by HumanG33k** [comment] 2021-04-22 15:51
Release it :D
