### ISSUE TITLE
[Bug] Index out of bounds (IndexError)

### ISSUE THREAD

**Issue by DOOMMARINE117** [iv-org/invidious#4201] opened 2023-10-25 03:47 UTC
Title: `Index out of bounds (IndexError)`
Date: `2023-10-25T03:46:03Z`
Route: `/data_control?referer=%2Ffeed%2Fpopular`
Version: `2023.10.21-2414e7d @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/json/any.cr:237:3 in 'update_data_control'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:30:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'handle_client'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

what does this mean?

**Comment by RadoslavL** [comment] 2023-10-25 05:37
This might be a duplicate of #4069.

What steps did you take before getting the error message?

**Comment by DOOMMARINE117** [comment] 2023-10-25 05:56
> This might be a duplicate of #4069.
> 
> What steps did you take before getting the error message?

yeah, its the same error. i mainly login, gone to preferences, then go to the bottom where it says iimport data.

i just realzed, this was on dev instance section. 

iv.ggtyler.dev was i suppsoed to login into that one?

**Closed** 2023-10-25 06:20 UTC
Labels: bug

**Comment by RadoslavL** [comment] 2023-10-25 06:22
>i just realzed, this was on dev instance section.
>
>iv.ggtyler.dev was i suppsoed to login into that one?

I don't think there are private public instances if that makes sense. If the instance is public, I assume it's meant to be used by people.

**Comment by DOOMMARINE117** [comment] 2023-10-25 08:06
> > i just realzed, this was on dev instance section.
> > iv.ggtyler.dev was i suppsoed to login into that one?
> 
> I don't think there are private public instances if that makes sense. If the instance is public, I assume it's meant to be used by people.

i see, so the instances can be used by anyone. when i try improting the csv files on that one. none of them went through.

**Comment by unixfox** [comment] 2023-10-25 08:07
> i just realzed, this was on dev instance section.

Don't use the test.invidious.io instance, it's **ONLY** for testing.

**Comment by DOOMMARINE117** [comment] 2023-10-25 08:08
> > i just realzed, this was on dev instance section.
> 
> Don't use the test.invidious.io instance, it's **ONLY** for testing.

gotcha, good to know. 

so that was my bad. 

i notice though on invidious.io.lol subscriptions one worked. but, any other file wouldnt go through.

**Comment by unixfox** [comment] 2023-10-25 08:12
It's literally WRITTEN on the homepage when you visit the website though... not sure how you did not understand that.

![image](https://github.com/iv-org/invidious/assets/4016501/d03ffb94-a041-47db-8a53-b886f5404cf7)

**Comment by RadoslavL** [comment] 2023-10-25 08:35
>Don't use the test.invidious.io instance, it's ONLY for testing.

They were using iv.ggtyler.dev, not test.invidious.io.
