### ISSUE TITLE
[Enhancement] Playbackspeeds higher than 2x

### ISSUE THREAD

**Issue by 14159265359** [iv-org/invidious#3284] opened 2022-08-28 11:04 UTC
I've been using Invidious instances since a few months and find it awesome software! However, sometimes I like to watch/listen to some videos at speeds higher than 2x. Right now I generally use the VideoSpeedController browser extension or console command
document.getElementsByTagName("video")[0].playbackRate = x (as described here https://www.quora.com/Is-there-a-way-of-watching-YouTube-videos-at-higher-than-2x-speed). However, on mobile devices I cannot conveniently use this and a toggle for higher speeds built into Invidious would be great. 

This could be implemented by adding a few buttons with speeds like 2.5x 3x 3.5x to trigger the document.getElementsByTagName("video")[0].playbackRate = x (as now is done with the other speeds). I hope you are willing to implement this and thanks in advance!

**Comment by unixfox** [comment] 2022-08-28 11:51
Duplicate of https://github.com/iv-org/invidious/issues/533

**Closed by unixfox** 2022-08-28 11:51 UTC
Labels: enhancement
