### ISSUE TITLE
No channels are loading[Bug] 

### ISSUE THREAD

**Issue by sh0e** [iv-org/invidious#1851] opened 2021-03-04 03:33 UTC
Title: `unexpected token '' at line 1, column 1 (JSON::ParseException)`
Date: `2021-03-04T03:33:16Z`
Route: `/channel/CHANNEL HERE`
Version: `2021.02.24-4c0aa04 @ serving9`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at line 1, column 1 (JSON::ParseException)
  from /usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from /usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from /usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from /usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
  from /home/azhao/invidious/src/invidious.cr:1723:20 in '->'
  from /home/azhao/invidious/lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /home/azhao/invidious/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /home/azhao/invidious/src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /home/azhao/invidious/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by llacb47** [comment] 2021-03-04 03:36
Search the open issues ..............

**Comment by llacb47** [comment] 2021-03-04 03:36
Duplicate of https://github.com/iv-org/invidious/issues/1838

**Closed** 2021-03-04 08:08 UTC
Labels: duplicate
