### ISSUE TITLE
[Bug] Some videos failed to play on non-DASH 720p

### ISSUE THREAD

**Issue by 138138138** [iv-org/invidious#3102] opened 2022-05-20 17:44 UTC
**Describe the bug**
Some videos are loading forever when playing with non-DASH 720p
Open F12 I can see a bunch of net::ERR_CONTENT_LENGTH_MISMATCH 206
example video:
https://vid.puffyan.us/watch?v=IrXLRxSsMbs
https://test.invidious.io/watch?v=IrXLRxSsMbs

**Steps to Reproduce**
1. Go to https://vid.puffyan.us/watch?v=IrXLRxSsMbs
2. Click play. Default quality is already non-DASH 720p
3. Videos keep loading
4. Open F12 there are net::ERR_CONTENT_LENGTH_MISMATCH 206
5. Switch to 360p will play successfully

**Logs**
watch:600          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
watch:1033          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
watch:1033          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
watch:1033          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
watch:1033          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
watch:1033          GET https://rr2---sn-i3b7knsd.googlevideo.com/videoplayback?expire=1653089651&ei=E9GHYrLEKoaM8wSQgLaICg&ip=51.81.85.74&id=o-AM7K8cnUiywbrLVzRCM8lS12rHLIF_Wp6Rm0iLnbohQ4&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=606.760&lmt=1653047054773055&fexp=24001373,24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHXZxwcTQdqPs1mpFBLs06btt6cpXK41rDn8bX1XnoEoCIQDAmGzErD3VYVKrs6amA47grt-GOdRnbfZTp8oE86_5jQ%3D%3D&host=rr4---sn-p5qlsn7d.googlevideo.com&redirect_counter=1&rm=sn-p5qees7z&req_id=d058a8255c3836e2&cms_redirect=yes&ipbypass=yes&mh=Gt&mip=37.120.151.123&mm=31&mn=sn-i3b7knsd&ms=au&mt=1653067750&mv=m&mvi=2&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pl&lsig=AG3C_xAwRQIgZptx3y8H8VREmU9yKT16ATLv7p-STrH0OzTx8SUPnSgCIQCWX70Pa9Y_XdutTmXOvE0m1MG9rUEVznimqEhdqS3kqw%3D%3D net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)

**Screenshots**

**Additional context**

**Comment by unixfox** [comment] 2022-05-20 18:16
Duplicate of https://github.com/iv-org/invidious/issues/3025

**Closed by unixfox** 2022-05-20 18:16 UTC
Labels: bug
