### ISSUE TITLE
[Bug] DB::PoolRetryAttemptsExceeded

### ISSUE THREAD

**Issue by NunoSempere** [iv-org/invidious#2743] opened 2021-12-25 19:05 UTC
**Describe the bug**
Video does not load.

**Steps to Reproduce**
1. Unclear; it appeared when going to https://invidious.snopyta.org/watch?v=DvoxzPbAXwI

**Logs**
```
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2021-12-25T18:59:04Z`
Route: `/watch?v=DvoxzPbAXwI`
Version: `2021.12.19-ddb06b0c @ master`
<details>
<summary>Backtrace</summary>
<p>
   
\`\`\`
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/pool.cr:190:7 in 'exec'
  from src/invidious/videos.cr:1005:9 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
\`\`\`
</p>
</details>
```
**Screenshots**
![Screenshot 2021-12-25 at 20-00-38 Error - Invidious](https://user-images.githubusercontent.com/16527456/147391818-5df4af46-aa87-4970-bc9b-a1639c7e96b8.png)

**Additional context**
 - Browser (if applicable): Firefox
 - OS (if applicable): Ubuntu
 - Instance: https://invidious.snopyta.org
- Perhaps a duplicate of: https://github.com/iv-org/invidious/issues/1582, but my stack trace seems different.
- Video loads again after a reload.

**Comment by unixfox** [comment] 2021-12-25 19:20
Duplicate of https://github.com/iv-org/invidious/issues/1582

**Closed by unixfox** 2021-12-25 19:20 UTC
Labels: bug
