### ISSUE TITLE
[idea/request] If it is possible to use invidious as a parental whitelist filter?

### ISSUE THREAD

**Issue by iso-i** [iv-org/invidious#2979] opened 2022-03-18 16:53 UTC
I'm trying to set up a server that could run locally as a YouTube proxy, to whitelist videos for school. I'm hoping that I will be able to import lists of whitelisted videos similar to how `uBlock Origin` lets users subscribe to other people's lists **and** have their own videos.

(That way the school could publish their own whiltelist and parents could just have their copy subscribe to that URL.)

I'm imagining that each home could have a SBC (like a raspberry pi) or an old laptop running linux, to act as a proxy, and then have the local DNS redirect YouTube.com and googlevideo.com to the local proxy. (Or have the school act as the proxy.)

Is this too far outside of the Invidious design goals? If not could that be documented and have a single shell script to download and install, for the less technically minded?

**Comment by unixfox** [comment] 2022-03-18 17:56
Duplicate of https://github.com/iv-org/invidious/issues/344

**Closed by unixfox** 2022-03-18 17:56 UTC
