### ISSUE TITLE
Missing hash key: "reason" (KeyError)

### ISSUE THREAD

**Issue by AndrewDaGuy** [iv-org/invidious#2095] opened 2021-05-19 04:47 UTC
Invidious wanted me to post this issue soooo:

Title: `Missing hash key: "reason" (KeyError)`
Date: `2021-05-19T04:44:56Z`
Route: `/watch?v=DQjyQDBaCw8`
Version: `2021.05.06-a51c5c3 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "reason" (KeyError)
  from /opt/crystal-0.36.1-1/share/crystal/src/hash.cr:1030:9 in '[]'
  from src/invidious/videos.cr:831:14 in 'extract_polymer_config'
  from src/invidious/videos.cr:966:10 in 'fetch_video'
  from src/invidious/videos.cr:942:17 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /opt/crystal-0.36.1-1/share/crystal/src/primitives.cr:255:3 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /opt/crystal-0.36.1-1/share/crystal/src/http/server.cr:498:5 in '->'
  from /opt/crystal-0.36.1-1/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by syeopite** [comment] 2021-05-20 16:12
Duplicate of #2086

**Closed by syeopite** 2021-05-20 16:12 UTC
