### ISSUE TITLE
[Bug] net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by Right-BuggerOff** [iv-org/invidious#4062] opened 2023-08-18 21:11 UTC
I've been trying to download a video with the Invidious app and I've been getting this response:

Web page not available
The web page at https://vid.puffyan.us/videoplayback?expire=1692414363&ei=O93fZLzoO4yB8gTBzL74DQ&ip=2001%3A19f0%3A5%3A4d2b%3A5400%3A4ff%3Afe78%3A2e45&id=o-AJMelXzvqceI9R6NG-5dA9BqpJTMvW1BpM6LNFxs28Pm&itag=599&source=youtube&requiressl=yes&mh=cc&mm=31%2C29&mn=sn-ab5sznzz%2Csn-ab5l6nr6&ms=au%2Crdu&mv=m&mvi=3&pl=38&initcwndbps=781250&spc=UWF9f6z1TxC097p-UdLAG6CEvuA1lqM&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=7666671&dur=1992.318&lmt=1691536845681083&mt=1692392477&fvip=5&keepalive=yes&fexp=24007246%2C24363392&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJo78UYigL_TO1rErrrL-NqaIy4JA0dvEt3J7-5HPeFkAiEAzxhwvVYwez-Jqt4szwS5i1CvtL_Ystn_rw_GZcONjUw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANDtRNnV1fP-dLtJgGPfcWvhd6kMqeaL9zMfU1um7Wc3AiA4xQ9BLysxJPN9RNEokN1_asNEc2XwfFaC0I5V6mgN5w%3D%3D&host=rr3---sn-ab5sznzz.googlevideo.com&title=Kraut%20-%20Using%20Liberal%20Political%20Theory%20Instead%20of%20History-FSN6dL5MUUM.mp4 could not be loaded because:

net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by absidue** [comment] 2023-08-18 22:05
duplicate of #4045

**Closed** 2023-08-18 22:07 UTC
Labels: bug
