### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JustaRandom** [iv-org/invidious#2712] opened 2021-12-10 16:37 UTC
Running Firefox 95 - Macos. Don't know if relevant.

Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-12-10T16:34:09Z`
Route: `/feed/trending`
Version: `2021.12.10-5e957c5 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/lib/crystal/core/int.cr:957:11 in 'to_i32'
  from /usr/lib/crystal/core/pointer.cr:130:6 in 'decode_length_seconds'
  from src/invidious/yt_backend/extractors.cr:75:26 in 'process'
  from src/invidious/yt_backend/extractors.cr:551:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:327:20 in 'parse'
  from src/invidious/yt_backend/extractors.cr:551:8 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:582:28 in 'extract_videos'
  from src/invidious/trending.cr:19:14 in 'trending'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by unixfox** [comment] 2021-12-10 16:54
Which instance are you using?

**Comment by unixfox** [comment] 2021-12-10 16:55
Duplicate of https://github.com/iv-org/invidious/issues/2708

**Closed by unixfox** 2021-12-10 16:55 UTC
