### ISSUE TITLE
[Bug] Document is empty (XML::Error) in channel community page

### ISSUE THREAD

**Issue by Ctrout3658** [iv-org/invidious#2556] opened 2021-11-02 18:29 UTC
Title: `Document is empty (XML::Error)`
Date: `2021-11-02T18:26:47Z`
Route: `/channel/UC3e8EMTOn4g6ZSKggHTnNng/community`
Version: `2021.10.26-6a15b0b @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Document is empty (XML::Error)
  from /usr/lib/crystal/core/json/parser.cr:117:5 in 'community'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:167:15 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>

**Comment by SamantazFox** [comment] 2021-11-03 00:17
Closing as it's a duplicate of #1725.

**Closed by SamantazFox** 2021-11-03 00:17 UTC
Labels: duplicate
