### ISSUE TITLE
Search Broken

### ISSUE THREAD

**Issue by FireMasterK** [iv-org/invidious#1488] opened 2020-11-25 06:16 UTC
![image](https://user-images.githubusercontent.com/20838718/100190182-b3a8cb80-2f13-11eb-8907-e5c096cbf92c.png)

https://invidious.kavin.rocks/search?q=bitcoin
https://invidious.snopyta.org/search?q=bitcoin

**Comment by carverh** [comment] 2020-11-25 08:41
Can confirm is broken on my instance as well.

**Comment by dentistformyeye** [comment] 2020-11-25 15:50
Is this due to a change in Youtube? Up to date instances worked just fine until late yesterday. Even an instance that's still on version 0.20.1-9995a8d shows a blank space, where there would be "nil assertion failed".
Video playback still works as usual.

**Comment by TheFrenchGhosty** [comment] 2020-11-25 17:02
@dentistformyeye 

>Is this due to a change in Youtube?

Yes, supposedly.

**Comment by FireMasterK** [comment] 2020-11-25 17:06
It's quite weird that these changes only broke Invidious, yt-dlc, and NewPipeExtractor work just fine.

**Comment by LostWanita21** [comment] 2020-11-25 18:26
Can confirm it affects both Yewtube and the Snopyta instances, I'm thinking it's something on Youtubes end since I'm getting similar search issues on Freetube.

**Comment by qorg11** [comment] 2020-11-25 23:54
Not working in my .onion (if that has something to do) instance

**Comment by andrigamerita** [comment] 2020-11-26 11:16
I can confirm the bug started occurring on my locally hosted instance (0.20.1-1973f93@master) as well, from about 45 hours ago. The strange thing I have experienced is the search was not entirely broken: it had like 10% chance of working and displaying results. As of now it seems to have stopped working completely.

**Comment by Coaggly** [comment] 2020-11-26 16:43
> I can confirm the bug started occurring on my locally hosted instance (0.20.1-1973f93@master) as well, from about 45 hours ago. The strange thing I have experienced is the search was not entirely broken: it had like 10% chance of working and displaying results. As of now it seems to have stopped working completely.

I'm also having a near identical experience.

**Comment by TheFrenchGhosty** [comment] 2020-11-26 17:10
Locking since it's becoming a "me too" issue. The fix ( #1491 ) will be merged soon

**Closed** 2020-11-26 17:28 UTC
Labels: bug, priority:critical, type:backend

**Comment by qorg11** [comment] 2020-11-26 20:58
I updated invidious but my search is still not working...
