### ISSUE TITLE
Page didn't load[Bug] 

### ISSUE THREAD

**Issue by Pyran1** [iv-org/invidious#2775] opened 2022-01-06 18:05 UTC
**Describe the bug**
Page didn't load :/

**Steps to Reproduce**
1. Go to https://yewtu.be

**Logs**
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2022-01-06T18:04:02Z`
Route: `/`
Version: `2022.01.05-7d8b3a8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/pool.cr:190:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:146:9 in 'query_one?:as'
  from src/invidious.cr:237:10 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'call_block_for_path_type'
  from lib/kemal/src/kemal/filter_handler.cr:16:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Comment by unixfox** [comment] 2022-01-06 18:09
Duplicate of https://github.com/iv-org/invidious/issues/1582

**Closed by unixfox** 2022-01-06 18:09 UTC
Labels: bug
