### ISSUE TITLE
[Bug] Bug/feature request - Hyphenated formats wrong redirect.

### ISSUE THREAD

**Issue by barkoder** [iv-org/invidious#5115] opened 2024-12-15 22:47 UTC
Both a bug report and a feature request. *(I don't know which label to file this under.)*

    $ yt-dlp -F m9Lz4v265tk | grep 'audio only'
    600-0        webm       audio only  [en] ultralow,   30k, webm_dash containervideo@   0k, opus @ 30k (48000Hz), 7.13MiB
    599-0        m4a        audio only  [en] ultralow,   30k, m4a_dash containervideo@   0k, mp4a.40.5@ 30k (22050Hz), 7.30MiB
    249-0        webm       audio only  [en] low,   45k, webm_dash containervideo@   0k, opus @ 45k (48000Hz), 10.73MiB
    139-0        m4a        audio only  [es-US] Spanish (United States), low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    139-1        m4a        audio only  [de-DE] German (Germany), low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    139-2        m4a        audio only  [fr-FR] French (France), low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    139-3        m4a        audio only  [it] Italian, low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    139-4        m4a        audio only  [pt-BR] Portuguese (Brazil), low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    139-5        m4a        audio only  [en] low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    249-1        webm       audio only  [fr-FR] French (France), low,   50k, webm_dash containervideo@   0k, opus @ 50k (48000Hz), 12.04MiB
    249-2        webm       audio only  [es-US] Spanish (United States), low,   51k, webm_dash containervideo@   0k, opus @ 51k (48000Hz), 12.12MiB
    249-3        webm       audio only  [it] Italian, low,   51k, webm_dash containervideo@   0k, opus @ 51k (48000Hz), 12.13MiB
    249-4        webm       audio only  [de-DE] German (Germany), low,   51k, webm_dash containervideo@   0k, opus @ 51k (48000Hz), 12.22MiB
    249-5        webm       audio only  [pt-BR] Portuguese (Brazil), low,   51k, webm_dash containervideo@   0k, opus @ 51k (48000Hz), 12.26MiB
    250-0        webm       audio only  [en] low,   59k, webm_dash containervideo@   0k, opus @ 59k (48000Hz), 14.08MiB
    250-1        webm       audio only  [fr-FR] French (France), low,   65k, webm_dash containervideo@   0k, opus @ 65k (48000Hz), 15.54MiB
    250-2        webm       audio only  [es-US] Spanish (United States), low,   66k, webm_dash containervideo@   0k, opus @ 66k (48000Hz), 15.65MiB
    250-3        webm       audio only  [it] Italian, low,   66k, webm_dash containervideo@   0k, opus @ 66k (48000Hz), 15.66MiB
    250-4        webm       audio only  [de-DE] German (Germany), low,   66k, webm_dash containervideo@   0k, opus @ 66k (48000Hz), 15.79MiB
    250-5        webm       audio only  [pt-BR] Portuguese (Brazil), low,   66k, webm_dash containervideo@   0k, opus @ 66k (48000Hz), 15.83MiB
    251-0        webm       audio only  [en] medium,  119k, webm_dash containervideo@   0k, opus @119k (48000Hz), 28.40MiB
    251-1        webm       audio only  [fr-FR] French (France), medium,  126k, webm_dash containervideo@   0k, opus @126k (48000Hz), 29.86MiB
    251-2        webm       audio only  [es-US] Spanish (United States), medium,  126k, webm_dash containervideo@   0k, opus @126k (48000Hz), 30.05MiB
    251-3        webm       audio only  [it] Italian, medium,  127k, webm_dash containervideo@   0k, opus @127k (48000Hz), 30.12MiB
    251-4        webm       audio only  [de-DE] German (Germany), medium,  127k, webm_dash containervideo@   0k, opus @127k (48000Hz), 30.30MiB
    251-5        webm       audio only  [pt-BR] Portuguese (Brazil), medium,  127k, webm_dash containervideo@   0k, opus @127k (48000Hz), 30.32MiB
    140-0        m4a        audio only  [de-DE] German (Germany), medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    140-1        m4a        audio only  [es-US] Spanish (United States), medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    140-2        m4a        audio only  [fr-FR] French (France), medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    140-3        m4a        audio only  [it] Italian, medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    140-4        m4a        audio only  [pt-BR] Portuguese (Brazil), medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    140-5        m4a        audio only  [en] medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB
    600-1        webm       audio only  [en-US] English (United States) original (default), ultralow,   30k, webm_dash containervideo@   0k, opus @ 30k (48000Hz), 7.13MiB
    599-1        m4a        audio only  [en-US] English (United States) original (default), ultralow,   30k, m4a_dash containervideo@   0k, mp4a.40.5@ 30k (22050Hz), 7.30MiB
    249-6        webm       audio only  [en-US] English (United States) original (default), low,   45k, webm_dash containervideo@   0k, opus @ 45k (48000Hz), 10.73MiB
    139-6        m4a        audio only  [en-US] English (United States) original (default), low,   48k, m4a_dash containervideo@   0k, mp4a.40.5@ 48k (22050Hz), 11.56MiB
    250-6        webm       audio only  [en-US] English (United States) original (default), low,   59k, webm_dash containervideo@   0k, opus @ 59k (48000Hz), 14.08MiB
    251-6        webm       audio only  [en-US] English (United States) original (default), medium,  119k, webm_dash containervideo@   0k, opus @119k (48000Hz), 28.40MiB
    140-6        m4a        audio only  [en-US] English (United States) original (default), medium,  129k, m4a_dash containervideo@   0k, mp4a.40.2@129k (44100Hz), 30.68MiB

Going to `https://<instance>/latest_version?id=m9Lz4v265tk&itag=140-0&local=true` audio redirects to `itag=18` video.
This is a bug and should not happen.

These new hyphenated formats are weird. The URLs for each of them don't resolve to their own separate hyphenated itags.
The final URL for the new formats all have the same itag.
Regardless of if you specify 140-1/2/3/4/5/6 the itag on the final googlevideo URL is always `itag=140` – just with a different `clen` , `dur` and related values for the various languages.

I don't know of any way to query language specific audio on invidious. Please consider supporting hyphenated formats.
Unless this option already exists – in which case, do let me know.

Thanks!

**Comment by absidue** [comment] 2024-12-15 23:11
This is not a bug report, the hyphenated values are a yt-dlp specific thing created by yt-dlp, they are not real itag values, so it is in no way surprising that they don't work on Invidious. Invidious searches for the itag and when it doesn't find it, because you passed it an invalid value, it redirects you to something that does actually exist so that you still get playback.

Also Invidious doesn't actually support multiple audio tracks yet, so this really is just a duplicate of the existing feature request. Additionally even when Invidious does support it, what you are doing still wouldn't work, as it would require Invidious to not only adopt support for invalid itag values but also to sort the audio streams in the exact same way as yt-dlp, so it seems extremely unlikely that you would be able to do what you are doing.

**Comment by unixfox** [comment] 2024-12-15 23:13
duplicate of https://github.com/iv-org/invidious/issues/2007

**Closed by unixfox** 2024-12-15 23:13 UTC
Labels: bug

**Comment by barkoder** [comment] 2024-12-16 14:26
@absidue I didn't know that. Thanks!

@unixfox sorry for the dupe.
