### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Timm-png** [iv-org/invidious#1856] opened 2021-03-04 13:46 UTC
Title: `unexpected token '' at 1:1 (JSON::ParseException)`
Date: `2021-03-04T13:45:27Z`
Route: `/channel/UCLizDDpxiFRoqTLlMyGX7lQ`
Version: `2020.12.09-2349a6a @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
unexpected token '<EOF>' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/parser.cr:125:5 in 'parse_exception'
  from ../../../usr/share/crystal/src/json/parser.cr:121:5 in 'unexpected_token'
  from ../../../usr/share/crystal/src/json/parser.cr:23:28 in 'parse_value'
  from ../../../usr/share/crystal/src/json/parser.cr:107:11 in 'get_60_videos'
  from src/invidious.cr:1938:20 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from src/invidious/helpers/logger.cr:17:33 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-03-04 14:25
This appears to be a duplicate of #1838. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-03-04 14:25 UTC
Labels: duplicate
