### ISSUE TITLE
[Bug] Database grows by 30 GB in minutes 

### ISSUE THREAD

**Issue by poltrian** [iv-org/invidious#2772] opened 2022-01-06 07:18 UTC
**Describe the bug**
I am the only user. When I create an account, import my subscriptions, it doesn't take long, and I have 35,000 unseen videos The Database grows by 30 GB. Why?

**Comment by unixfox** [comment] 2022-01-06 08:08
Duplicate of https://github.com/iv-org/invidious/issues/2766

**Closed by unixfox** 2022-01-06 08:08 UTC
Labels: bug
