### ISSUE TITLE
[Bug] DASH videos infinitely load

### ISSUE THREAD

**Issue by lyiriyah** [iv-org/invidious#2864] opened 2022-02-05 08:34 UTC
**Describe the bug**

Whenever I switch to DASH quality on my Invidious instance it just infinitely loads any video.

**Steps to Reproduce**
1. Navigate to https://inv.linv.duckdns.org
2. Set quality to DASH
3. Try to play any video

**Logs**
All variations on this:
```
2022-02-05 08:23:40 UTC [info] 206 GET /videoplayback?expire=1644070828&ei=TDP-YZG6A_eexN8PuOqp2AY&ip=[REDACTED]&id=o-AAl0uwzfcG5NwIPslEt9HDtEQymza6PnmE-YNLMpxcbC&itag=298&source=youtube&requiressl=yes&mh=Le&mm=31%2C26&mn=sn-cu-ajtes%2Csn-5hne6nsz&ms=au%2Conr&mv=m&mvi=3&pl=25&initcwndbps=1883750&vprv=1&mime=video%2Fmp4&gir=yes&clen=415143429&dur=1703.666&lmt=1642829843754126&mt=1644049019&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgAKQa2lKMqka57jup5nPEaJ8jrFwkKwC6Qab42rip9cACIDP1W_O1wzOH0SkAELt_coagCCG4zwmV-8HkPbhsRvQ-&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJdUJaoNTIWiNwmCcza6hDS7Lgs8ian8Vks4tM4tqc_rAiBTgLbJw7lqF27FncS33DD6hYNSV-dQMLwIuzHhmJJA8g%3D%3D&host=rr3---sn-cu-ajtes.googlevideo.com 660.34ms
```
In fact, all of the log messages look the exact same (bar the timestamp and request time).

**Screenshots**

**Additional context**

I'm using Firefox and Invidious is running off an Arch Linux box. DASH videos work fine on other instances. I'm also using nginx as a reverse proxy, if that matters

**Comment by unixfox** [comment] 2022-02-05 09:47
How did you install Invidious? Can you use the latest version? You aren't running the latest one.

**Comment by lyiriyah** [comment] 2022-02-06 00:56
Sorry for the late reply. Just updated Invidious, issue still occurs.

`crystal --version`: 
```
Crystal 1.3.2 (2022-01-19)

LLVM: 13.0.0
Default target: x86_64-pc-linux-gnu
```

**Comment by Lexzach** [comment] 2022-02-06 04:38
Having this problem as well

**Comment by unixfox** [comment] 2022-02-06 09:40
Please downgrade to crystal 1.2.2. We don't support the latest version of crystal yet.

Duplicate of https://github.com/iv-org/invidious/issues/2783

**Closed by unixfox** 2022-02-06 09:40 UTC
Labels: question
