### ISSUE TITLE
[Question] DASH not working, only giving 403 Errors

### ISSUE THREAD

**Issue by andreasmolnardev** [iv-org/invidious#5086] opened 2024-11-19 19:05 UTC
On my selfhosted Invidious instance running on my Pi, whenever I set the quality to DASH, it starts throwing 403 errors.
I tried proxing Videos which did not make a difference. I also updated my Invidious instance to the latest docker arm64 docker compatible version

**Logs**

![Screenshot 2024-11-19 19 56 22](https://github.com/user-attachments/assets/a3cb60b1-2efe-4414-8cf6-54be61f173a4)

the errors also occur inside of the container, so it doesn't seem to be browser related to me:
`
2024-11-19 18:55:38 UTC [info] 403 GET /videoplayback?expire=1732063614&ei=Ht08Z9WiIqC_6dsP1ZHWwAM&ip=37.5.251.206&id=o-AAUjv-wim3mqp2z_MVNN2-xao6xn1PfW0zCcWSvt_B-5&itag=398&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1732042014%2C&mh=7c&mm=31%2C26&mn=sn-4g5e6nzl%2Csn-f5f7lnl6&ms=au%2Conr&mv=m&mvi=4&pl=23&rms=au%2Cau&initcwndbps=1836250&bui=AQn3pFQdFcfAybjJildRRFYMIZ8OhUncKoRyVthUreV_7bfwrAE3Cv0hkupN9yrNeFWBGeISSEk3Ga4E&spc=qtApAaRJaNIrE7CCwi81lpT-JLwp0z6Fb1hMbxiMa-k5Du0f0jxrpm5-Nso3&vprv=1&svpuc=1&mime=video%2Fmp4&ns=uuyYIITf5q1a3r9ED37UFrsQ&rqh=1&gir=yes&clen=15710398&ratebypass=yes&dur=212.040&lmt=1717049653514126&mt=1732041702&fvip=3&keepalive=yes&fexp=51299154%2C51312688%2C51326932%2C51335594%2C51348766&c=WEB&sefc=1&txp=4537434&n=ghCG5ohFmJvWZg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhANC9ZaLEvmrbXIdnKbjAatAzbRTOJw9U6WstY75iPR5aAiAcRDRmIeWTPXpg4HeM-ON4LWQx5D1_nHhZZxAcF_NARA%3D%3D&sig=AJfQdSswRAIgC2aj5jWWH7Nb2mx1JZ843lWST646yXgadoBwzEb5z3cCIBWG7K6Kl_RmYd4k8B1P-p8-dmQSCdL5qNDQn14XPWv1&pot=dWJa9FZTdy7b1Q9gzHwQxKXuLp4iKpcVQg1P7CTae57D03ddSJV1Pm9CcTyYYDFa 284.15ms
`

**Additional context**

 - Browser (if applicable): Google Chrome 130.0.6723.101 (Official Build) (64-bit) 
 - OS (if applicable): chromeOS
-->

**Comment by unixfox** [comment] 2024-11-19 20:42
are you using potoken method?

**Comment by andreasmolnardev** [comment] 2024-11-20 07:14
Currently i am not using potokens. I can try whether that fixes my issue.

**Comment by unixfox** [comment] 2024-11-20 07:54
Duplicate of https://github.com/iv-org/invidious/issues/4947

**Closed by unixfox** 2024-11-20 07:54 UTC
Labels: question
