### ISSUE TITLE
[Enhancement] More playback speed options like 2.5x 3x 1.1x

### ISSUE THREAD

**Issue by pritkr** [iv-org/invidious#2573] opened 2021-11-09 11:47 UTC

**Comment by unixfox** [comment] 2021-11-09 12:08
Not sure if it's a good idea to pollute the playback speed options with a lot of options at the same time.

I wish there were a hotkey for controlling the playback speed instead.

**Comment by syeopite** [comment] 2021-11-09 12:12
Duplicate of #533

**Closed by syeopite** 2021-11-09 12:12 UTC
Labels: enhancement
