### ISSUE TITLE
[Bug] youtu.be link lead to "javascript:void(0)"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2386] opened 2021-09-06 13:53 UTC
**Describe the bug**

If a comment contains `https://youtu.be/X?t=123` (I don't know if the timecode is what's causing this), its hyperlink lead to "javascript:void(0)".

**Steps to Reproduce**

N/A

**Logs**

N/A

**Screenshots**

N/A

**Additional context**

Related #2380

**Comment by SamantazFox** [comment] 2021-09-07 00:11
yep, it's due to the timestamp. This is a duplicate of #2020, btw

**Closed** 2021-09-10 07:46 UTC
Labels: bug
