### ISSUE TITLE
[Bug] On iPhone: Next video does not autoplay

### ISSUE THREAD

**Issue by ManiMatter** [iv-org/invidious#4019] opened 2023-07-27 15:14 UTC
When watching a playlist of videos on my iPhone, the next video is loaded after the previous one has ended, but the new video does not start to be played.

My settings of invidious are: 
- Autoplay: true
- Automatically next video: true
- Automatically play next video: true

On my macbook, the next video loads correctly and starts playing with the same settings. 

Tried this on separate networks (5G, 4G, Wifi), with 2 different devices (iPhone 13 Pro, iOS 16.5.1 / iPhone , iOS 16.5.1) with consistent same result (same bug).

**Comment by unixfox** [comment] 2023-07-27 16:30
Does it work on youtube though? I feel like it's a limitation of safari on iOS.

**Comment by ManiMatter** [comment] 2023-07-27 16:46
On youtube it works correctly. The next song is played automatically.

**Comment by unixfox** [comment] 2023-07-27 16:53
Can you reproduce the same issue on Firefox and chrome for ios?

**Comment by ManiMatter** [comment] 2023-07-27 16:54
I just downloaded both Firefox and Chrome for iOS and both show the same bug as Safari.
The new page opens, but the video does not start to play.

**Comment by latenightdef** [comment] 2023-08-06 06:33
This can be reproduced with Firefox (and Fennec F-Droid) on Android too, with these settings enabled
![image](https://github.com/iv-org/invidious/assets/64822291/0a664305-4ded-485a-b8bf-596135263fe3)

**Comment by absidue** [comment] 2023-08-08 17:12
From Apple's docs:
> A <video> element can use the play() method to automatically play without user gestures only when it contains no audio tracks or has its muted property set to true. If this video element gains an audio track or becomes unmuted without a user gesture, playback pauses.

https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari#3030259

So autoplay only works on iOS if the video is set to muted, otherwise it's blocked by Safari.

**Comment by ManiMatter** [comment] 2023-08-08 17:33
Thanks for looking into this.

When you play a video on invidious with "listen only" setting, you can actually lock the iPhone and the song continues.

Therefore, I feel this statement here does not apply here: 
"Playback stops if the video element isn't visible onscreen or is out of the viewport."

In consequence, if it doesn't apply, should't the next song load?

**Comment by absidue** [comment] 2023-08-08 17:34
No because it will continue playback after you the user has interacted with it, but when the new video loads, as you haven't interacted with it yet, it won't start playing automatically.

**Comment by ManiMatter** [comment] 2023-08-08 18:03
Got it!

Is there an ingenious way that invidious could treat listen-only videos not as videos, so that the next item could be autoplayed?

That would be very neat...

**Comment by unixfox** [comment] 2023-08-08 19:32
Closing as that's not possible, it's handled by videojs and we can't do anything on this side sorry.

**Closed by unixfox** 2023-08-08 19:32 UTC
Labels: bug
