### ISSUE TITLE
[Feature request] enque

### ISSUE THREAD

**Issue by imxade** [iv-org/invidious#3281] opened 2022-08-25 13:33 UTC
Would be great if invidious had a feature to **enque** multiple streams

**Screenshot of implemented feature**

![Screenshot_20220825-185846_NewPipe SponsorBlock](https://user-images.githubusercontent.com/56511165/186678182-538428e5-c135-4d81-b88b-e472c7fbeae7.png)
![Screenshot_20220825-185818_Via](https://user-images.githubusercontent.com/56511165/186678197-e1e0bb55-9e49-4201-a803-04236fd43413.png)

**Comment by unixfox** [comment] 2022-08-25 13:40
Duplicate of https://github.com/iv-org/invidious/issues/2419

**Closed by unixfox** 2022-08-25 13:40 UTC
Labels: feature-request
