### ISSUE TITLE
[Feature request] Fediverse comments with ActivityPub

### ISSUE THREAD

**Issue by leethax666** [iv-org/invidious#2705] opened 2021-12-08 06:56 UTC
It's great you support both YouTube and Reddit comments on Invidious, but supporting ActivityPub would be a step-up. 

Different Invidious instances could share comments and you could subscribe to user, video, or playlist comments on any of them. You could even add your own upvote/downvote, like Lemmy.ml uses, that could federate.

Also, users on Mastodon, etc, would be able to follow video comments on Invidious instances without leaving Mastodon

It might piss off Youtube more than normal, tho.

**Comment by unixfox** [comment] 2021-12-08 07:37
Duplicate of https://github.com/iv-org/invidious/issues/264

**Closed by unixfox** 2021-12-08 07:37 UTC
Labels: feature-request
