### ISSUE TITLE
[Bug] Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)

### ISSUE THREAD

**Issue by kitl000** [iv-org/invidious#3201] opened 2022-07-14 18:09 UTC
**Logs**
Title: `Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)`
Date: `2022-07-14T18:06:46Z`
Route: `/watch?v=zYw4xdlj2SQ`
Version: `2022.07.12-5ecf5bc6 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing JSON element "twoColumnWatchNextResults" (BrokenTubeException)
  from src/invidious/videos.cr:966:9 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:1111:10 in 'fetch_video'
  from src/invidious/videos.cr:1099:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>
-->

**Comment by unixfox** [comment] 2022-07-14 20:25
Duplicate of https://github.com/iv-org/invidious/issues/3200

**Closed by unixfox** 2022-07-14 20:25 UTC
Labels: bug
