### ISSUE TITLE
[Bug]+Invalid+Int32:+"@Simplicissimus"+(ArgumentError)

### ISSUE THREAD

**Issue by yatbz** [iv-org/invidious#3420] opened 2022-11-21 07:51 UTC
Title: `Invalid Int32: "@Simplicissimus" (ArgumentError)`
Date: `2022-11-21T07:47:46Z`
Route: `/search?q=simplicissimus`
Version: `2022.11.17-516efd2 @ master`

I just searched for a channel and this happend.
The same error message appears also for searching other channels (just with Simplicissimus replaced by the other name)

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@Simplicissimus" (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-11-21 20:02
Closing as a duplicate of #3394

**Closed by SamantazFox** 2022-11-21 20:02 UTC
Labels: bug
