### ISSUE TITLE
Title: `Invalid Int32: "@fangzhouzi-official" (ArgumentError)`

### ISSUE THREAD

**Issue by bwplan** [iv-org/invidious#3415] opened 2022-11-20 16:02 UTC
Title: `Invalid Int32: "@fangzhouzi-official" (ArgumentError)`
Date: `2022-11-20T16:01:27Z`
Route: `/search?q=%E6%96%B9%E8%88%9F%E5%AD%90`
Version: `2022.11.02-09942de @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@fangzhouzi-official" (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by bwplan** [comment] 2022-11-20 16:02
Title: `Invalid Int32: "@fangzhouzi-official" (ArgumentError)`
Date: `2022-11-20T16:01:27Z`
Route: `/search?q=%E6%96%B9%E8%88%9F%E5%AD%90`
Version: `2022.11.02-09942de @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32: "@fangzhouzi-official" (ArgumentError)
  from /usr/share/crystal/src/int.cr:957:11 in 'to_i32'
  from /usr/share/crystal/src/string.cr:333:5 in 'short_text_to_number'
  from src/invidious/yt_backend/extractors.cr:173:20 in 'process'
  from src/invidious/yt_backend/extractors.cr:707:17 in 'extract_item'
  from src/invidious/yt_backend/extractors.cr:738:28 in 'extract_items'
  from src/invidious/search/processors.cr:12:14 in 'process'
  from src/invidious/routes/search.cr:55:18 in 'search'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by SamantazFox** [comment] 2022-11-20 22:59
Closing as a duplicate of #3394

**Closed by SamantazFox** 2022-11-20 22:59 UTC
Labels: bug
