### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by darklighskully** [iv-org/invidious#1778] opened 2021-02-15 23:44 UTC
Title: trying to get into the channel 
Date: `2021-02-15T23:40:28Z`
Route: `/channel/UC7_YxT-KID8kRbqZo7MyscQ`
Version: `2021.01.31-26ce0eb @ (HEAD detached at 26ce0eb)`
<details>
<summary>Backtrace</summary>
<p>
   
```
Unexpected char '<' at 1:1 (JSON::ParseException)
  from ../../../usr/share/crystal/src/json/lexer.cr:371:7 in 'raise'
  from ../../../usr/share/crystal/src/json/lexer.cr:367:5 in 'unexpected_char'
  from ../../../usr/share/crystal/src/json/lexer.cr:366:11 in 'unexpected_char'
  from ../../../usr/share/crystal/src/slice.cr:229:5 in 'next_token'
  from ../../../usr/share/crystal/src/json/parser.cr:13:12 in 'get_60_videos'
  from src/invidious.cr:1716:20 in '->'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by hackerncoder** [comment] 2021-02-15 23:58
This appears to be a duplicate of #1637. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Closed by hackerncoder** 2021-02-15 23:58 UTC
Labels: duplicate
