### ISSUE TITLE
Red indicator on subscriptions page?

### ISSUE THREAD

**Issue by psychedelic-fox** [iv-org/invidious#1174] opened 2020-05-15 05:17 UTC
This probably isn't a bug, I just have no idea what it indicates.

[Here](https://imgur.com/EYaTaUp.png) is an example.

What does this marker mean?

**Comment by TheFrenchGhosty** [comment] 2020-08-20 21:21
Duplicate of https://github.com/iv-org/invidious/issues/1267

**Closed by TheFrenchGhosty** 2020-08-20 21:21 UTC
Labels: question
