### ISSUE TITLE
[Bug] Expected Hash for #[]?(key : String), not Array(JSON::Any) (Exception)

### ISSUE THREAD

**Issue by cal0mintal** [iv-org/invidious#3353] opened 2022-10-19 14:45 UTC
**Describe the bug**

When trying to load up the video link for Juan Antonio's "Aspargus II" 16-bit Minecraft computer, it instead crashes and lands on the aforementioned error log.
Instance: yewtu.be

**Steps to Reproduce**

1. Open up yewtu.be
2. Type "ohm 16-bit minecraft computer" into search bar
3. Click on 5th link within search results
4. There, error shows up

**Logs**

<details>
<summary>Backtrace</summary>
<p>
   
Title: `Expected Hash for #[]?(key : String), not Array(JSON::Any) (Exception)`
Date: `2022-10-19T14:05:32Z`
Route: `/watch?v=qZ2GRTiCdeA`
Version: `2022.10.19-2dfe9d9 @ master`

```
Expected Hash for #[]?(key : String), not Array(JSON::Any) (Exception)
  from src/invidious/yt_backend/extractors.cr:483 in '[]?'
  from /usr/lib/crystal/core/json/any.cr:124:5 in 'parse_video_info'
  from src/invidious/videos/parser.cr:92:12 in 'extract_video_info:video_id'
  from /usr/lib/crystal/core/hash.cr:1185:13 in 'fetch_video'
  from src/invidious/videos.cr:354:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from lib/kemal/src/kemal/config.cr:92:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call'
  from /usr/lib/crystal/core/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/lib/crystal/core/http/server.cr:500:5 in '->'
  from /usr/lib/crystal/core/fiber.cr:146:11 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '??'
```
</p>
</details>

**Screenshots**

![202210192231](https://user-images.githubusercontent.com/116180936/196723149-4364f53d-a79c-402b-82aa-4ded7cd2d8da.png)
![202210192235](https://user-images.githubusercontent.com/116180936/196723174-320b0610-6405-4e11-9be5-988bb76ac025.png)

**Additional context**

Browser + version: Microsoft Edge 106.0.1370.47
OS: Windows 10 Home Edition Single Language (21H2)

**Comment by unixfox** [comment] 2022-10-21 07:42
Caused by https://github.com/iv-org/invidious/pull/3238, closing for now.

**Closed** 2022-10-21 07:41 UTC
Labels: bug
