### ISSUE TITLE
[Feature request] Reflect the additional parameters on the list of videos

### ISSUE THREAD

**Issue by FrostBlade5** [iv-org/invidious#3329] opened 2022-09-27 15:48 UTC
Request summarized by @unixfox 

I would like that the additional parameters that I pass on a page that list videos are reflected on the links for viewing the videos.

For example, on the page `/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash` all the videos listed will have `quality=dash` in their URL.

This applies to:
- channel page
- playlist page
- feeds page (like popular feed)

-----

The default streaming quality with invidious / yewtu.be is 720p, i request to increase this value to 1080p because 720 looks somewhat blury, however if this request will be denied i have anotherone instead.

When i navigate to this video url https://yewtu.be/watch?v=xBC3JzlYrJ8 and then edit it by adding &quality=dash at the end, this will allow me to stream in 1080p.
However this method sadly only works with urls that are releated directly to a video.

I do not use a youtube (google) account for privacy reasons, instead i use a windows bat file to instantly open all my favorite youtube channels.
This is one of them:
https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q
I tried adding &quality=dash to the end of the channel url but instead of changing to a 1080p version, i saw this:
"This channel does not exist."
My request should be clear now, if 1080p cannot become the new standard please add a new function to switch to dash quality (1080p) by adding &quality=dash to the end of any indivious channel url.

I do not save cookies for privacy reasons by browser will not remember if i set invidious to stream in 1080p and i don't want to change it manually every single time...

**Comment by SamantazFox** [comment] 2022-09-27 22:24
https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash

URL queries have to start with `?`. `&` is the field delimiter. For instance:
`https://example.com/path?key1=value1&key2=value2`

**Comment by FrostBlade5** [comment] 2022-09-28 03:43
> https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash
> 
> URL queries have to start with `?`. `&` is the field delimiter. For instance: `https://example.com/path?key1=value1&key2=value2`

Oh that was easy, thank you very much!

**Comment by FrostBlade5** [comment] 2022-09-28 03:50
> https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash
> 
> URL queries have to start with `?`. `&` is the field delimiter. For instance: `https://example.com/path?key1=value1&key2=value2`

When i go to https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash the url works but when i klick on a video the ?quality=dash is removed and the video will only play in 720p instead of 1080p (dash), not sure wht i'm supposed to do?

**Comment by unixfox** [comment] 2022-09-28 11:31
I've edited the title and I made a summary of your request so that it's easier to understand your feature request.

> When i go to https://yewtu.be/channel/UCgFP46yVT-GG4o1TgXn-04Q?quality=dash the url works but when i klick on a video the ?quality=dash is removed and the video will only play in 720p instead of 1080p (dash), not sure what i'm supposed to do?

That's not yet implemented, so indeed it doesn't work.

**Comment by unixfox** [comment] 2022-09-28 14:42
We are volunteers that work on our free time, so there is no estimate time for any feature request created. We are only 2 developers in the project and there are a lot of other features request opened: https://github.com/iv-org/invidious/labels/feature-request

If you want to have this feature as quickly as possible, the best way is to start implementing it yourself (by programming).

**Comment by unixfox** [comment] 2022-09-28 15:10
Please keep this issue on topic. If you want to discuss more about it please join our IRC channel: https://web.libera.chat/?channel=#invidious

Or matrix channel: https://matrix.to/#/#invidious:matrix.org

**Comment by FrostBlade5** [comment] 2022-09-28 15:25
Alright, will go there for "off topic" questions.

Just one question, hope u don't mind (it's not releated to this issue but i wanted to ask you personaly, i found invidious when i was searching for youtube alternatives to avoid google.
First i saw there is a so called "no cookie" version of youtube, but it doesn't work anymore, then i found invidious as a great solution. Question is, how does nvidious know/find out all the google-video-urls to stream youtube videos? How do you get these urls? If the anser is long and complicated, don't mind just ignore me.. just curious because i wanted to use no-cookie version of yt but didn' work. https://www.youtube-nocookie.com/ (this url does not work...) but if you add the term "embed" and the specific video url to it then it works, but how do i get the specific video url like you do with invidious?

**Comment by unixfox** [comment] 2022-09-28 16:55
Please stop being off-topic, join our IRC or matrix channel for offtopic questions: https://github.com/iv-org/invidious/issues/3329#issuecomment-1261058467

**Comment by SamantazFox** [comment] 2022-09-29 05:27
Closing as a duplicate of https://github.com/iv-org/invidious/issues/2130

**Closed** 2022-09-29 06:51 UTC
Labels: feature-request
