### ISSUE TITLE
Missing hash key: "runs" (KeyError)

### ISSUE THREAD

**Issue by lvarma** [iv-org/invidious#1596] opened 2020-12-21 17:41 UTC
I have Invidition add-on in my Firefox. I performed an Youtube search through Firefox address bar, using the keyword "tube [searchterm]". This usually shows the Youtube search URL in address bar for a second and then redirects to Invidious and opens the search results in Invidious interface. 

This time the search returned the following error message: (this is my first time posting on GitHub, I'm just trying to describe the problem to the best of my capabilities)

Looks like you've found a bug in Invidious. Please open a new issue on GitHub and include the following text in your message:

Title: `Missing hash key: "runs" (KeyError)`
Date: `2020-12-21T17:13:40Z`
Route: `/search?q=monsp+tape&page=1`
Version: `2020.12.14-1380058 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "runs" (KeyError)
  from ../usr/share/crystal/src/hash.cr:1027:11 in '[]'
  from ../usr/share/crystal/src/json/any.cr:102:7 in '[]'
  from src/invidious/helpers/helpers.cr:264:47 in 'extract_item'
  from src/invidious/helpers/helpers.cr:326:13 in 'extract_items'
  from src/invidious/search.cr:259:3 in 'search'
  from src/invidious/search.cr:445:20 in 'process_search_query'
  from src/invidious/routes/search.cr:51:37 in 'search'
  from src/invidious.cr:317:1 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'process_request'
  from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/websocket_handler.cr:13:14 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:212:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:145:12 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:70:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/logger.cr:16:5 in 'call'
  from ../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from ../usr/share/crystal/src/http/server/request_processor.cr:50:11 in 'process'
  from ../usr/share/crystal/src/http/server.cr:513:5 in 'handle_client'
  from ../usr/share/crystal/src/http/server.cr:468:13 in '->'
  from ../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ../usr/share/crystal/src/fiber.cr:92:34 in '->'
  from ???
```
</p>
</details>

Released under the AGPLv3 by Omar Roth.
BTC: bc1qfhe7rq3lqzuayzjxzyt9waz9ytrs09kla3tsgr
XMR: Click here
Documentation
View JavaScript license information. / View privacy policy.
Current version: 2020.12.14-1380058 @ master

**Comment by Sigma-One** [comment] 2021-02-05 15:13
I can confirm this issue, seems to happen if some specific substrings appear in the query. One such substring is "endzeit bunke", which appears as a substring in the query I encountered this bug with, and it looks like on the original report by Ivarma, "monsp" is the string triggering the bug based on my testing.

My attached report is from https://invidious.048596.xyz, however, I could also reproduce the issue on https://invidious.snopyta.org and https://tube.connect.cafe

Generated report is as follows:

Title: `Missing hash key: "runs" (KeyError)`
Date: `2021-02-05T15:03:12Z`
Route: `/search?q=endzeit+bunkertracks+viii`
Version: `2021.01.27-f07aed5 @ serving5`
<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "runs" (KeyError)
  from ../../../usr/share/crystal/src/hash.cr:1030:9 in '[]'
  from ../../azhao/invidious/src/invidious/helpers/helpers.cr:268:47 in 'extract_item'
  from ../../azhao/invidious/src/invidious/helpers/helpers.cr:330:13 in 'extract_items'
  from ../../azhao/invidious/src/invidious/search.cr:259:11 in 'search'
  from ../../azhao/invidious/src/invidious/search.cr:445:20 in 'search'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from ../../../usr/share/crystal/src/time.cr:356:5 in 'call'
  from ../../../usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from ../../azhao/invidious/lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from ../../../usr/share/crystal/src/http/server.cr:498:5 in '->'
  from ../../../usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```
</p>
</details>

**Comment by Sigma-One** [comment] 2021-02-05 15:23
Update to my previous comment, I believe the issue may actually be caused by certain results appearing in the search, as anything that may turn up the result I was searching for (a certain music album) causes this crash. Those searches including intentional misspellings of the title along with the name of the label that published this album. I do not have time currently to pinpoint any exact result that may be causing the bug, however if this hypothesis is corrrect, at least one should appear in the results for at least the queries "alfa matrix", "endzeit bunkertracks", and various slight misspellings of the latter.

**Comment by saltycrys** [comment] 2021-02-09 23:45
The cause for this is if a playlist has a `Various Artists` author. Instead of `item["ownerText"]["runs"][0]["text"]` it's `item["ownerText"]["simpleText"]` here: https://github.com/iv-org/invidious/blob/c9a316ad353cd1ee38c34d1aff0759765b37b2b3/src/invidious/helpers/helpers.cr#L234

This can probably be fixed by adding a bunch of question marks.

**Closed** 2021-02-10 00:12 UTC
Labels: bug, priority:critical, type:backend
