### ISSUE TITLE
[Feature request] Bypass age restriction

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#2992] opened 2022-03-27 20:07 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, i can't watch a video because "This video may be inappropriate for some users".

**Describe the solution you'd like**
A system to bypass the restriction, even if i have to admit that i don't even know if it's technically possible.

**Comment by unixfox** [comment] 2022-03-27 21:19
Duplicate of https://github.com/iv-org/invidious/issues/2189

**Closed by unixfox** 2022-03-27 21:19 UTC
Labels: feature-request
