### ISSUE TITLE
[Bug] Error 500 on loading comments on all public instances - breaks healthchecks with docker

### ISSUE THREAD

**Issue by Sommerwiesel** [iv-org/invidious#4497] opened 2024-03-28 18:58 UTC
**Describe the bug**
Sometimes, loading comments results in error 500.

**Steps to Reproduce**

1. Choose any public instance, click on video, comments don't load
or
2. manually run the healtcheck command in an invidious container

-->

**Logs**
**docker exec:**
/invidious $ wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/commen
ts/jNQXAC9IVRw
Connecting to 127.0.0.1:3000 (127.0.0.1:3000)
wget: server returned error: HTTP/1.1 500 Internal Server Error

**Screenshots**
[Screenshot-20240328-195136.png](https://postimg.cc/0M7BzF0K)

**Comment by net00-1** [comment] 2024-03-28 23:50
I am seeing this issue in my private instance (docker), comments won't load most of the time. They will pop up after a few refreshes though.

The issue is intermittent though

```
Invidious_1     | 2024-03-28 23:37:53 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 549.85ms
invidious_1     | 2024-03-28 23:38:23 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 493.16ms
invidious_1     | 2024-03-28 23:38:54 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 417.63ms
invidious_1     | 2024-03-28 23:39:24 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 411.61ms
invidious_1     | 2024-03-28 23:39:55 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 465.63ms
invidious_1     | 2024-03-28 23:40:26 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 499.56ms
invidious_1     | 2024-03-28 23:40:56 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 498.81ms
invidious_1     | 2024-03-28 23:41:27 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 472.7ms
invidious_1     | 2024-03-28 23:41:57 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 574.83ms
invidious_1     | 2024-03-28 23:42:28 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 509.58ms
invidious_1     | 2024-03-28 23:42:59 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 467.11ms
invidious_1     | 2024-03-28 23:43:29 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 462.02ms
invidious_1     | 2024-03-28 23:44:00 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 366.33ms
invidious_1     | 2024-03-28 23:44:30 UTC [info] 500 GET /api/v1/comments/jNQXAC9IVRw 515.23ms
invidious_1     | 2024-03-28 23:45:01 UTC [info] 200 GET /api/v1/comments/jNQXAC9IVRw 390.04ms
```

**Comment by SamantazFox** [comment] 2024-03-30 15:29
It's because Youtube is still A/B testing a change in the format of the comments response.

**Comment by unixfox** [comment] 2024-04-07 02:45
Closing in favor of https://github.com/iv-org/invidious/issues/4566

**Closed by unixfox** 2024-04-07 02:45 UTC
Labels: bug
