### ISSUE TITLE
Invalid Int32: (ArgumentError) (https://invidious.kavin.rocks/) [Bug] 

### ISSUE THREAD

**Issue by Sangonomiya** [iv-org/invidious#2453] opened 2021-10-03 22:17 UTC
**Describe the bug**
Good evening, I encountered an error on a instance when visiting a channel.
I tried to import my subscription data and found that the amount of channels was one lower than expected. I filtered it out and tried to visit said channel -> then I stumbled upon this error, which I presume is at fault for failing to import the channel I was missing. If I made a mistake or formatting error or whatever feel free to point it out: I do not commonly report GitHub bugs (rarely needed to) so just say it if I did something wrong.

**Steps to Reproduce**
Go to https://invidious.kavin.rocks/channel/UCePpoSlomqhfAWcAtSSY2ew
(The page was already loading very slowly; then this error appeared instead of the channel, I refreshed a few minutes after the error to be sure)

**Logs**
Title: `Invalid Int32:  (ArgumentError)`
Date: `2021-10-03T22:02:55Z`
Route: `/channel/UCePpoSlomqhfAWcAtSSY2ew`
Version: `2021.10.02-81b12b8 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
```
Invalid Int32:  (ArgumentError)
  from /usr/share/crystal/src/string.cr:432:5 in 'to_i32'
  from /usr/share/crystal/src/pointer.cr:130:6 in 'decode_length_seconds'
  from src/invidious/helpers/extractors.cr:77:113 in 'process'
  from src/invidious/helpers/extractors.cr:532:17 in 'extract_item'
  from src/invidious/helpers/extractors.cr:556:28 in 'extract_items'
  from src/invidious/helpers/helpers.cr:251:15 in 'extract_videos'
  from src/invidious/channels/videos.cr:72:19 in 'get_60_videos'
  from src/invidious/routes/channels.cr:38:22 in 'videos'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from /src/boringssl/src/google-boringssl-251b516/ssl/internal.h:334:8 in '???'
```
</p>
</details>

**Additional information**
Instance: `https://invidious.kavin.rocks/` (Kavin Rocks India instance, NOT the US or JP instance)
User Agent: `Firefox 92.0.1 (64-bit)`
Others: `Please comment if you require additional information not listed.`

**Comment by unixfox** [comment] 2021-10-04 06:24
Duplicate of https://github.com/iv-org/invidious/issues/2449

**Closed** 2021-10-04 06:24 UTC
Labels: bug
