### ISSUE TITLE
Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)

### ISSUE THREAD

**Issue by McMac** [iv-org/invidious#3821] opened 2023-05-26 06:21 UTC
Title: `Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)`
Date: `2023-05-26T05:54:43Z`
Route: `/watch?v=B1vqKQIPxr0`
Version: `2023.05.25-381a0e3 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Hostname lookup for www.youtube.com failed: Try again (Socket::Addrinfo::Error)
  from /usr/share/crystal/src/socket/addrinfo.cr:132:7 in 'initialize'
  from /usr/share/crystal/src/gc/boehm.cr:192:5 in 'io'
  from /usr/share/crystal/src/http/client.cr:671:5 in 'send_request'
  from /usr/share/crystal/src/http/client.cr:651:20 in '_post_json'
  from src/invidious/videos/parser.cr:59:21 in 'extract_video_info:video_id'
  from src/invidious/videos.cr:377:10 in 'fetch_video'
  from src/invidious/videos.cr:365:13 in 'get_video:region'
  from src/invidious/routes/watch.cr:63:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by McMac** [comment] 2023-05-26 06:23
> docker exec -it invidious-invidious-1 /bin/sh
/invidious $ nslookup www.yahoo.com
;; connection timed out; no servers could be reached

/invidious $ cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
/invidious $

**Comment by unixfox** [comment] 2023-05-26 06:39
This issue have been opened multiple times, please search before opening one...

https://github.com/iv-org/invidious/issues/3538
https://github.com/iv-org/invidious/issues/3664
https://github.com/iv-org/invidious/issues/2967

Closing as it's a DNS server issue on your end and not a bug...

**Closed by unixfox** 2023-05-26 06:39 UTC
Labels: question

**Comment by McMac** [comment] 2023-05-26 15:12
Other containers are working.
Pihole is standalone (on a RPi) not a container (what your links point to).

**Comment by unixfox** [comment] 2023-05-26 15:46
That's truly the worst idea to do, that's like getting around the real problem, which is that your setup have a broken DNS resolution that need to be fixed. (or the DNS server chosen by docker is not the correct one)

I bet some other containers won't work with DNS resolution too, other real applications not an empty container like busybox.

Anyway, out of the box Invidious works fine without any issue at all and it's tested here for every new changes in the code: https://github.com/iv-org/invidious/blob/master/.github/workflows/ci.yml#L125

**Comment by McMac** [comment] 2023-05-26 17:20
What can I say, lookup in busybox is working - what difference does it make for a plain nslookup if it is empty or not?! 
nslookup is also ok within freshrss container, docker-socket-proxy and a few others where there is no custom network and where I do have nslookup. 
This is my docker-compose:

```yml
version: '2'
services:
  invidious:
    image: quay.io/invidious/invidious:latest
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3030:3000"
#    dns:
#      - 172.16.20.2
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: ****
          host: <extdbhost>
          port: 5433
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
```
I just don't see it.

**Comment by McMac** [comment] 2023-05-26 18:06
@unixfox - not sure what is going on. Did a Synology update several days back so not sure why the issue didn't pop up not right away. Also, why on my system only invidious seems to have an issue. The requests do show up in Pihole but somehow the response doesn't make it back to the IV container... don't know. 
 (I use invidious a lot so would have seen right away! Thank you for it!!! 👍)
As it is working with the dns parameter but not without, there is something else going on that isn't reproducible for me right now.
Cheers. 👋🏻

**Comment by McMac** [comment] 2023-05-26 19:06
@unixfox issue resolved! Turns out that my synology still had the old dns entries listed in it's /etc/resolv.conf. 

#1 olddns1 (<-- pihole on container)
#2 olddns2 (<-- old router ip)
#3 newdns1 (<-- new & correct pihole on a dedicated RPi 3)

Why this only caused issues on some containers (like IV) and not others I am guessing it might possibly be related to how each base image is handling multiple dns entries (or only handle 2). Looks like some would keep trying through the list until it hits a valid dns (which would explain why the working nslookups seem working albeit slow). 
The IV base build however only tried the 1st (? and 2nd?) dns which was/were no longer reachable.

So you were right, not an IV issue really but as you said DNS but with a completely different root cause. Hopefully this thread is helpful to anyone with such an odd case. 🙂

**Comment by SamantazFox** [comment] 2023-05-27 17:53
Sorry, but I have to post this classic:
![image](https://github.com/iv-org/invidious/assets/52980486/90c6c08f-e1e0-4bfc-b937-83fb613948d4)

**Comment by McMac** [comment] 2023-05-29 17:11
... at least I am trying to give helpful feedback so others don't run into the same issue respectively for them figure it out themselves. I could have just left it open-ended and not "embarrass myself". 
Sure, @SamantazFox posting a dumb picture is very much helpful. Well done! 👍🏻
My apologies for not being such a grand wizard as you are. I'm sure you feel better about yourself. 🙂
