### ISSUE TITLE
[Question] How to disable auto-generated captions?

### ISSUE THREAD

**Issue by haorenxu** [iv-org/invidious#3303] opened 2022-09-05 15:37 UTC
My "default captions" setting is "none/none/none," but the auto-generated English captions always show up. Can I disable it?

Edit: My iMac (M1, MacOS 12.5.1, Safari) has this problem, but on Mac mini (Intel, MacOS 12.5.1, Safari), the captions are off by default. They are use the same instance that runs on my VPS.

**Comment by SamantazFox** [comment] 2022-09-11 21:51
What do you mean by "the auto-generated English captions always show up"?
Are the captions showing up in the list, or are they displayed on the video?

**Comment by haorenxu** [comment] 2022-09-12 02:05
> What do you mean by "the auto-generated English captions always show up"?
> Are the captions showing up in the list, or are they displayed on the video?

They are displayed on the video, therefore I have to manually turn it off every time I open a new video.

**Comment by SamantazFox** [comment] 2022-09-12 05:04
Does it happen on all videos? Have you checked if there is an option in Safari for captions (as it varies between your mac machines)? What version of invidious do you have?

**Comment by unixfox** [comment] 2022-09-12 06:42
Probably a duplicate of https://github.com/iv-org/invidious/issues/2710

**Comment by haorenxu** [comment] 2022-09-12 07:11
> Does it happen on all videos? Have you checked if there is an option in Safari for captions (as it varies between your mac machines)? What version of invidious do you have?

It happens on all videos (on my M1 iMac), and as I know, Safari have no such caption options. My Invidious version is the newest one (docker).

> Probably a duplicate of #2710

It looks like the same problem. Interestingly it does not happen on my Intel Mac mini. By the way, my M1 iMac is 24", and the Intel Mac mini is using a 19" monitor, though I think this is not relevant.

**Comment by unixfox** [comment] 2022-09-12 08:20
I'll then close this issue and we can continue the discussion on https://github.com/iv-org/invidious/issues/2710

**Closed by unixfox** 2022-09-12 08:20 UTC
Labels: question
