### ISSUE TITLE
[Bug] Missing hash key: "selected" (KeyError)

### ISSUE THREAD

**Issue by zeilsandayo** [iv-org/invidious#3171] opened 2022-06-30 12:49 UTC
**Describe the bug**

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

Title: `Missing hash key: "selected" (KeyError)`
Date: `2022-06-30T12:46:47Z`
Route: `/channel/UC6-oZfglyFHe-Kubz-7XBYw/community`
Version: `2022.06.13-6c73614 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Missing hash key: "selected" (KeyError)
  from /usr/share/crystal/src/hash.cr:1080:9 in '[]'
  from src/invidious/channels/community.cr:16:133 in 'fetch_channel_community'
  from src/invidious/routes/channels.cr:84:26 in 'community'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:167:15 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>

**Comment by unixfox** [comment] 2022-06-30 12:52
Duplicate of https://github.com/iv-org/invidious/issues/3154

**Closed by unixfox** 2022-06-30 12:52 UTC
Labels: bug
