### ISSUE TITLE
[Bug] Cannot add URL parameters to the main page

### ISSUE THREAD

**Issue by Elaborendum** [iv-org/invidious#2208] opened 2021-06-25 22:37 UTC
**Describe the bug**

In every instance I have tried until now, every time you add any URL parameter to the Main Page's URL it just reloads again and ditches the URL parameter. No settings are applied either. Is this intentional or am I just doing it wrong?

**Steps to Reproduce**
1. Go to the main page of any instance
2. Add any URL parameter, like "&dark_mode=false" to the end of its URL
3. Press enter

**Additional context**
 - Browser (if applicable): Firefox
 - OS (if applicable): Windows

**Comment by SamantazFox** [comment] 2021-06-26 09:13
The first URL parameter should be preceeded by `?`, instead of `&`. So it looks like:

- `https://example.com/some/url/with/1/param?param1=value1`
- `https://example.com/some/url/with/2/param?param1=value1&param2=value2`

**Comment by unixfox** [comment] 2021-06-26 10:34
Closing as this is not a bug but a malformed URL.

**Closed by unixfox** 2021-06-26 10:34 UTC
Labels: bug
